### ISSUE TITLE
Does not display arch in the payload section

### ISSUE THREAD

**Issue by Cropi** [rpminspect/rpminspect#1001]
**Describe the bug**
Rpminspect shows that many (sub)packages are missing after latest build of usbguard even though those are present. In the most recent change, we decided to not build/ship it for i686 anymore, so this is why the warnings are present but I would expect rpminspect to detect that the sub-packages are missing only for that particular arch and not for all. In the **lostpayload** section it does not display which arch the warning applies to, so I would assume that it applies to all. However, in other sections it is able to display which archs are affected.

```
[VERIFY] Existing subpackage usbguard is now missing
Suggested remedy:
Check to see if you eliminated a subpackage but still have the %package and/or the %files section for it.
... 
```

**To Reproduce**

/usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml --workdir /var/ARTIFACTS/work-rpminspectmrnh6xuf/rpminspect/discover/default-0/tests/workdir/ --format=json --output=/var/ARTIFACTS/work-rpminspectmrnh6xuf/rpminspect/execute/data/rpminspect/data/result.json --verbose --release=el9 usbguard-1.0.0-10.el9_0.1 49938315

**Expected behavior**
Rpminspect is able to tell which subpackages have been removed for certain architectures.

**Additional info**
rpminspect version 1.11
zlib version 1.2.11
libmagic version 539
libclamav version 0.103.7
librpm version 4.16.1.3
libxml version 20913
json-c version 0.14
libcurl version 7.76.1 (OpenSSL/3.0.1 zlib/1.2.11 nghttp2/1.43.0)
libarchive version 3.5.3 (zlib/1.2.11 liblzma/5.2.5 bz2lib/1.0.8 liblz4/1.9.3 libzstd/1.5.1)
libyaml version 0.2.5
OpenSSL version 3.0.1 14 Dec 2021
xmlrpc-c version 1.51.0
msgunfmt (GNU gettext-tools) 0.21
annocheck version 10.94.
abidiff version 2.2.0
kmidiff version 2.2.0

Space required to download artifacts: 63176169 bytes (60 MiB)
Space required to unpack artifacts: 288564615 bytes (275 MiB)

**Environment:**
 - RHEL

**Comment by dcantrell** [comment]
Great explanation and thanks for the suggestion.  Patch coming momentarily to improve the reporting on this inspection.
