### ISSUE TITLE
license inspection rejects a valid "Artistic 2.0 and (GPL+ or Artistic)" license

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#101]
Copied from <https://bugzilla.redhat.com/show_bug.cgi?id=1804115>:

~~~~
$ rpminspect -T license noarch/perl-Specio-0.45-3.fc33.noarch.rpm 
license:
--------
1) Invalid License Tag in perl-Specio-0.45-3.fc33.noarch: Artistic 2.0 and (GPL+ or
Artistic) 
Result: BAD
Waiver Authorization: Not Waivable

Suggested Remedy: The License tag must contain an approved license string as defined by
the distribution (e.g., GPLv2+).  If the license in question is approved, the license
database needs updating in the rpminspect-data package.

Result: OK
~~~~

Expected result is OK. Compare to a different package with a simpler license:

~~~~
$ rpminspect -T license noarch/perl-IPC-Run-20180523.0-7.fc33.noarch.rpm 
license:
--------
1) Valid License Tag in perl-IPC-Run-20180523.0-7.fc33.noarch: GPL+ or Artistic 
Result: INFO

Result: OK
~~~~

A reply from David Cantrel:

The problem string here is "(GPL+ or Artistic)".  The license inspection should
look for that before further breaking it down.  What the inspection currently
does is tokenize the string, throw out all the boolean words and parens, and
checks for each license token in the license JSON database.

**Comment by ppisar** [comment]
If I implemented the inspection, I would simply substituted the good licenses with OK and the unknown licenses with BAD and let the expression evaluate. I.e. (Artistic 2.0 and (GPL+ or Artistic)) would reduce from (OK and (OK or BAD)) to OK. But do whatever you like.

**Comment by dcantrell** [comment]
Yeah, that would be clean and easy but the problem is the license database is more complicated with abbreviations.  It's not strictly broken down in to short tags.  It in the case of "GPL+ or Artistic" that's the entire token I need to look in the database for.  GPL+ and Artistic by itself are not listed and/or not approved.

Working on a fix right now which preserves the existing complicated break down of the License field.

**Comment by dcantrell** [comment]
I've got a patch now that continues to check each token but will also check parenthesized expressions in their entirety in case the individual token failed.  If this passes my current tests, I'll call it good enough.  But any further changes to this inspection and I'm just taking it to lex and yacc.  Should have done that in the first place.  :)
