### ISSUE TITLE
Weird error: "Invalid License Tag: MIT and (BSD or ASL 2.0)"

### ISSUE THREAD

**Issue by hroncok** [rpminspect/rpminspect#102]
Hello.

I see the following error in https://fedora.softwarefactory-project.io/logs/31/31/6f7da3bf055f7f118e2293d38d754c590ad3d07a/check/rpm-rpminspect/8ee2c33/rpminspect.html

**Message: Invalid License Tag in python-setuptools-45.2.0-1.fc33.noarch: MIT and (BSD or ASL 2.0)**

What's invalid about that? All three `fedora_abbrev`s are listed in https://github.com/rpminspect/rpminspect-data-fedora/blob/master/licenses/fedora.json since at least v0.1.

**Comment by dcantrell** [comment]
That is correct and this is a bug in librpminspect.  I recently expanded the license test to account for parenthesized substrings that are approved but individually the tokens are not approved.  I'll make sure this one continues to pass.

**Comment by hroncok** [comment]
Thanks.
