### ISSUE TITLE
How do I specify source path for `ignore` in `unicode` check?

### ISSUE THREAD

**Issue by omajid** [rpminspect/rpminspect#1020]
https://github.com/rpminspect/rpminspect/blob/8f83a5e4f44ea322d01aaaa3d64146b57b374382/data/generic.yaml#L933-L939

The example given is for RPM binary paths? But the check applies to "extracted and patched source code files, scripts, and spec files". How do I specify these paths? Where should I root them?

**Comment by dcantrell** [comment]
The ignore paths are relative to the root of the archive or package payload, with or without the leading /.  So for a binary package, all are relative to the root filesystem.  For a source package, it's relative to the extracted source archive.  That is, the directory that the spec file unpacks and possibly patches in %prep.  You can reference paths in a source archive like this:

```
unicode:
    ignore:
        - libsomething-1.2.3/src/bigfile.c
```
