### ISSUE TITLE
Support for security rules for the virus inspection

### ISSUE THREAD

**Issue by thoger** [rpminspect/rpminspect#1026]
**Describe the bug**
Issue #1025 requests making virus inspection failures WAIVABLE_BY_SECURITY.  If that is done, there's also an associated need to have centralized way to allow-list certain acceptable failures (e.g. when eicar test file is included in a test suite of some package).  Adding a "virus" rule type to the existing security rules mechanisms would make sense.

**Comment by dcantrell** [comment]
I'm thinking in the data/security/ files, adding "virus=" which can be SKIP, INFORM, VERIFY, or FAIL.  I believe this is what you described, but I just want to confirm.  If this is sufficient, the modification will be easy to rpminspect.

Thoughts @thoger ?
