### ISSUE TITLE
bogus debuginfo: `Lost: .symtab`

### ISSUE THREAD

**Issue by t184256** [rpminspect/rpminspect#1028]
**Describe the bug**
I'm getting `Lost: .symtab` in debuginfo during differential comparisons, despite this not seeming to be the case:
* `readelf` on reported files doesn't confirm that
* flipping old->new to new->old still results in `Lost: .symtab`

Might be related to rework done in https://github.com/rpminspect/rpminspect/pull/994

**To Reproduce**
* `rpminspect -a x86_64 -Tdebuginfo -c /usr/share/rpminspect/fedora.yaml gnutls-3.7.8-9.fc38 gnutls-3.7.8-11.fc38`, observe `Lost: .symtab`
* `rpminspect -a x86_64 -Tdebuginfo -c /usr/share/rpminspect/fedora.yaml gnutls-3.7.8-11.fc38 gnutls-3.7.8-9.fc38`, observe `Lost: .symtab`, express doubt

**Expected behavior**
No `Lost: .symtab` in debuginfo output.

**Environment:**
 - Fedora 37 x86_64
 - rpminspect-1.11-0.1.202301181551git8ff3c2f.fc37
 - rpminspect-data-fedora-1.10-0.1.202301091929giteeb0ee8.fc37

**Comment by t184256** [comment]
OK, even simpler reproducer: one can compare the package to itself and still get these messages

**Comment by dcantrell** [comment]
Thanks for the report, I've been able to easily reproduce this.  Hopefully the fix is easy, which would mean it was just me doing something stupid in the code.

**Comment by dcantrell** [comment]
I've got a patch, but the test suite fails.  Will be able to finish this tomorrow.

**Comment by dcantrell** [comment]
OK, I've got a fix for the reported problem.  Test suite passes.  But now it's reporting that all of the /usr/lib/guile/2.2/site-ccache/.../*.go files contain .symtab.  Indeed they do.  file(1) reports them as not stripped.

Is this expected or should those files also be stripped?  If it is correct, then you may need to add those paths to the ignore list for the debuginfo inspection in the package's rpminspect.yaml file.

**Comment by t184256** [comment]
That I don't know, unfortunately, but this sounds like something orthogonal to the original report.

**Comment by dcantrell** [comment]
I may have answered my own question.  I think this is just how compile Guile objects work.  It is orthogonal, but the debuginfo inspection still fails for your package comparisons here so that's what I'm trying to get to pass.  It's ok, I see what I need to add now.
