### ISSUE TITLE
individual rpminspect tests in the HTML report are not sorted

### ISSUE THREAD

**Issue by kkaarreell** [rpminspect/rpminspect#1062]
**Describe the bug**
Current HTML report presents all rpminspect test in a table. However items in this table are not sorted (alphabetically) so finding one particular test is quite difficult. It would be good to have tests sorted by name.

I am not filing it as a RFE since it feels to me more like a usability bug.

**To Reproduce**
Simply observe the HTML report

**Expected behavior**
Test names in a table are sorted by name.

**Comment by dcantrell** [comment]
The order they appear in now is the order in which I wrote the inspections.  Sorting is fine.  I can do that in the program itself which would carry over the sorted results to the other output modes.
