### ISSUE TITLE
Clear distinction in results output between comparison errors and baseline analysis errors

### ISSUE THREAD

**Issue by mulkieran** [rpminspect/rpminspect#1070]
**Is your feature request related to a problem? Please describe.**

In new Fedora release of stratisd, we were building some executables differently and they were flagged with errors.

See here:
* https://bodhi.fedoraproject.org/updates/FEDORA-2023-11d44a0dbc
* https://artifacts.dev.testing-farm.io/d15f5242-9d0e-4b4d-aca4-f834040702e3/

It appears that the elf errors were comparison errors but the debuginfo errors were baseline analysis errors.

We would likely react differently to the different kinds of errors. For the first kind, we would likely just waive them after investigation, because, since they are comparison errors, we would expect them not to show up again. For baseline analysis errors, on the other hand, we might like to specify something in our package level rpminspect.yaml file, so that we can ignore them. Unfortunately, we can't distinguish between the two kinds of errors by viewing the results. We can find out by doing another release and seeing which continue to be reported and which don't, but that's time-consuming. In the particular case we're in now, the errors are also architecture-specific, so local testing using rpminspect would require reserving a machine with the somewhat non-standard architectures on which the errors show up.

**Describe the solution you'd like**
A clear distinction in the results output between the comparison and base analysis errors. An extra tag in the results.json output would be a good first step, but ideally this would also end up in the human readable display also.

**Describe alternatives you've considered**
None, really. I think that the other ways to figure out what kind of error is being reported, e.g, making additional releases, inspecting rpminspect source, would all take too much time and effort.

**Additional context**
None.

**Comment by dcantrell** [comment]
So you want something in the output that identifies the error as the result of a comparision between builds or just an analysis of the after build?  In your example, I'm not sure that's really necessary.  For the comparison errors, what you should do is submit a PR to rpminspect-data-fedora (and -centos and probably -redhat) with per-file rules on how to handle the GNU_RELRO finding.  For example, I would set it to relro=SKIP for the files in question.  Alternatively, you could skip the problem files in the elf inspection.  The overrides with "relro=SKIP" would have to go in the vendor data package and that has to be by PR.

For the debuginfo inspection findings, you can either add the problem files to the debuginfo inspection ignore list or you can redefine the debuginfo_sections.  The default is provided by the vendor data package (e.g., rpminspect-data-fedora) but those may actually vary depending on what language was used.  Stratis is in Rust, right?  Do those debuginfo files have .symtab?  If not, just redefine debuginfo_sections in your rpminspect.yaml file.  If you do that, make sure to comment it in your rpminspect.yaml for future onlookers know why it's there.
