### ISSUE TITLE
Do not include work directory in the unicode results messages

### ISSUE THREAD

**Issue by thoger** [rpminspect/rpminspect#1073]
**Describe the bug**
The unicode inspection performs unpacking of the source rpm files.  Unpacking is done using work directories and names of those work directories can be included in results messages, even though any suppression configuration (such as ignore list entries) is only supposed to contain relative paths starting from the top level directory created during package extraction.

At least the following types of messages were found to include work directory names:

- path to expanded source tree starting with "unpack-XXXXX"
- path to patch files from SRPM with a full path to the work directory

**Expected behavior**
Results messages should not include work directory and should correspond to what needs to be used in the suppression configuration.

**Comment by omajid** [comment]
:+1: 

This tripped me up at https://github.com/rpminspect/rpminspect/issues/1020 too

**Comment by dcantrell** [comment]
Can you give me a build I can use to recreate the behavior you saw?
