### ISSUE TITLE
Infinite loop when reading empty rpminspect.yaml file

### ISSUE THREAD

**Issue by thoger** [rpminspect/rpminspect#1087]
**Describe the bug**

When an rpminspect.yaml file in the current directory is "empty" - meaning it either has size of 0 or only contains white spaces and comments and no uncommented configuration directives - it causes rpminspect to enter what seems to be an infinite loop repeatedly producing this error message:

```
rpminspect: skipping token type YAML_STREAM_END_TOKEN
rpminspect: ignoring malformed rpminspect configuration file: /path/to/current/directory/rpminspect.yaml
rpminspect: *** error reading '/path/to/current/directory/rpminspect.yaml': Invalid argument
```

This is a regression, most likely related to the recent major changes to config file reading.

**To Reproduce**

Create rpminspect.yaml using any of the following commands:

```
$ > rpminspect.yaml

$ echo "# comment" > rpminspect.yaml

$ echo -e "   \n\n\n" > rpminspect.yaml
```

Running `rpminspect foo.rpm` (foo.rpm does no need to exist) triggers looping.

**Environment:**

rpminspect-1.11-0.1.202302142024git0d7d9a7.fc37.x86_64

**Comment by dcantrell** [comment]
Good find, reasonable enough to include in v1.11.

**Comment by dcantrell** [comment]
https://www.youtube.com/watch?v=DNb4VKln1uw
