### ISSUE TITLE
RFE: Output from rpminspect --dump-config option discoverable in output of testing farm run

### ISSUE THREAD

**Issue by mulkieran** [rpminspect/rpminspect#1097]
**Is your feature request related to a problem? Please describe.**
Want to know what configuration specifications are being obeyed in a run on testing-farm, currently can not tell.

**Describe the solution you'd like**
Output of --dump-config available on results page, or in some log file.

**Describe alternatives you've considered**
None.

**Additional context**
Related to #1069

**Comment by dcantrell** [comment]
The -D/--dump-config option just dumps the combined configuration data at runtime to stderr.  I can change how rpminspect outputs this info, but within the testing farm how that information is displayed to users is up to that integration.  I would talk to them first and see what would work best and then if there's something I need to do in rpminspect to adjust how -D outputs the configuration data, file a new RFE for that.
