### ISSUE TITLE
Fileinfo checks duplicated in both permissions and addedfiles inspections

### ISSUE THREAD

**Issue by thoger** [rpminspect/rpminspect#1105]
**Describe the bug**

I noticed that both permissions and addedfiles inspections call match_fileinfo_mode(), which leads to most reports about inconsistencies with the expected state defined in fileinfo files are duplicated in both inspections.  One difference is that in case of addedfiles inspection, a remedy text is provided.  Alerts are not duplicated when fileinfo expects a file to be setuid or setgid, but it does not have any of that set in the package, as addedfiles only calls match_fileinfo_mode() for files (and not directories) with setuid or setgid bit set.

I do not really see a reason for this duplication, but it's possible that I'm overlooking something important.  What is the reason for calling match_fileinfo_mode() from both inspections?

**To Reproduce**

Run rpminspect with both permissions and addedfiles inspections enabled on an rpm, which includes a setuid or setgid binary not listed on the corresponding fileinfo list.

**Expected behavior**

Avoid duplicated reports of the same problem.

**Comment by dcantrell** [comment]
There's no real design reason for the duplication, other than this is how things were done in rpminspect's ancestor.  I do not think it makes sense, but I was also aiming for mostly functional parity.  I think it makes sense to move the match_fileinfo_mode() checks to the permissions inspection and drop them from the addedfiles inspection.  What do you think?
