### ISSUE TITLE
Unhandled patch file `patch-%{rpmversion}-redhat.patch` defined in spec file

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#1114]
**Describe the bug**

This is probably due to this recently merged patch: https://github.com/rpminspect/rpminspect/commit/c6b98863e5d64769548755ad3f4bb16de5515c25

kernel and kernel-rt builds in RHEL started failing the patches inspection with the following message:
```
Unhandled patch file `patch-%{rpmversion}-redhat.patch` defined in spec file
```

From the spec file:
```
Patch1: patch-%{rpmversion}-redhat.patch
```

**To Reproduce**

```
/usr/bin/rpminspect-redhat -T patches -a src --verbose --release=el9 --profile=rhel-9 kernel-rt-5.14.0-162.18.1.rt21.181.el9_1 51115108
```

**Expected behavior**

**Environment:**
 - RHEL

```
+ rpm -qa
+ grep rpminspect
librpminspect-1.11-0.1.202303022042gitf7c1fcb.el9.x86_64
rpminspect-1.11-0.1.202303022042gitf7c1fcb.el9.x86_64
rpminspect-data-redhat-1.8-0.1.202302281838git148ef5d.el9.noarch
```

**Comment by dcantrell** [comment]
I knew this would happen.  This is going to be a "chase the macros" type thing until the patch inspection handles enough macros in spec files so it is not a problem.  I can get this fixed quickly.
