### ISSUE TITLE
Missing license database(s) error in license check despite license data installed

### ISSUE THREAD

**Issue by ckelleyRH** [rpminspect/rpminspect#1117]
**Describe the bug**
The `license` check is failing with  `rpminspect: problem adding entries to array vendor->licensedb` and `1) Missing license database(s)`.  See this [failed CI run](https://github.com/ckelleyRH/pki/actions/runs/4414601385/jobs/7736672566) for the gritty detail. I have tried locally on an F37 machine with the same result. The linked CI run uses a custom profile but my local reproduction does not, simply running the freshly installed latest `rpminspect` packages was sufficient to reproduce. 

**To Reproduce**
```
# On F37...
dnf install -y rpminspect-*
rpminspect-fedora  -T license <some_rpm>
```

**Expected behavior**
The `license` check finds the `licensedb` entries correctly and executes normally.  

**Environment:**
F37 latest as of 14th March 2023.
```
rpm -qa | grep rpminspect
librpminspect-1.11-1.fc37.x86_64
rpminspect-1.11-1.fc37.x86_64
rpminspect-data-centos-1.1-3.fc37.noarch
rpminspect-data-fedora-1.9-2.fc37.noarch
rpminspect-data-generic-1.11-1.fc37.x86_64
``` 
...and also `fedora-license-data-1.14-1.fc37.noarch`

**Comment by ckelleyRH** [comment]
Possibly linked to #858?

**Comment by dcantrell** [comment]
This is caused by the licensedb: setting in the /usr/share/rpminspect/fedora.yaml file in rpminspect-data-fedora-1.9.  If you install rpminspect-data-fedora from my Copr repo you will get a correctly formatted fedora.yaml file.  However, Copr is down at the moment for https://github.com/fedora-copr/copr/issues/2534.  But I need to release a new rpminspect-data-fedora anyway, so I will do that and push it out as an update.

**Comment by ckelleyRH** [comment]
> This is caused by the licensedb: setting in the /usr/share/rpminspect/fedora.yaml file in rpminspect-data-fedora-1.9. If you install rpminspect-data-fedora from my Copr repo you will get a correctly formatted fedora.yaml file. However, Copr is down at the moment for [fedora-copr/copr#2534](https://github.com/fedora-copr/copr/issues/2534). But I need to release a new rpminspect-data-fedora anyway, so I will do that and push it out as an update.

Great, thanks!

**Comment by dcantrell** [comment]
OK, rpminspect-data-fedora-1.10 released, built, and pushed as testing updates in Fedora and EPEL.

Doing rpminspect-data-centos next.
