### ISSUE TITLE
Warning about existance of /usr/etc

### ISSUE THREAD

**Issue by hhorak** [rpminspect/rpminspect#1133]
**Is your feature request related to a problem? Please describe.**
It's related to osbuild feature that expects `/usr/etc` to not exist. When it happens (like in `npm` package), it makes the osbuild fail: https://bugzilla.redhat.com/show_bug.cgi?id=2177776
Since FHS does not specify `/usr/etc`, it seems to be a packaging issue that should be captured early on.

**Describe the solution you'd like**
Detect that an RPM ships something under `/usr/etc`.

**Describe alternatives you've considered**
Do the check outside of rpminspect, but this tool looks pretty good fit.

**Additional context**
https://bugzilla.redhat.com/show_bug.cgi?id=2177776 might have more context soon.

**Comment by dcantrell** [comment]
You can add /usr/etc to the list of forbidden_path_prefixes under the addedfiles section of /usr/share/rpminspect/fedora.yaml.

Submit a PR to the https://github.com/rpminspect/rpminspect-data-fedora project with this change and it will do what you are looking for.  If this applies to CentOS, be sure to submit an MR to rpminspect-data-centos on gitlab.com and if it applies to RHEL, be sure to submit an MR to the internal rpminspect-data-redhat project on gitlab.cee.
