### ISSUE TITLE
Warn about ignored sections in rpminspect.yaml

### ISSUE THREAD

**Issue by omajid** [rpminspect/rpminspect#1150]
**Is your feature request related to a problem? Please describe.**

rpminspect flagged some unicode issues in my packages. I added a `unicode` section to my `rpminspect.yaml` file following the template here: https://github.com/rpminspect/rpminspect/blob/8eefc18b2d610d5c0b1abe9094ecb6df84adcbce/data/generic.yaml#L898-L938

My configuration was ignored. rpminspect didn't tell me it's ignored. That made me frustrated because my configuration wasn't being picked up. I thought it was a bug in rpminspect.

(It turns out that `unicode` is only configurable via the centralized vendor policy.)

**Describe the solution you'd like**
Could rpminspect warn me when there's configuration in `rpminspect.yaml` that is unknown (or known but rpminspect not going to use it)?

**Describe alternatives you've considered**

- Maybe there could be a separate `rpminspect-lint` program that we could run manually to get warnings?

**Additional context**

**Comment by dcantrell** [comment]
A warning in the diagnostics output is what I wanted to do here, but I saved this until after the bulk of the security changes were done.  There are still two more that I need to push PRs for, but I should have them done soon.
