### ISSUE TITLE
Excluding files for unicode inspection needs to take into account where the source archive is extracted

### ISSUE THREAD

**Issue by jchecahi** [rpminspect/rpminspect#1157]
**Describe the bug**
Unicode inspection unpacks some source archives manually (not using rpm API) in a separate directory such as `/var/tmp/rpminspect/local.XXXXXX/rpmbuild/BUILD/unpack-XXXXXX`.  Looking to #1073 it seems like it shouldn't be taking that last `unpack-XXXXXX` directory into account for reporting. Also not clear to me, but looks like it shouldn't take that into account for ignored files.

I'm trying to add an unicode exception for a file inside one of those manually unpacked source files (clang-tools-extra-16.0.1.src), and I must specify `unpack-*/clang-tools-extra-*.src/<rest_of_path>` in order to make it work.

Looking into the source, it seems like [this check](https://github.com/rpminspect/rpminspect/blob/959e480c414b01468dd0529f3a3542437559208d/lib/inspect_unicode.c#L429) assumes that `build` contains the whole path up to `unpack-XXXXXX` but instead point to its parent dir: `BUILD`, but I might be wrong.

Hence adding this to `security/el8` in `rpminspect-data-<vendor>` (in my case `rpminspect-data-redhat`) makes the inspection to *not* ignore the file:
```
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  clang  *  *  unicode=INFORM
``` 
While line makes the inspection to ignore the file and hence pass the unicode inspection:
```
unpack-*/clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  clang  *  *  unicode=INFORM
```

**To Reproduce**
```
rpminspect-redhat -v -w ~/builds -f rhel8-8080020230119204057.fd72936b
rpminspect-redhat -k -v -T unicode -a src ~/builds/llvm-toolset-rhel8-8080020230119204057.fd72936b
```

**Expected behavior**
It should be possible to add ignored files without taking into account whether the source archive will be extracted manually in a `rpmbuild/BUILD/unpack-XXXXXX` directory or directly into `rpmbuild/BUILD`.

**Comment by dcantrell** [comment]
This reads like a bug.  My intent is to make source tree specification relative to an invisible root tree but relative to the extracted SRPM.  Within that you would have extracted and patched source archives.  So think of it as a tree that would look like the result of `fedpkg prep` in a dist-git repo in Fedora.

Files that are directly in the SRPM can be references as is.  For example, a file name `extrasource.c` in the SRPM as a SourceN file can be referenced in a unicode rule as `extrasource.c`.  For an unpacked source tree, it would be whatever that unpacked source archive would be named, something like `mainsource-*/src/something.c`.

If you are only seeing things work when specifying them with the unpack-* and internal rpminspect tmp dir names, something is wrong.  I will investigate this and see what I need to do.

**Comment by dcantrell** [comment]
Because this package ends up using the manual_prep_source() function, I was not properly accounting for the unpack-XXXXXX/ subdirectories I was creating for extraction.  Patch coming.

**Comment by dcantrell** [comment]
And I also found that it's processing source files twice, so that's another fix.  Either way, patch coming for this.

**Comment by jchecahi** [comment]
Thanks for looking into this!

**Comment by dcantrell** [comment]
Sure thing, it's not a problem.  I mean, I want this to work as intended.

This one sure is like peeling an onion.  The llvm case is a really good one to help illustrate how the code path should work in the unicode inspection.  I've hit another condition where I think the most flexible course of action will be to record visited failing files.  The patch continues to evolve.

**Comment by dcantrell** [comment]
OK, strike the previous comment.  Since this is a module with multiple SRPMs, rpminspect has to scan each one.  Rather than keep a log of visited source files, what the user should do is add multiple rules to the security/RELEASE file in the vendor data package.  For this package I have tested:

```
# llvm module
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  clang       *  *  unicode=INFORM
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  lld         *  *  unicode=INFORM
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  libomp      *  *  unicode=INFORM
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  llvm        *  *  unicode=INFORM
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  lldb        *  *  unicode=INFORM
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  python-lit  *  *  unicode=INFORM
```

The wildcard is not allowed for the package name so that rules are more explicit and we have a better understanding of what's going in to each package.

I also thought about the idea of keeping track of visited source in cases where modules have duplicate sources, but that's not implied in modules and makes the code path more complicated when really additional rules in the security/PRODUCT file work.

With the forthcoming patch and the above rules added to the vendor data package, the unicode inspection passes for the llvm module.

**Comment by jchecahi** [comment]
I agree with @thoger: having to add the rule for each package contained in the module, even when the source(s) don't belong to those packages doesn't seem right to me.

I have taken another look at the code and I think there are some things that are not quite right. If I'm understanding the code correctly, this is what it does, very high level:
1. From `inspect_unicode` function, it takes all the files from each unpacked `src.rpm`, and for each one of them, it runs `unicode_driver`.
2. If the file is a `.spec` file, `unicode_driver` "preps" it in `build` (which is typically `/var/tmp/rpminspect/local.XXXXXX/rpmbuild/BUILD/`) with `rpm_prep_source`. If this fails, `rpm_prep_source` calls `rmtree()` on `build`. In this case `unicode_driver` tries to manually unpack with `manual_prep_source`.
3. `unicode_driver` walks the tree under `/var/tmp/rpminspect/local.XXXXXX/rpmbuild/BUILD/`, running `validate_file` on each file.
4. `unicode_driver` reports back the result inpection in `globalresult`

However in the llvm-toolset module use case I can see several problems. I'll try to illustrate it with an example:
1. `inspect_unicode` starts with the first srpm, let's say it's `libomp`. Calls `unicode_driver` for each file until it reaches `libomp.spec`.
2. `unicode_driver` calls `rpm_prep_source` on `libomp.spec` successfully, now the directory pointed by `build` contains an unpacked source of `openmp-<version>`
3. `unicode_driver` walks the tree pointed by `build` with `validate_file` on each file. Finishes and reports back to `inspect_unicode`
4. `inspect_unicode` takes the next one, `lldb` and does the same process. When it gets to `lldb.spec` file `unicode_driver` unpacks it in `build`, and now this tree contains a source of lldb **and** a source of openmp. `unicode_driver` runs the inspection on **both** sources, being openmp source inspected by second time.
5. `inspect_unicode` takes now the problematic package, `clang`. When it gets to `clang.spec`, `unicode_driver` passes it to `rpm_prep_source` and this fails, so it calls rmtree on `build`, removing the previously unpacked sources of openmp and lldb. Then calls `manual_prep_source` and now `build` contains two `unpack-XXXXXX` folders, one for `clang` and other for `clang-tools-extra` sources. Back on `unicode_driver` this runs `validate_file` on these unpacked sources, and returns to `inspect_unicode`
6. `inspect_unicode` takes the next one, so to say `compiler-rt.spec`, prepares, and `unicode_driver` walks `build` tree inspecting the sources, including previously unpacked `clang` and `clang-tools-extra`.

This process keeps going, with `inspect_unicode` preparing each spec file under the tree pointed by `build`. Each time, the sources prepared there from previous spec files are re-inspected. Whith the last spec file, each file in clang and clang-tools-extra sources would have been inspected 5 times. Also, following this example, you wouldn't need to include the rule matching `libomp` and `lldb` because when those inspections happen, `clang` sources haven't been unpacked yet.

If there is no need to keep the unpacked sources under `build` after running rpminspect, maybe it would make sense to clean up the `build` tree after each inspecting each srpm. Maybe [after setting](https://github.com/rpminspect/rpminspect/blob/feb53a1e7ea5583fcf151df915f8208be6a53d86/lib/inspect_unicode.c#L616) the `seen` variable?

Otherwise if the sources need to be kept, an option might be to somehow match the sources extracted to the package it belongs to, so you can walk only the sub-trees that belong to the srpm you are inspecting at any moment. Also in this case, take into account that `rpm_prep_source` removes the entire `<tmp>/rpmbuild/BUILD` tree, including any previously unpacked sources.

**Comment by dcantrell** [comment]
Oh yeah, I should be clearing out the unpacked sources.  My assumption here is that each SRPM was using those source archives differently.  I did not dig in to it closely enough.

I would still prefer that users explicitly list SRPM names, but that's my personal opinion.

Let me update the patch here.

**Comment by dcantrell** [comment]
Alright, with the latest update to the PR I am cleaning the temp unpacking directory and there is now just the single rule required for security/el8 in the vendor data package:

```
# llvm module
clang-tools-extra-*.src/docs/clang-tidy/checks/misc/misleading-bidirectional.rst  clang       *  *  unicode=INFORM
```
