### ISSUE TITLE
find_file_peers() has quadratic behavior, for compares of kernel packages it takes tens of minutes

### ISSUE THREAD

**Issue by dvlasenk** [rpminspect/rpminspect#1194]
I added this debug printout in lib/peers.c
```
        /* match up file peers between builds */
        if (peer->before_files && peer->after_files) {
fprintf(stderr, "find_file_peers >\n");
            find_file_peers(peer->before_files, peer->after_files);
fprintf(stderr, "find_file_peers <\n");
        }
```
and when I run `rpminspect-fedora -p rawhide -Dv -k -t VERIFY -w $PWD/TEMPDIR -a x86_64,noarch,src kernel-6.3.0-0.rc7.56.fc39 kernel-6.3.0-63.fc39` with pre-downloaded kernel-* directories, I see this (the lines with dots are the output of a performance monitoring tool):
```
find_file_peers >
00:29:52 U.......................................................................................    0    0
....
00:39:16 S.......................................................................................    0 8192
00:39:17 S.......................................................................................    0    0
00:39:18 S.......................................................................................    0    0
find_file_peers <
```
IOW: it spends ~10 minutes there. It would probably run into ~50 minutes if the compare wouldn't be limited to just x86_64.

I dug deeper and added this:
```
static Elf *get_elf_with_kind(const char *fullpath, int *out_fd, Elf_Kind kind)
{
....
    elf = elf_begin(fd, ELF_C_READ_MMAP_PRIVATE, NULL);
fprintf(stderr, "get_elf_with_kind('%s'): elf_kind(elf):%d kind:%d\n", fullpath, (int)elf_kind(elf), (int)kind);
```
I found out that through
```
bool is_elf(const char *path)
{
    return (is_elf_file(path) || is_elf_archive(path));
}
```
the get_elf_with_kind() gets called very, very, VERY many times. It translates to lstat()+open()+mmap()+close() per each call. This is why it takes 10 minutes to run all find_file_peers().

For example, (randomly picking a file), before/x86_64/usr/src/debug/kernel-6.3-rc7/linux-6.3.0-0.rc7.56.fc39.x86_64/arch/x86/mm/ident_map.c had been get_elf_with_kind()'ed  3284 times.

In total, the comparison run has 262076 extracted files, and there were 138342270 (138 million) get_elf_with_kind() calls.

I suggest: in extract_rpm(), in this code:
```
        /* Write the file to disk */
        if (archive_read_extract(archive, entry, archive_flags) != ARCHIVE_OK) {
            warnx("archive_read_extract: %s", archive_error_string(archive));
            free_files(file_list);
            file_list = NULL;
            goto cleanup;
        }
```
inspect the beginning of each file. If it's neither `"{0x7f}ELF"` nor `"!<arch>"` bytes at the beginning, record the information that the file is neither "is_elf_file" nor "is_elf_archive", and avoid calling get_elf_with_kind() on it ever again.

(Yes, this is not that trivial, need to replace archive_read_extract() with something which exposes the data stream... but efficiency matters, writing and *re-reading* the data from disk will be markedly slower).

Maybe, for efficiency, we can just save a few (16?) first bytes of each written file? Using this saved data, some other checks can probably be made much faster too.

For files which do need the check, record check result on the first call and reuse it, do not lstat()+open()+mmap()+close() 3284 times per file.

**Comment by dcantrell** [comment]
This is also a good idea for an improvement.  I'll work on this one after I finish up the libcurl changes.  Thanks for digging in to this and coming up with a good place for improvement.
