### ISSUE TITLE
fedora-ci.koji-build.rpmdeplint.functional checks for parallel installation of non-multilib packages

### ISSUE THREAD

**Issue by jwakely** [rpminspect/rpminspect#1205]
**Is your feature request related to a problem? Please describe.**

https://bugzilla.redhat.com/show_bug.cgi?id=2174300 is a test failure caused by conflicts in tbb-doc.i686 and tbb-doc.x86_64, however that is not a multilib package, so users can never install the i686 package on an x86_64 without downloading it manually (in which case it's their own fault).

**Describe the solution you'd like**

If Fedora CI passed the multilib-readiness down to rpminspect then the particular test could be executed only when it makes sense.

**Describe alternatives you've considered**

In this case, the package should probably just be `noarch`, and it wouldn't be an issue. So this is probably not a priority because it won't happen for properly-packaged packages.

**Comment by dcantrell** [comment]
Looking in to this I see it's coming from rpmdeplint rather than rpminspect.  Is this something that rpmdeplint is doing that should be handled by rpminspect?  Or is it just an rpmdeplint bug?  If the latter, I would instead report the issue to rpmdeplint.

https://github.com/fedora-ci/rpmdeplint-pipeline
https://pagure.io/rpmdeplint

**Comment by jwakely** [comment]
> Looking in to this I see it's coming from rpmdeplint rather than rpminspect. Is this something that rpmdeplint is doing that should be handled by rpminspect? 

Dunno :shrug: 

> Or is it just an rpmdeplint bug? If the latter, I would instead report the issue to rpmdeplint.

OK, I've opened https://github.com/fedora-ci/rpmdeplint-pipeline/issues/45 now, so feel free to close this. Thanks.

**Comment by dcantrell** [comment]
Thanks, and sorry for any confusion re: rpminspect vs. rpmdeplint.

**Comment by jwakely** [comment]
No prob, thanks for your help!
