### ISSUE TITLE
Don't run Unicode check on po files

### ISSUE THREAD

**Issue by mcatanzaro** [rpminspect/rpminspect#1213]
**Describe the bug**
The Unicode inspection does not like LTR or RTL control codes. For example:

```
A forbidden code point, 0x202A, was found in the glib-2.68.4/po/yi.po source file on line 675 at column 47. This source file is used by glib2.spec.
```

This is not useful because it forbids development of internationalized software. Understanding that programmers can escape the codepoints in source files, we should not expect translators to understand escape sequences and should not start removing these control codes from po files.

**To Reproduce**
```
/usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml --workdir /var/ARTIFACTS/work-rpminspect9s5ejrm3/rpminspect/discover/default-0/tests/workdir/ --format=json --output=/var/ARTIFACTS/work-rpminspect9s5ejrm3/rpminspect/execute/data/guest/default-0/rpminspect-1/data/result.json --verbose --release=el9 --profile=rhel-9 glib2-2.68.4-6.el9 53740663
```

**Expected behavior**
Just skip over the po files.

**Environment:**
 - RHEL 9, architecture unknown

**Comment by dcantrell** [comment]
Yeah, this has been reported in a few other places.  I was working on a way to accomodate po files via this inspection, but I think you're right and it's just not possible.

**Comment by juhp** [comment]
Thanks

**Comment by dcantrell** [comment]
I already had code to do this, but it was only running for files in the SRPM.  In the extracted source tree I had a different code path that also checked the MIME type *but* was not trimming the MIME type string of everything from the ';' on, which happened in the other code path.  I have fixed this and a PR is coming momentarily.

**Comment by mcatanzaro** [comment]
Thanks!
