### ISSUE TITLE
rpminspect complains about "forbidden Unicode code point" in a test sample

### ISSUE THREAD

**Issue by keszybz** [rpminspect/rpminspect#1228]
> A forbidden code point, 0x202D, was found in the systemd-254/test/fuzz/fuzz-unit-file/oss-fuzz-6977-unminimized source file on line 3 at column 37753. This source file is used by systemd.spec.

This is not a text file. It is not unicode. This warning is not useful.

https://artifacts.dev.testing-farm.io/1806385f-f7e9-416c-bc32-b33e1e6d2893/

**Comment by keszybz** [comment]
Also:
> Suggested remedy:

> The rpminspect configuration file contains a list of forbidden Unicode code points. One was found in the extracted and patched source tree or in one of the text source files in the source RPM. Either remove this code point or discuss the situation with the Product Security Team to determine the correct course of action.

This is just bad advice. I'm sure Product Security Team has better things to do than to discuss fuzzer samples in random projects packaged for Fedora.

**Comment by dcantrell** [comment]
> > A forbidden code point, 0x202D, was found in the systemd-254/test/fuzz/fuzz-unit-file/oss-fuzz-6977-unminimized source file on line 3 at column 37753. This source file is used by systemd.spec.
> 
> This is not a text file. It is not unicode. This warning is not useful.
> 
> https://artifacts.dev.testing-farm.io/1806385f-f7e9-416c-bc32-b33e1e6d2893/

I add a rule for this in the rpminspect-data-fedora package under security/fc39:

https://github.com/rpminspect/rpminspect-data-fedora/blob/main/security/fc39

I am not sure if the same rule applies to CentOS and RHEL, but if so you will want to submit PRs for those projects too.

**Comment by dcantrell** [comment]
> Also:
> 
> > Suggested remedy:
> 
> > The rpminspect configuration file contains a list of forbidden Unicode code points. One was found in the extracted and patched source tree or in one of the text source files in the source RPM. Either remove this code point or discuss the situation with the Product Security Team to determine the correct course of action.
> 
> This is just bad advice. I'm sure Product Security Team has better things to do than to discuss fuzzer samples in random projects packaged for Fedora.

Don't shoot the messenger.  :)

I was instructed to direct Unicode BiDi findings to the Product Security Team.  I am fine changing the wording here, but I could not come up with anything better.

**Comment by keszybz** [comment]
Thanks!
