### ISSUE TITLE
rpminspect complains about commonly-used functions

### ISSUE THREAD

**Issue by keszybz** [rpminspect/rpminspect#1229]
>  /usr/lib/systemd/tests/unit-tests/test-dnssec may use forbidden functions on i686
> Forbidden symbols were found in an ELF file in the package. The configuration settings for rpminspect indicate the named symbols are forbidden in packages. If this is deliberate, you may want to disable the badfuncs inspection. If it is not deliberate, check the man pages for the named symbols to see what API functions have replaced the forbidden symbols. Usually a function is marked as deprecated but still provided in order to allow for backwards compatibility. Whenever possible the deprecated functions should not be used.
> Forbidden function symbols found:
>	inet_addr

In this particular use, the use is entirely correct. It is test code which checks for specific return values for specific addresses. And the function is documented as deprecated by the man page, because it has corner cases which don't work well, but that is no reason to forbid it in general. For most packages, the use in the package may actually be correct, and the packager is not able to rewrite the upstream code to remove the use, so they are not in a position to resolve this.

Also, entirely disabling the test is not good advice. IMO, the warning should indicate how to ignore a specific symbol, possibly just in a specific binary or a group of binaries. If people disable the test entirely, they could miss the user of other functions which are added in subsequent versions.

**Comment by dcantrell** [comment]
Add this to the package's rpminspect.yaml file in dist-git:

```
---
badfuncs:
    allowed:
        /usr/lib/systemd/tests/unit-tests/test-dnssec:
            - inet_addr
        /usr/lib/systemd/tests/unit-tests/test-network:
            - inet_addr
            - inet_aton
        /usr/lib/systemd/tests/unit-tests/test-resolve:
            - inet_addr
        /usr/lib/systemd/tests/unit-tests/test-resolved-etc-hosts:
            - inet_addr
        /usr/bin/networkctl:
            - inet_aton
```

I explain this in the data/generic.yaml file in the source tree (https://github.com/rpminspect/rpminspect/blob/main/data/generic.yaml#L809).  I should really take some time to work on finalizing documentation for the project.
