### ISSUE TITLE
Unable to find task xyz in Koji hub ("wrapperRPM" build task)

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#1241]
**Describe the bug**

rpminspect downloads RPMs when I provide a build name:
```
$ rpminspect-redhat -v octavia-amphora-image-x86_64-18.0-20230807.6.el9ost
Downloading RPM build octavia-amphora-image-x86_64-18.0-20230807.6.el9ost
=> octavia-amphora-image-x...230807.6.el9ost.src.rpm  [^C                                                    ]
```

However, when I specify a task ID instead, rpminspect fails to download the RPMs:
```
$ rpminspect-redhat -v 54486121
rpminspect: *** unable to find task 54486121 in Koji hub https://brewhub.engineering.redhat.com/brewhub
```

Note this is not the typical "build" Brew task, it's called "wrapperRPM". So that might be the reason why rpminspect fails in this case. All normal "build" tasks work fine.

**To Reproduce**
```
$ rpminspect-redhat -v 54486121
rpminspect: *** unable to find task 54486121 in Koji hub https://brewhub.engineering.redhat.com/brewhub
```

**Expected behavior**
rpminspect can download RPMs for "wrapperRPM" build tasks

**Environment:**
 - RHEL CI

**Comment by dcantrell** [comment]
The wrapperRPM method does present a different XML-RPC to gathering similar info.  I almost have a patch ready.
