### ISSUE TITLE
Javadoc aren't consistent despite best efforts

### ISSUE THREAD

**Issue by cipherboy** [rpminspect/rpminspect#125]
I've tried several times to get javadocs for my package to build consistently. On the same runner, I frequently get [very](https://github.com/dogtagpki/jss/pull/479/files) | [minor](https://github.com/dogtagpki/jss/pull/477/files) | [changes](https://github.com/dogtagpki/jss/pull/450) for no apparent reason at all. This type of minor change also happens across different architectures &c.

This results in rpminspect output like:

```json
...
     {
       "result": "VERIFY",
       "waiver authorization": "Anyone",
       "message": "File \/usr\/share\/javadoc\/jss-4.4.9\/org\/mozilla\/jss\/provider\/java\/security\/package-summary.html changed content on s390",
       "remedy": "Unexpected file changes were found.  Verify these changes are correct.  If they are not, adjust the build to prevent file changes."
     },
...
```

Could/should these be conditionally whitelisted based on rpminspect config?

---

For anyone else with javadoc building experience, my full command line is:

```bash
$ javadoc -overview /path/to/overview.html -windowtitle $TEXT -notimestamp -breakiterator -classpath $CLASSPATH -sourcepath $SOURCEPATH -d $OUTPUTPATH @/path/to/files.txt
```

**Comment by dcantrell** [comment]
I think this could be handled with an expansion of the changedfiles inspection to honor a changedfiles_path_exclude setting in the rpminspect.conf file (or the profile).  It would be regexp syntax similar to elf_path_exclude.

Thoughts?

**Comment by cipherboy** [comment]
Sounds good to me, thanks @dcantrell!

**Comment by dcantrell** [comment]
rpminspect now supports per-inspection ignore lists.  You can list explicit files or use glob(7) syntax to exclude only certain files per-inspection.  There is the global ignore list, but rpminspect lets you do per-inspection ignores which you can use to handle these cases.

Were this in gating, I would suggest creating an rpminspect.yaml file in the dist-git repo with the following contents:

```
---
changedfiles:
    ignore:
        # javadoc files are slightly different on each build and can trigger a false positive on changed content
        - /usr/share/javadoc/jss-*/org/mozilla/jss/provider/java/security/package-summary.html
```

You would commit that to the dist-git repo and be done with it.
