### ISSUE TITLE
Do not report not-allowed license for packages that are known to be exceptions

### ISSUE THREAD

**Issue by xsuchy** [rpminspect/rpminspect#1286]
Recently fedora-license-data added `packages_with_exceptions` to source data.
  https://gitlab.com/fedora/legal/fedora-license-data/-/blob/main/TEMPLATE.toml?ref_type=heads#L99

It would be great if rpmlint could recognize this field and e.g. do not report license issues for fedora-logos package because it is known exception
  https://gitlab.com/fedora/legal/fedora-license-data/-/blob/main/data/LicenseRef-Fedora-Logos.toml?ref_type=heads#L13

**Comment by dcantrell** [comment]
What will this data look like when written to the generated JSON file?  rpminspect reads from the JSON file and not the individual TOML files.

**Comment by xsuchy** [comment]
I wanted to point you to schema definition, but I forgot to add it to schema! I will fix it.
You can check mkjson.py in fedora-license-data. It is already there as `licensedata[i]["license"]["packages_with_exceptions"]` and it should be already presented in JSON artifact.

**Comment by dcantrell** [comment]
Perfect, thanks!
