### ISSUE TITLE
rpminspect warns about all (?) symlinks in packages

### ISSUE THREAD

**Issue by keszybz** [rpminspect/rpminspect#1295]
https://artifacts.dev.testing-farm.io/0f49e367-3397-4fd8-8118-ce5bac36e2fd/

> `INFO` symbolic link /usr/lib/environment.d/99-environment.conf became a dangling symbolic link in systemd on i686 `Not Waivable`

It is a symlink to /etc/enviornment which is provided by `setup.rpm` which is required by `filesystem.rpm`, which means that it's always available.

> `VERIFY` regular file /usr/lib/systemd/systemd-cryptsetup became a symbolic link (to ../../bin/systemd-cryptsetup) in systemd-udev on i686 `Anyone`
> `VERIFY` regular file /usr/lib/systemd/ukify became a symbolic link (to ../../bin/ukify) in systemd-ukify on noarch `Anyone`

Those are just regular relative symlinks to a file in the same package. Maybe it doesn't understand relative symlinks?

**Comment by dcantrell** [comment]
rpminspect should be able to see that absolute to relative symlinks still point to the same thing.  Still investigating, but this looks like a bug on my end.
