### ISSUE TITLE
Investigate autowaive allowances

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#13]
The goal is to find a balance between rigorous matching and broad matching for autowaive policies; if too broad, they could accidentally be triggered by an unintended user's rpminspect run.

References:
JIRA: 1004
BZ: 1351683

**Comment by dcantrell** [comment]
The plan I have right now is to start with file globbing that looks like this in the config file:

[ignores]
/usr/lib*/*.a
/usr/share/doc/flarfenblargle/README
/usr/bin/forkbomb

This section can exist in the system rpminspect.conf (/etc/rpminspect/rpminspect.conf), an rpminspect profile definition in /etc/rpminspect/profiles, or the .rpminspectrc file that lives where the program is run (i.e., the dist-git repo for the package).

This list will support glob(3) specifications for path names.  Anything listed here will be excluded from the peer matching code which will cause rpminspect to just ignore those files completely.

**Comment by dcantrell** [comment]
The idea here is captured with the plans for rpminspect.  Some of these things are already implemented:

- Runtime configuration file
- Runtime profiles to overlay the configuration
- Supplementary config file in current directory
- Regular expressions and globs to ignore categories of files
- Ability to skip tests when they do not apply to a build
