### ISSUE TITLE
get_rpmtag_str: Assertion `hdr != NULL' failed.

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#130]
Hello
We started to get the next error:
```
rpminspect -v python-requests-mock-1.3.0-1.el7ost python-requests-mock-1.3.0-2.el7ost
...
rpminspect: ../lib/rpm.c:118: get_rpmtag_str: Assertion `hdr != NULL' failed.
Aborted (core dumped)
```
* librpminspect-0.12-0.1.202004232014git.fc31.x86_64
* rpminspect-data-redhat-0.9-0.1.202004221252git.fc31.noarch
* rpminspect-0.12-0.1.202004232014git.fc31.x86_64

**Comment by dcantrell** [comment]
I've fixed this one.  A couple of things were happening.  The changelog inspection needed to make sure it was picking a binary package with both a before and after build.  The other problem was with the get_rpmtag_str() chain being a bit too fatal, which was unnecessary.  It can totally return NULL, which it does now.  Thanks for the report!
