### ISSUE TITLE
RFE: dangling symlink check

### ISSUE THREAD

**Issue by dcantrell** [rpminspect/rpminspect#133]
Similar to TEST_SYMLINK from rpmdiff.  Check for and report packaged dangling symlinks.  In general we should not do this in packages so it would be nice to catch it before releasing a package to the wild.

See https://bugzilla.redhat.com/show_bug.cgi?id=1830412 for more info.

**Comment by sgallagher** [comment]
In addition to dangling symlinks, can you also test for "Too many levels of symbolic links"? This is usually the result of having cycles in the symlinks.

**Comment by dcantrell** [comment]
Yes, that's an easy one to check for too.  I think (but am not sure) that the cycle check is also part of rpmdiff but have not verified in the code.

**Comment by dcantrell** [comment]
I've got the first iteration of this done and am working on test cases.
