### ISSUE TITLE
Please avoid split sentences 

### ISSUE THREAD

**Issue by rffontenelle** [rpminspect/rpminspect#1334]
This code snippet contains split sentences, and their parts (in appended with `strappend`) are shown for the translators without any explanation, which might confuse them and lead to incorrect translation. See [Never split sentences](https://wiki.gnome.org/TranslationProject/DevGuidelines/Never%20split%20sentences) at GNOME Wiki for a good reason to fix this.

Please consider to use the usual %s placeholder (preferable), or to add a comment explaining this on top of the strings to be extracted when generating the translation template.

https://github.com/rpminspect/rpminspect/blob/159e73af437b9a1831c59b3a127b22ece99009e0/lib/permissions.c#L82-L122

See in the [rpminspect.pot](https://github.com/rpminspect/rpminspect-l10n/blob/70eac5a27cadc0959a3ceaa329cb6eca2e7e461f/rpminspect.pot#L2698-L2741) how these source strings — in "msgid" line — looks for the translators.

**Comment by dcantrell** [comment]
Yep, this is definitely a mistake I made.  I know there are a lot of strings I need to fix in this case.  I have replaced some of these, but I know there are more to get to.
