### ISSUE TITLE
SPDX license check should work case insensitively for license names

### ISSUE THREAD

**Issue by yarda** [rpminspect/rpminspect#1335]
**Describe the bug**
SPDX license names are case insensitive according to the SPDX standard [1]. But the operators are case sensitive.

[1] https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/#d2-case-sensitivity

**To Reproduce**
E.g the following license is incorrectly rejected:
gpl-2.0-or-later

**Expected behavior**
License accepted.

**Environment:**
 - Fedora CI

Fedora infra original issue:
https://pagure.io/fedora-infrastructure/issue/11766

**Comment by lzaoral** [comment]
Also, while e.g. lowercase licence names are not accepted as noted by @yarda, lowercase operators are which is also incorrect as shown by the license of `ledmon-0.97-4.fc40`:

* `rpmlint` is green: https://artifacts.dev.testing-farm.io/5cb2bbb7-6491-49bd-b71c-72a85b011656/
* `licence-validate` fails:
```console
$ license-validate -v 'GPL-2.0-only and LGPL-2.1-only'
No terminal matches 'a' in the current parser context, at line 1 col 14

GPL-2.0-only and LGPL-2.1-only
             ^
Expected one of:
        * OR
        * AND

Not a valid license string
```

cc: @msuchy
