### ISSUE TITLE
free(): double free detected in tcache 2

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#134]
Hello!
I've got the next problem today:
```
$ rpminspect -v openshift-kuryr-4.3.13-202004130402.git.1622.ed0f539.el8 openshift-kuryr-4.3.10-202004030001.git.1622.6230cdd.el8
or 
$ rpminspect -v dotnet-2.1.513-2.el8 dotnet-2.1.514-1.el8_2
...
free(): double free detected in tcache 2
Aborted (core dumped)
```
* rpminspect-0.12-0.1.202005051745git.fc31.x86_64
* rpminspect-data-redhat-0.9-0.1.202005051747git.fc31.noarch
* librpminspect-0.12-0.1.202005051745git.fc31.x86_64

**Comment by dcantrell** [comment]
Thanks for the report.  Fixed.
