### ISSUE TITLE
Desktop file references icon but no subpackages contain it

### ISSUE THREAD

**Issue by ondrejholy** [rpminspect/rpminspect#1357]
**Describe the bug**
The `desktop` test fails for the `nautilus` builds with the `Desktop file /usr/share/applications/nautilus-autorun-software.desktop on x86_64 references icon application-x-executable but no subpackages contain application-x-executable` error. This should have been already fixed over the https://github.com/rpminspect/rpminspect/pull/525 request that was created as a reaction to my previous https://github.com/rpminspect/rpminspect/issues/422 report, but it is probably not...

**To Reproduce**
`$ rpminspect-redhat -T desktop nautilus-46.0-1.el10`

**Expected behavior**
The `desktop` test should pass as the `application-x-executable` icon is part of the standard system icons.

**Comment by dcantrell** [comment]
Makes sense.  This check just needs to understand the notation for standard system icons and not assume it's a filename.  I can do that.

**Comment by dcantrell** [comment]
rpminspect-data-fedora updated.  I've posted MRs for rpminspect-data-centos and rpminspect-data-redhat as well.
