### ISSUE TITLE
Invalid License Tag in perl-HTTP-Message-6.24-1.fc33.noarch: (GPL+ or Artistic) and CC0

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#138]
rpminspect in Fedora CI rejects a valid "(GPL+ or Artistic) and CC0" license. See [http://fedora-build-checks.apps.ci.centos.org/job/fedora-rpminspect/18695/artifact/package-tests/logs/rpminspect.json].

**Comment by dcantrell** [comment]
Good catch, thanks for the report.  I have a fix in progress for this.  I need to fix up issue #137 first and then I can finish up this one.

**Comment by dcantrell** [comment]
Fixed.
