### ISSUE TITLE
annocheck may try to fetch remote (!!!) debuginfo if DEBUGINFOD_URLS is set (it is set on Fedora). Unset it.

### ISSUE THREAD

**Issue by dvlasenk** [rpminspect/rpminspect#1399]
rpmbuild also was affected by this issue, they dealt with it this way:

commit b927c044b8809c4dd892f75737240a20c32c2b90
Author: Panu Matilainen <pmatilai@redhat.com>
Date:   Thu Feb 16 12:25:24 2023 +0200

    Disable debuginfod server lookups in build and dependency generator scripts

    With recent elfutils (0.182 or so) various seemingly innocuous tools
    such as `readelf` like to do network lookups for ELF symbol information.
    There's no circumstance where we'd want that to happen during rpmbuild,
    so disable these lookups during all spec build scriptlets and also
    dependency generator children.

diff --git a/build/rpmfc.c b/build/rpmfc.c
index 06205469c..a69e81f44 100644
--- a/build/rpmfc.c
+++ b/build/rpmfc.c
@@ -316,6 +316,7 @@ static int getOutputFrom(ARGV_t argv,
        rpmlog(RPMLOG_DEBUG, "\texecv(%s) pid %d\n",
                         argv[0], (unsigned)getpid());

+       unsetenv("DEBUGINFOD_URLS");
        if (buildRoot)
            setenv("RPM_BUILD_ROOT", buildRoot, 1);

**Comment by dcantrell** [comment]
I will make this change, but this feels like bad behavior on the part of debuginfod or annocheck or whatever is actually reading the environment variable and fetching source.  I saw your post on fedora-devel and agree.  This is a bad default.

**Comment by dcantrell** [comment]
(And I remember voting in favor of the change in FESCo, but did not realize that would mean fetching things live.  I was under the impression there were distinct fetching and serving operations with debuginfod.   I thought all debuginfo if served was local and to fill that cache there was a cron job or some other process to handle fetching things.)

**Comment by dvlasenk** [comment]
The comment is wrong: you don't even need to have debuginfod running (or installed), just having 
$DEBUGINFOD_URLS set enables this!

commit 961505113aa275b4fd1dd913b343b3133d122b2c (HEAD -> main, origin/main, origin/HEAD)
Author: David Cantrell <dcantrell@redhat.com>
Date:   Thu May 23 14:18:48 2024 -0400

    [fix] Unset DEBUGINFOD_URLS to prevent downloading debuginfo rpms

    If debuginfod is running and the environment where rpminspect runs has
   ^^^^^^^^^^^^^^^^^^^^ incorrect
    DEBUGINFOD_URLS set, then it will start trying to download debuginfo
    RPMs when you get to the annocheck inspection.

    Fixes: #1399

    Signed-off-by: David Cantrell <dcantrell@redhat.com>

diff --git a/lib/inspect_annocheck.c b/lib/inspect_annocheck.c
index 6157cb11..908e93cb 100644
--- a/lib/inspect_annocheck.c
+++ b/lib/inspect_annocheck.c
@@ -677,6 +677,11 @@ bool inspect_annocheck(struct rpminspect *ri)
     }
 #endif

+    /* Prevent debuginfod from fetching debuginfo packages. */
                         ^^^^^^^^^^ incorrect, it's /usr/lib64/libdebuginfod.so.1 what does it.
+    if (unsetenv("DEBUGINFOD_URLS") == -1) {
+        warn("*** unsetenv");
+    }
