### ISSUE TITLE
segfaults with rpminspect-0.12-0.1.202005121901git.fc31.x86_64

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#142]
Start to see this quite often in production:

```
$ rpm -qa rpminspect\*
rpminspect-0.12-0.1.202005121901git.fc31.x86_64
rpminspect-data-redhat-0.9-0.1.202005051747git.fc31.noarch

$ rpminspect -T ALL ansible-tower-3.6.3-1.el7at ansible-tower-3.7.0-0.git20200516.cdfc9e0.el7at; echo $?
Segmentation fault
139
```

Coredump should be available here: https://url.corp.redhat.com/rpminspect-coredump-2020-05-16

**Comment by dcantrell** [comment]
I hit this problem yesterday and could not complete the fix before I called it a day.  Yes, I am still working on it.

**Comment by dcantrell** [comment]
Fixed.
