### ISSUE TITLE
Garbage after "Suggested Remedy:" of a failed license test

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#1429]
I noticed a garbage after "Suggested Remedy:" text in this output:

~~~~
$ rpminspect -c /usr/share/rpminspect/fedora.yaml --release=fc42 --profile=rawhide -T license /tmp/perl-Types-UUID-0.004-24.fc42.noarch.rpm
[...]
license:
--------
1) Unapproved license in perl-Types-UUID-0.004-24.fc42.noarch: Artistic-1.0-Perl 

Result: BAD
Waiver Authorization: Not Waivable

Suggested Remedy: P^Q<C7>o*V
~~~~

Observed with rpminspect-2.0-1.fc42.x86_64 and fedora-license-data-1.55-1.fc42.noarch.

Please note that perl-Types-UUID-0.004-24.fc42.noarch.rpm has this license expression, valid according to license-validator:

~~~~
$ license-validate '(GPL-1.0-or-later OR Artistic-1.0-Perl) AND (GPL-1.0-or-later OR Artistic-1.0-Perl OR CC-BY-SA-2.0-UK) AND LicenseRef-Fedora-Public-Domain'
$ echo $?
0
~~~~

First I recalled  issue #855 that was worked around in fedora-license-data. This time I decided to fix the rpminspect failure by spelling the license differently. I quoted the Perl subexpression into parentheses:

~~~~
(GPL-1.0-or-later OR Artistic-1.0-Perl) AND ((GPL-1.0-or-later OR Artistic-1.0-Perl) OR CC-BY-SA-2.0-UK) AND LicenseRef-Fedora-Public-Domain
~~~~

That makes rpmsinpect happy and you can see it in perl-Types-UUID-0.004-25.fc42 build.

I created this issue to report the garbage after "Suggested Remedy:" text in case of the failure. It's a sign of a use of an uninitialized memory.

**Comment by dcantrell** [comment]
Yeah, this is from the vendor-specific remedy strings I added.  Those should default correctly, but I guess I missed one.  Fix coming.

**Comment by dcantrell** [comment]
Well, I was wrong.  I can't reproduce this locally and it seems to be working fine with the latest fedora-license-data package as well as the latest rpminspect-data-fedora in Copr.

I'm going to cut a new release of rpminspect-data-fedora today.  The license data package separately updates.

**Comment by dcantrell** [comment]
I release rpminspect-data-fedora-1.13 so the data package in Fedora matches the latest rpminspect build.

https://github.com/rpminspect/rpminspect-data-fedora/releases/tag/v1.13
