### ISSUE TITLE
rpminspect seems to mistakenly scan U+2202B (some Chinese character) as U+202B RIGHT-TO-LEFT EMBEDDING

### ISSUE THREAD

**Issue by mike-fabian** [rpminspect/rpminspect#1433]
In the case of vi-nomtelext.mim in the m17n-db package, rpminspect reports:

```
A forbidden code point, 0x202B, was found in the m17n-db-1.8.5/MIM/vi-nomtelex.mim source file on line 117 at column 17.
```

line 117 contains:

```
("baang" ("氷冰挷𢲔𢀫搬"))
```

The Chinese character 𢀫 U+2202B is **not** U+202B RIGHT-TO-LEFT EMBEDDING. So rpminspect apparently scans wrong, seems to use only the lower 16 bit.

This is the line in the upstream repo:

https://git.savannah.nongnu.org/cgit/m17n/m17n-db.git/tree/MIM/vi-nomtelex.mim#n130

**Comment by mike-fabian** [comment]
Similar problem in the ibus-table-chinese package. It contains the file cangjie5.txt: https://github.com/mike-fabian/ibus-table-chinese/blob/main/tables/cangjie/cangjie5.txt

which contains stuff like

```
sklb	𢁨	1000
```

The Chinese character in the line is U+22068 but rpminspect reports:

```
A forbidden code point, 0x2068, was found in the ibus-table-chinese-1.8.12/tables/cangjie/cangjie5.txt source file on line 51377 at column 5. This source file is used by ibus-table-chinese.spec.
```

**Comment by dcantrell** [comment]
This is another one where the vendor policy package for rpminspect needs to know to skip this file in the unicode check.  Submit PRs to rpminspect-data-redhat and rpminspect-data-centos.

I also recommend submitting PRs to rpminspect-data-fedora so the check works as expected there too:  https://github.com/rpminspect/rpminspect-data-fedora

**Comment by mike-fabian** [comment]
@dcantrell Is this really only a data-package-update problem? Because these files don't actually contain  U+202B or U+2068, they contain the completely unrelated characters U+2202B and U+22068. So isn't this an error in parsing?
