### ISSUE TITLE
rpminspect needs rebuilding against libclamav.so.12

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#1442]
New clamav-lib-1.4.1-1.fc42 changes soname from libclamav.so.11 to libclamav.so.12. librpminspect-2.1-0.1.202410161454gitf11af6a9.fc42.x86_64 from a Copr repository now has a broken dependency on the libclamav library.

**Comment by dcantrell** [comment]
OK, done in both rawhide and in Copr.  Copr had far more problems.  Looks like I've got some work to do to start building EPEL-10 packages.
