### ISSUE TITLE
rpminspect fails after SPDX Phase 4 change (BSD -> LicenseRef-Callaway-BSD)

### ISSUE THREAD

**Issue by AloisMahdal** [rpminspect/rpminspect#1449]
**Describe the bug**

This package which maintain was [auto-converted to use SPDX license format][1] with the comment that "review is highly recommended".  Now [rpminspect fails][2], with failure described as

    Unapproved license in ydiff-1.4.1-1.fc42.src: LicenseRef-Callaway-BSD

I don't know whether this is just missing identifier or if the [license text itself][3] is problematic.

  [1]: https://src.fedoraproject.org/rpms/ydiff/c/1a0ae475efdef0b2f7dfb7cabe587af11ebee3d3?branch=rawhide
  [2]: https://bodhi.fedoraproject.org/updates/FEDORA-2024-e62b13b2f2
  [3]: https://github.com/ymattw/ydiff/blob/master/LICENSE

**To Reproduce**

rpminspect ran as part of TMT plan in Bodhi; this looks like the relevant command:

    /usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml --workdir /var/ARTIFACTS/work-rpminspectiflh9d2z/rpminspect/discover/default-0/tests/workdir/ --format=json --output=/var/ARTIFACTS/work-rpminspectiflh9d2z/rpminspect/execute/data/guest/default-0/rpminspect-1/data/result.json --verbose --release=fc42 --profile=rawhide ydiff-1.3-3.fc41 ydiff-1.4.1-1.fc42

**Expected behavior**

Naively, I expect the test to succeed.. :)

I don't know, though, whether this is a problem with the license itself or just rpminspect not recognizing it.

Or the license is in the process of being legally approved somewhere; in that case I would like to know how to track that.

**Environment:**

rpminspect ran as part of TMT plan: https://artifacts.dev.testing-farm.io/deeab9fc-0517-4826-b83e-927486b91ff6/#artifacts-/rpminspect

Diagnostics/versions:

    rpminspect version 2.1
    zlib version 1.3.1.zlib-ng
    libmagic version 545
    libclamav version 1.4.1
    librpm version 4.20.0
    libxml version 21208
    json-c version 0.17
    libcurl version 8.10.1 (OpenSSL/3.2.2 zlib/1.3.1.zlib-ng brotli/1.1.0 libidn2/2.3.7 libpsl/0.21.5 libssh/0.11.1/openssl/zlib nghttp2/1.63.0 OpenLDAP/2.6.8)
    libarchive version 3.7.6 (zlib/1.3.1.zlib-ng liblzma/5.6.2 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6)
    libyaml version 0.2.5
    OpenSSL version 3.2.2 4 Jun 2024
    xmlrpc-c version 1.59.2
    msgunfmt (GNU gettext-tools) 0.22.5
    annocheck version 12.70.
    abidiff version 2.5.0
    kmidiff version 2.5.0
    udevadm version 256

**Comment by dcantrell** [comment]
Well I checked fedora-license-data and LicenseRef-Callaway-BSD is not in there.  Please open an issue here:

https://gitlab.com/fedora/legal/fedora-license-data

**Comment by AloisMahdal** [comment]
I'd be happy to open the ticket but I need help since I don't quite understand the nature of the problem (and don't want to open a ticket that is unclaar).  I'm trying to file the ticket using license-review template.

From My POV, this ID of `LicenseRef-Callaway-BSD` is what the auto-converting scripting came up with but I'm not sure whether that's simply a search-replace operation (the original text was just `BSD`) or it's more sophisticated such as some heuristics based on the actual text.

So is this about a completely new license which needs to be added to SPDX?   I can't see anything containing "callaway" in the license list at https://spdx.org/licenses/.

**Comment by AloisMahdal** [comment]
Thanks for your reply.  Indeed it helped me understand the issue.  Hope you are enjoying your offline time.  This is not a pressing matter.

FTR, I did some more research and ended up [opening a ticket][1] with the ydiff's license, since the text had minor differences from some of the accepted licenses and I was not sure if they could matter.  (I'm not a lawyer and I'm always trying to be careful around legal stuff.)

  [1]: https://gitlab.com/fedora/legal/fedora-license-data/-/issues/710
