### ISSUE TITLE
rpminspect.analysis.symlinks  - dangling symlinks are not allowed

### ISSUE THREAD

**Issue by drckeefe** [rpminspect/rpminspect#145]
rpminspect find dangling symlinks

                "outcome": "NEEDS_INSPECTION",
                "ref_url": "",
                "testcase": {
                    "name": "dist.rpminspect.analysis.symlinks",
                    "ref_url": "",
                    "test_outputs": [
                        {
                            "message": "symbolic link /usr/lib/debug/.build-id/<directory> is a dangling symbolic link in <package>-debuginfo on i686",
                            "remedy": "Make sure symlinks point to a valid destination in one of the subpackages of the build; dangling symlinks are not allowed.  If you are comparing builds and have a non-symlink turn in to a symlink, ensure this is deliberate.  NOTE:  You cannot turn a directory in to a symlink due to RPM limitations.",
                            "result": "NEEDS_INSPECTION",
                            "waiver_authorization": "Anyone"

**Comment by gicmo** [comment]
I got something similar with a recent [osbuild](https://github.com/osbuild/osbuild/) build:

```
"outcome": "NEEDS_INSPECTION",
                "ref_url": "",
                "testcase": {
                    "name": "dist.rpminspect.analysis.symlinks",
                    "ref_url": "",
                    "test_outputs": [
                        {
                            "message": "symbolic link /usr/lib/osbuild/schemas is a dangling symbolic link in osbuild on noarch",
                            "remedy": "Make sure symlinks point to a valid destination in one of the subpackages of the build; dangling symlinks are not allowed.  If you are comparing builds and have a non-symlink turn in to a symlink, ensure this is deliberate.  NOTE:  You cannot turn a directory in to a symlink due to RPM limitations.",
                            "result": "NEEDS_INSPECTION",
                            "waiver_authorization": "Anyone"
                        }
                    ]
                }
```

The symlink identified is actually provided by the inside the same package. Here is relevant section from the [spec](https://github.com/osbuild/osbuild/blob/master/osbuild.spec) file:
```

# schemata
mkdir -p %{buildroot}%{_datadir}/osbuild/schemas
install -p -m 0755 $(find schemas/*.json) %{buildroot}%{_datadir}/osbuild/schemas
ln -s %{_datadir}/osbuild/schemas %{buildroot}%{pkgdir}/schemas
```
Which should be according to the [Fedora Packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/#_absolute_symlinks) and also ends up exactly as intended as:
```
lrwxrwxrwx.  1 root root   26 May 21 10:36 schemas -> /usr/share/osbuild/schemas/
```

**Comment by dcantrell** [comment]
Can you tell me what NVRs were used in this rpminspect run?

**Comment by drckeefe** [comment]
@dcantrell 
I have this info:
rpminspect_analysis/32639//"
    },
    "thread_id": "79dfe7381c2a-1",
    "type": "rpminspect-analysis",
    "version": "0.1.0"
}

**Comment by dcantrell** [comment]
Sorry, I meant what build from koji was rpminspect running on?  Like what build did you submit to koji?

**Comment by drckeefe** [comment]
@dcantrell 
I tried to IM some questions and logs to you.  Let me know if you didn't receive them.

**Comment by drckeefe** [comment]
NVR of the package in brew was stratisd-2.0.0-6.el8

**Comment by dcantrell** [comment]
I am modifying librpminspect to report dangling symlinks as INFO for the moment.  I need to figure out a way that it can validate symlinks with link destinations provided by packages outside of the build.  I am leaving this issue open until I can resolve that.

**Comment by dcantrell** [comment]
I've tried reproducing the original issue reported here with both current and old builds and everything reports as 'pass'.  If there is more here and someone is encountering problems, please reopen this issue with new details.  But I am going to consider it done at this point.
