### ISSUE TITLE
SPDX checker warns about mixed case when there isn't a mixed case

### ISSUE THREAD

**Issue by troycurtisjr** [rpminspect/rpminspect#1454]
**Describe the bug**
The SPDX checker warns against using mixed case with boolean expressions in an SPDX identifier even when there is no mixed case. I think it is perhaps getting tripped up on the `-or` present in the license text itself in my example. The test farm failure: https://artifacts.dev.testing-farm.io/2eceda7e-9684-43ef-83a3-04955da926a3/

The error:
> SPDX license expressions in use in rarian-0.8.6-1.fc42.src, but an invalid boolean was found: AND; when using SPDX expression the booleans must be in all lowercase or all uppercase (not mixed case).

The license:
> License: LGPL-2.1-or-later AND Zlib

**To Reproduce**
```
rpminspect version 2.1
zlib version 1.3.1.zlib-ng
libmagic version 545
libclamav version 1.4.1
librpm version 4.20.0
libxml version 21208
json-c version 0.18
libcurl version 8.10.1 (OpenSSL/3.2.2 zlib/1.3.1.zlib-ng brotli/1.1.0 libidn2/2.3.7 libpsl/0.21.5 libssh/0.11.1/openssl/zlib nghttp2/1.64.0 OpenLDAP/2.6.8)
libarchive version 3.7.7 (zlib/1.3.1.zlib-ng liblzma/5.6.3 bz2lib/1.0.8 liblz4/1.10.0 libzstd/1.5.6)
libyaml version 0.2.5
OpenSSL version 3.2.2 4 Jun 2024
xmlrpc-c version 1.59.2
msgunfmt (GNU gettext-tools) 0.22.5
annocheck version 12.77.
abidiff version 2.6.0
kmidiff version 2.6.0
udevadm version 257

Space required to download artifacts: 3806454 bytes (4 MiB)
Space required to unpack artifacts: 12621508 bytes (12 MiB)
```

CLI
```
/usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml --workdir /var/ARTIFACTS/work-rpminspect4jt8o5t9/rpminspect/discover/default-0/tests/workdir/ --format=json --output=/var/ARTIFACTS/work-rpminspect4jt8o5t9/rpminspect/execute/data/guest/default-0/rpminspect-1/data/result.json --verbose --release=fc42 --profile=rawhide rarian-0.8.5-4.fc41 rarian-0.8.6-1.fc42
```

**Expected behavior**
Since all upper case is allowed for the boolean expression, I expect this license expression to not produce an error.

**Environment:**
 This is on the Fedora testing-farm instance. I haven't been able to determine the exact version or architecture it is running. Presumably the latest stable Fedora Linux 41?

**Comment by ppisar** [comment]
Another instance is bzip3-1.5.1-1.fc42 <https://artifacts.dev.testing-farm.io/ca7b28c7-d696-4efc-9811-ca483bfe6410/>.
