### ISSUE TITLE
False positive "removed from" warning

### ISSUE THREAD

**Issue by alexey-tikhonov** [rpminspect/rpminspect#155]
Hi,

`rpminspect` reports warning: `/usr/share/man/man8/pam_sss.8.gz removed from *`
(new: `sssd-2.3.0-1.el8`; old: `sssd-2.2.3-20.el8`)

This is false positive as corresponding RPMs in this build (`sssd-client-2.3.0-1.el8.*.rpm`) contain this file.

**Comment by dcantrell** [comment]
Thanks for the report.  I need to two things to fix this up.  The first is filter the results found by the removedfiles inspection.  The second is to commit the movedfiles inspection which report as INFO when files move between subpackages.  Just noting here for my own record.

**Comment by dcantrell** [comment]
I have been restructuring how addedfiles, removedfiles, and movedfiles work.  I have fixed some errors in addedfiles and fixed reporting there.  Now working on removedfiles and movedfiles.  All three of these inspections are inter-related, so I have to do them as one big change.  Just wanted to give a heads up.

**Comment by dcantrell** [comment]
This is now working as expected in the master branch.  Likely rpminspect 1.1, but I haven't tried that one.  rpminspect detects that the file moves between subpackages and does not report it as a removal.
