### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#156]
Hello
Another segfault
```
rpminspect -v ansible-tower-3.7.1-1.el8at
...
Running license inspection...        FAIL
Running emptyrpm inspection...       FAIL
Running metadata inspection...       pass
Running manpage inspection...        pass
Running xml inspection...            FAIL
Running elf inspection...            pass
Running desktop inspection...        pass
Segmentation fault (core dumped)
```
* rpminspect-1.0-0.1.202006161650git.fc31.x86_64
* librpminspect-1.0-0.1.202006161650git.fc31.x86_64
* rpminspect-data-redhat-1.0-0.1.202005291509git.fc31.noarch

**Comment by dcantrell** [comment]
I hit this problem yesterday as well.  I've restricted the macro gathering more as a result.  Fix is in commit 9d506f5c683a21168d99c248237d59c2555757db.  Just ran "rpminspect -v ansible-tower-3.7.1-1.el8at" using latest master branch build and it doesn't seg fault.
