### ISSUE TITLE
 get_rpm_header_arch: Assertion `h != NULL' failed

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#161]
Hi David!
Caught a new bug in the latest version:
```
$ rpminspect-redhat -v git-2.18.4-2.el8_2 git-2.27.0-1.el8
...
rpminspect: ../lib/rpm.c:167: get_rpm_header_arch: Assertion `h != NULL' failed.
/usr/bin/rpminspect-redhat: line 2:   102 Aborted                 (core dumped) /usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml $*
```
* fedora 31
* rpminspect-1.1-0.1.202007062116git.fc31.x86_64
* librpminspect-1.1-0.1.202007062116git.fc31.x86_64
* rpminspect-data-redhat-1.1-0.1.202007062056git.fc31.noarch

**Comment by dcantrell** [comment]
Fixed.  And now I'm working on fixing the Copr builds which I seem to have broken.

**Comment by dcantrell** [comment]
Builds fixed in Copr again.  Hope you don't need F30 builds because I turned those off.
