### ISSUE TITLE
Validate disappearing provides with epoch when adding an actual epoch

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#174]
You'll have to pull the BZ up on this one and add some context as it's a bit over my head :) But I think the subject covers it.

Reference: BZ#1486954

**Comment by dcantrell** [comment]
This is handled in rpmdiff's TEST_REQUIRES and has yet to be implemented in rpminspect.

**Comment by dcantrell** [comment]
This is done as of the rpmdeps inspection.
