### ISSUE TITLE
Handle "Requires: rpmlib(PartialHardlinkSets)" on builds

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#175]
On the previous software we used for build comparisons, it would throw errors like this:
Requires: rpmlib(PartialHardlinkSets) <= 4.0.4-1 appearing on noarch

We need to handle these accordingly; more context in the BZ.

Reference: BZ#1572791

**Comment by dcantrell** [comment]
This does not happen with the rpmdeps inspection.
