### ISSUE TITLE
RFE: Improve test run messages "Specfile Checks"

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#178]
With whatever spec file checks we are conducting, the actions/results of this inspection should be clear actions for the developer to act on/fix.

Reference: BZ#1704776

**Comment by dcantrell** [comment]
The specfile checks from rpmdiff have been split out to separate inspections in rpminspect.  The reporting messages are meant to be more clear as well as providing possible remedy messages for how to fix something that reports as VERIFY or BAD.
