### ISSUE TITLE
Changed permissions from 0755 to 0755 on noarch

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#181]
Hi David,

In this job result, I see a bunch a lines such as:

'Message: /usr/bin/marshalparser changed permissions from 0755 to 0755 on noarch'

https://fedora.softwarefactory-project.io/logs/3/3/6b1996f153b5bd4ac895f583c567c67d29e7efba/check/rpm-rpminspect/309542e/rpminspect.html

Is it expected ?
Thanks a lot for your response.

**Comment by dcantrell** [comment]
That definitely looks like a bug.  Let me dig in to this.

**Comment by dcantrell** [comment]
I can't see what the rpminspect command line was that was run.  The first result in rpminspect called 'rpminspect' is the full command line used to invoke the program.  I added that to help with debugging, but the URL above suppresses the information.

What builds did you compare, or what was the command line used?

Thanks.

**Comment by dcantrell** [comment]
What, I backed up the URL a level and found result.json.  The first problem I notice is that you are passing the same two builds to rpminspect to get a comparison run:

```
/usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml -k -t BAD -a x86_64,noarch,src -o /root/zuul-output/logs/result.json -F json /var/tmp/rpminspect/marshalparser-0.2.0-1.fc33 /var/tmp/rpminspect/marshalparser-0.2.0-1.fc33
```

While that shouldn't matter, it's sort of pointless.  Comparing builds is intended for 2 different builds, but I think that if you run it this way it shouldn't report information like you received.  Looking in to that now.

(Side note, if you have the latest builds of rpminspect and rpminspect-data-fedora from Copr, then you can run 'rpminspect-fedora' and not have to pass the -c option to specify the Fedora config file.  Also, the way you are passing the builds implies you previously downloaded them.  rpminspect can do this for you, so you can drop the /var/tmp/rpminspect prefix.  It looks like you're downloading builds manually and then copying them in to /var/tmp/rpminspect to then run rpminspect.  You can skip doing all that and just give rpminspec the build NVRs and it will download them.)

**Comment by dcantrell** [comment]
Wow, that was easy.  Stupid me.  I computed the XOR of the modes but then excluded it from the if block.  Ooops.  Fix going in today:

```
diff --git a/lib/inspect_permissions.c b/lib/inspect_permissions.c
index 03fcb3c..b63af32 100644
--- a/lib/inspect_permissions.c
+++ b/lib/inspect_permissions.c
@@ -68,7 +68,7 @@ static bool permissions_driver(struct rpminspect *ri, rpmfile_entry_t *file)
     allowed = match_fileinfo_mode(ri, file, HEADER_PERMISSIONS, NULL);
 
     /* if setuid/setgid or new mode is more open */
-    if (file->peer_file && !allowed) {
+    if (mode_diff && file->peer_file && !allowed) {
         if (!(before_mode & (S_ISUID|S_ISGID)) && (after_mode & (S_ISUID|S_ISGID))) {
             params.severity = RESULT_BAD;
             what = _("changed setuid/setgid");
```

**Comment by morucci** [comment]
Hi David,

Thanks for this quick investigation and fix.

Yes the job is run on a distgit PR that does not bump the NVR, the spec file is not modified. I could probably detect that and skip the run of the rpminspect job but that looks too advanced at the moment.

I'm using the copr version and recently did the change to use rpminspect-fedora command:
https://pagure.io/fedora-zuul-jobs/pull-request/66#request_diff
https://pagure.io/zuul-distro-jobs/pull-request/68#request_diff

We see elsewhere in the artifacts related to that job that the command is correct: https://fedora.softwarefactory-project.io/zuul/build/309542eeb465437fb7a2d39172af874d/console#2/0/28/container
Maybe the result.json does not render the right command ?

Yes since rpminspect is able to download from koji I should do the change but this is still in my todo list ;)
