### ISSUE TITLE
rpminspect complains about unapplied patches when a patch is %include'd

### ISSUE THREAD

**Issue by dodjiseketeli** [rpminspect/rpminspect#182]
In the GDB package, we use git for patch management.

We keep a list of patches in two files, _gdb.spec.[pP]atch.include. These are %included from gdb.spec. Originally, they were Source:, but rpminspect complained about that.

After talking to David Cantrell, it was decided a better approach would be to use Patch for this, but this new warning appeared.

So we are filing this bug to teach rpminspect about this particular use case.

**Comment by dcantrell** [comment]
Can you give me an rpminspect command line you ran to see this error?  Or a build of gdb in koji that demonstrates the problem?

**Comment by dodjiseketeli** [comment]
Hello David,
So apparently, after updating rpminspect to a more recent version, the problem seems to have "vanished".  Sorry for the noise.  I am closing this issue.
