### ISSUE TITLE
[RFE] Support downloading packages

### ISSUE THREAD

**Issue by voxik** [rpminspect/rpminspect#190]
It would be nice if rpminspec supported download packages, e.g. this would work:

~~~
$ rpminspect https://kojipkgs.fedoraproject.org//packages/rubygem-puma/4.3.3/1.fc33/x86_64/rubygem-puma-4.3.3-1.fc33.x86_64.rpm https://kojipkgs.fedoraproject.org//packages/rubygem-puma/4.3.6/1.fc34/x86_64/rubygem-puma-4.3.6-1.fc34.x86_64.rpm
*** unable to find after build: https://kojipkgs.fedoraproject.org//packages/rubygem-puma/4.3.6/1.fc34/x86_64/rubygem-puma-4.3.6-1.fc34.x86_64.rpm
*** Failed to gather specified builds.
~~~

Of course even more common use case would be:

~~~
$ rpminspect https://kojipkgs.fedoraproject.org//packages/rubygem-puma/4.3.3/1.fc33/x86_64/rubygem-puma-4.3.3-1.fc33.x86_64.rpm rubygem-puma-4.3.6-1.fc34.x86_64.rpm
~~~

i.e. comparing previous build available in build system with locally updated package.

**Comment by dcantrell** [comment]
I like that idea.  I'll slate this one for the 1.2 release.  At the moment I am finalizing things for 1.1 so I don't want to add anything new there.

**Comment by dcantrell** [comment]
I have a patch for this for the master branch now.  You can specify single RPMs as a URL and rpminspect will download them and perform the rpminspect run.  Thanks for the suggestion.
