### ISSUE TITLE
Using satellite profile hangs rpminspect

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#194]
```
# rpm -qa rpminspect\*
rpminspect-1.2-0.1.202009152054git.fc31.x86_64
rpminspect-data-redhat-1.1-0.1.202009091815git.fc31.noarch
```

We are seeing hanging builds in staging when using `satellite` profile:

```
# rpminspect-redhat -v -w /tmp/artifacts -o /tmp/rpminspect-results.txt -F json -T ALL  tfm-rubygem-katello-3.14.0.27-1.el7sat 31338604
Downloading http://download.eng.bos.redhat.com/brewroot/work/tasks/8627/31338627/tfm-rubygem-katello-3.16.0.8-1.el7sat.src.rpm...
Downloading http://download.eng.bos.redhat.com/brewroot/work/tasks/8627/31338627/tfm-rubygem-katello-assets-3.16.0.8-1.el7sat.noarch.rpm...
Downloading http://download.eng.bos.redhat.com/brewroot/work/tasks/8627/31338627/tfm-rubygem-katello-3.16.0.8-1.el7sat.noarch.rpm...
^C
```

```
# rpminspect-redhat -v -w /tmp/artifacts -o /tmp/rpminspect-results.txt -F json -T ALL -p satellite tfm-rubygem-katello-3.14.0.27-1.el7sat 31338604
<HANGS>
```

Cannot provide more details right now, any idea what it could be?

**Comment by thrix** [comment]
`scl` profile works well, so must be related only to satellite profile

**Comment by dcantrell** [comment]
I have tried to recreate this locally, but I can't.  Can you run it with debugging mode (-d) and capture the output using 2>&1 and send that file?

**Comment by thrix** [comment]
yep, on it

**Comment by thrix** [comment]
hmm even with `-d` I see no output. Let me try strace .... we run rpminspect in a container, I guess it will have to do something with it ...

**Comment by thrix** [comment]
Adding strace from the host machine, I run the command:

```
sudo strace docker run -it --entrypoint=bash docker-registry.upshift.redhat.com/testing-farm/baseosci-citool-bundle-full-devel:latest rpminspect-redhat -d -v -w /tmp/artifacts -o /tmp/rpminspect-results.txt -F json -T ALL -p satellite tfm-rubygem-katello-3.14.0.27-1.el7sat 31338604
```

[rpminspect-strace.txt](https://github.com/rpminspect/rpminspect/files/5237192/rpminspect-strace.txt)

**Comment by dcantrell** [comment]
This looks like a failure on the docker side of things, but I don't really no.  All of the strace output to me looks like docker is failing to set up the environment properly and it's waiting using epoll() over and over.

**Comment by dcantrell** [comment]
I shortened the command to

```
sudo docker run -it --entrypoint=bash docker-registry.upshift.redhat.com/testing-farm/baseosci-citool-bundle-full-devel:latest
```

And got this:

```
Digest: sha256:488433f97e2797c2baf3765e07661ba9e3a79604d8d649e127b6759c03af1eee
Status: Downloaded newer image for docker-registry.upshift.redhat.com/testing-farm/baseosci-citool-bundle-full-devel:latest
docker: Error response from daemon: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown.
ERRO[0035] error waiting for container: context canceled 
```

I have no idea what I'm doing.

**Comment by dcantrell** [comment]
One last idea I have is what happens if you say '--profile=satellite' instead of '-p satellite' on the rpminspect options list?  Long shot, but I've seen programs mess up option parsing before.

**Comment by jimbair** [comment]
@thrix I think I have reproduced this on my local Fedora system :) I'm working with David to see if we can find out what's going on. For reference, the same thing happens with --profile. I see 100% CPU used and no output  from the command.

**Comment by dcantrell** [comment]
Figured it out.  YAML prohibits '%' in token names and that was causing libyaml to loop indefinitely.  I would expect people more familiar with YAML than me to be able to spot use of a perfectly good character that YAML has categorically decided to exclude.  :)

**Comment by thrix** [comment]
@dcantrell :rocket:

**Comment by thrix** [comment]
> I shortened the command to
> 
> ```
> sudo docker run -it --entrypoint=bash docker-registry.upshift.redhat.com/testing-farm/baseosci-citool-bundle-full-devel:latest
> ```
> 
> And got this:
> 
> ```
> Digest: sha256:488433f97e2797c2baf3765e07661ba9e3a79604d8d649e127b6759c03af1eee
> Status: Downloaded newer image for docker-registry.upshift.redhat.com/testing-farm/baseosci-citool-bundle-full-devel:latest
> docker: Error response from daemon: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown.
> ERRO[0035] error waiting for container: context canceled 
> ```
> 
> I have no idea what I'm doing.

BTW, to make docker running I believe still this guide applies ... https://linuxconfig.org/how-to-install-docker-on-fedora-31

But I guess if you reproduced it, it means that you found a way to run it ..

Also feel free to just `s/docker/podman/` next time, which just works in Fedora
