### ISSUE TITLE
not existing scratch build caues rpminspect to segfault

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#198]
found this by accident while running some testing:

```
$ rpminspect-redhat -F json -T ALL -p satellite tfm-rubygem-katello-3.14.0.27-1.el7sat 31338604
*** Fopen() failed for /var/tmp/rpminspect/scratch-31338604.9Ek96d/after/src/tfm-rubygem-katello-3.16.0.8-1.el7sat.src.rpm: No such file or directory
*** Fopen() failed for /var/tmp/rpminspect/scratch-31338604.9Ek96d/after/noarch/tfm-rubygem-katello-assets-3.16.0.8-1.el7sat.noarch.rpm: No such file or directory
*** Fopen() failed for /var/tmp/rpminspect/scratch-31338604.9Ek96d/after/noarch/tfm-rubygem-katello-3.16.0.8-1.el7sat.noarch.rpm: No such file or directory
*** Fopen() failed for /var/tmp/rpminspect/scratch-31338604.9Ek96d/after/noarch/tfm-rubygem-katello-doc-3.16.0.8-1.el7sat.noarch.rpm: No such file or directory
rpminspect: ../src/rpminspect.c:103: get_product_release: Assertion `after != NULL' failed.
/usr/bin/rpminspect-redhat: line 2:  2883 Aborted                 (core dumped) /usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml $*
```

It should traceback ideally, but write an error ...

**Comment by dcantrell** [comment]
I have run in to similar problems like this with scratch builds.  There are a number of problems.  Sometimes a scratch build does not have all of its files published at the download URL despite Koji reporting those files existing.  And of course there's the problem with scratch builds eventually being removed.

Even with those limitations, rpminspect should be able to handle the condition more gracefully.  There's not a lot I can do except trap for it and then error out.   I'll work on that.

**Comment by dcantrell** [comment]
I think I fixed this with my commit for #190 

Can you try again with a current build?  What should happen in cases like this is rpminspect will just error out and tell you the before or after RPM is invalid.  This can happen for a number of reasons, but at least this way it doesn't crash.

**Comment by dcantrell** [comment]
@thrix any update here?

**Comment by ukulekek** [comment]
I confirm segfault is gone with the latest build and a clean error appeared. I believe the issue can be closed
```
$ rpminspect-redhat -F json -T ALL -p satellite tfm-rubygem-katello-3.14.0.27-1.el7sat 31338604
rpminspect: Fopen() failed for /var/tmp/rpminspect/scratch-31338604.wWzrHE/after/src/tfm-rubygem-katello-3.16.0.8-1.el7sat.src.rpm: No such file or directory
rpminspect: Fopen() failed for /var/tmp/rpminspect/scratch-31338604.wWzrHE/after/noarch/tfm-rubygem-katello-assets-3.16.0.8-1.el7sat.noarch.rpm: No such file or directory
rpminspect: Fopen() failed for /var/tmp/rpminspect/scratch-31338604.wWzrHE/after/noarch/tfm-rubygem-katello-3.16.0.8-1.el7sat.noarch.rpm: No such file or directory
rpminspect: Fopen() failed for /var/tmp/rpminspect/scratch-31338604.wWzrHE/after/noarch/tfm-rubygem-katello-doc-3.16.0.8-1.el7sat.noarch.rpm: No such file or directory
rpminspect: invalid after RPM: No such file or directory
```

**Comment by dcantrell** [comment]
Thanks for the update, I will close this bug.

**Comment by thrix** [comment]
thanks for testing @ukulekek ! and sorry for not getting back to this earlier @dcantrell
