### ISSUE TITLE
RFE: Richer "allowed" expressions

### ISSUE THREAD

**Issue by funnelfiasco** [rpminspect/rpminspect#220]
For ecosystems where there are multiple projects/products, it would be helpful to have a single license json file that can used to express approval for all of them, potentially independently.

The logic is essentially: `approved && ifThenElse(approved_<id> is defined, approved_<id>, True)`

For example, the FunnelFiascorp vendor data might have a `licenses/funnelfiascorp.json` file that contains

````
  "Some License": {
    "approved": "yes",
    "spdx_abbrev": "some",
    "spdx_name": "Some license",
    "url": "http://example.com/some-license.txt"
  },
  "Another License": {
    "approved": "yes",
    "approved_bar": "no",
    "spdx_abbrev": "Another",
    "spdx_name": "Another license",
    "url": "http://example.com/this-too.txt"
  },
````

Both the Some License and the Another License are okay for the _foo_ project. For the _bar_ project, only the Some License is acceptable. So if rpminspect, using this vendor data, is told the project is "foo", then it works as currently. If the project is "bar", then it flags anything using the Another License.

The idea is that certain projects can override the default "yes" approval with a "no" approval. It may also be worth considering a situation where the default is no, but the per-project approval can override that. That makes the logic a little more complex and I'm not sure it's going to be a common enough use case. The workaround is to set the default yes and then set no on all projects except the one where it is allowed.

**Comment by dcantrell** [comment]
Clearing the target release for now.  More work needs to happen on this one and it's currently not high priority.

**Comment by dcantrell** [comment]
So given the SPDX change proposal that has gone through Fedora and the migration to SPDX expressions and a new workflow around the fedora-license-data project, I am going to close this RFE.
