### ISSUE TITLE
rpminspect stuck after kmidiff inspection in comparison mode

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#221]
Hello,

rpminspect stucks after kmidiff inspection. The inspections took 1.5 hours and then I cancelled it
```
$ rpminspect-redhat -v scap-security-guide-0.1.48-7.el8 scap-security-guide-0.1.48-9.el8_2
...
Running types inspection...          pass
Running abidiff inspection...        pass
Running kmidiff inspection...        pass
```
* rpminspect-1.2-0.1.202010081406git.fc31.x86_64
* rpminspect-data-redhat-1.2-0.1.202010072009git.fc31.noarch
* librpminspect-1.2-0.1.202010081406git.fc31.x86_64

**Comment by dcantrell** [comment]
Wow, 1.5 hours!  OK, let me take a look at this.

**Comment by dcantrell** [comment]
I have been able to reproduce this one locally.  It is happening in the config and doc inspections.  Getting back to work on it.

**Comment by thrix** [comment]
Yep we still see it, and it is causing delays in testing quite heavily today (more builds from this package took all workers)

**Comment by dcantrell** [comment]
OK, making progress here.  There are a couple of problems I am working on.  The scap-security-guide package is a good reproducer to use for this problem.  Here is a summary of where I currently am:

- The config inspection runs 'diff -q' to see if the files differ.  If they do, it then runs 'diff -u -w -I^#.*$' on the file.  This results in two processes invoked for every file difference.  I sped things up by replacing the first 'diff -q' with my filecmp() function which does an mmap() and memcmp() operation.
- I eventually get a SIGSEGV while trying to read /usr/share/scap-security-guide/ansible, so I think some additional file type checks need to be in place.

There's not a lot I can do about the second diff(1) invocation right now until I can replace my usage of diff(1) with a library call.  That's far down the road for now, but I think the above improvements will fix things up.  OK, back to it.

**Comment by dcantrell** [comment]
Yep, ugh, you would think I would stop doing this.  It's trying to read and diff directories.  Restricting to S_ISREG() and continuing...

**Comment by dcantrell** [comment]
OK, new discovery.... it thinks documentation files are %config files.  This is likely librpm lying to me.  And the investigation continues.

**Comment by dcantrell** [comment]
I think I have things working now.  Here's the current output from my test run:

```
rpminspect:
-----------
1) command line 
Result: INFO
Waiver Authorization: Not Waivable

Details:
/home/dcantrell/scm/github.com/dcantrell/rpminspect/build/src/rpminspect -w /data/bigvar/tmp/rpminspect -c /var/tmp/rpminspect.yaml.jF4eO4 -v -d -T config scap-security-guide-0.1.48-7.el8 scap-security-guide-0.1.48-9.el8_2



config:
-------
Result: OK
Waiver Authorization: Not Waivable
```

**Comment by thrix** [comment]
Awesome, can you post us versions of `rpminspect` / `rpminspect-data-redhat` which will containe the fixes? just for verification purposes.

**Comment by dcantrell** [comment]
rpminspect-1.2-0.1.202010132025git from my copr repo contains the fix.  No changes to rpminspect-data-redhat.

**Comment by dcantrell** [comment]
NOTE: Please make sure you use rpminspect-1.2-0.1.202010132025git or higher from Copr.  I just pushed two fixes that I found on Fedora systems.  It's 10:29 PM my time, which is way past when I work.  But I just pushed it and it should be building now in Copr.
