### ISSUE TITLE
Cannot install rpminspect & rpminspect-data-redhat on RHEL8

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#232]
Our users are reporting problems when installing rpminspect on RHEL8. Current version of the internal `rpminspect-data-redhat` does not work with the one from the `dcantrell/rpminspect` copr repo nor the one from EPEL.

I was not able to find `rpminspect-data-redhat` in Brew ....

Could you please look at it? As a workaround we are instructing users to use F32 container image to play around with `rpminspect`.

**Comment by dcantrell** [comment]
Looking at this now.
