### ISSUE TITLE
Allow multiple domains in buildhost_subdomain

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#25]
As we've discovered, especially when it comes to special architectures like s390x, Fedora may share build systems with Red Hat (or CentOS, etc). To solve for this, we should allow mutiple domains so we can still filter out unexpected domains, but allow two or more if required.

**Comment by hroncok** [comment]
An example is here:

    Package Build Host "dhafeman.bos.redhat.com" is not within ".fedoraproject.org" in python3-...-3.7.4-3.fc31.s390x

**Comment by dcantrell** [comment]
The buildhost_subdomain setting in rpminspect.conf is now handled as a space-delimited string.  You can specify multiple build host subdomains just separated by spaces.  This will let us add .bos.redhat.com for the s390x builders.
    
I have tested this out by changing buildhost_subdomain in my rpminspect.conf file to:
    
        ".fedoraproject.org .bos.redhat.com"
    
And it works.  I will also change the rpminspect-data-fedora package to add .bos.redhat.com.
