### ISSUE TITLE
check-conflict raises false alarm by ignoring Obsoletes 

### ISSUE THREAD

**Issue by pmoravec** [rpminspect/rpminspect#252]
General scenario should be:

- packages A and B in some release
- B provides a file F1
- new version of A provides F1 and obsoletes B (via "Obsolete: B" in spec file)

This allows me to manually update to the new version of A on a system with both A and B packages present, as dnf removes the obsolete package B during the upgrade.

But `<arch>-check-conflicts` tests raise error like:

    Undeclared file conflicts:
    newA provides F1 which is also provided by B

**Comment by msrb** [comment]
Moved to JIRA as this is a problem in rpmdeplint pipeline, not rpminspect. In any case, thanks for the bug report @pmoravec :wink:

**Comment by thrix** [comment]
yeah, sorry also, did not spot this is about rpmdeplint not rpminspect :(

**Comment by dcantrell** [comment]
No problem, thanks for the clarification.
