### ISSUE TITLE
false positive  fedora-ci.koji-build.rpminspect.static-analysis run

### ISSUE THREAD

**Issue by marticak** [rpminspect/rpminspect#257]
I see a false positive  fedora-ci.koji-build.rpminspect.static-analysis run.

https://bodhi.fedoraproject.org/updates/FEDORA-2020-52df64a667

Shows a "/patches" failure, which actually seems to be "Error: exec session exited with non-zero exit code 1: OCI runtime error
".

**Comment by dcantrell** [comment]
I have worked on this one for a bit and after thinking about it more, I feel that the 'patches' inspection is best turned off in the default case for Fedora.  It really only makes sense for RHEL packages, but there may be instances where Fedora packagers want it.

This did not require a change to rpminspect, just to the rpminspect-data-fedora package.  Here is the commit:
https://github.com/rpminspect/rpminspect-data-fedora/commit/016599dad2ba7ad5816937516cf3484e231accaa

Thanks for the report.
