### ISSUE TITLE
A new rpminspect webapp

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#259]
Hi,

I'd like to share that we created a webapp [1] to help visualize the rpminspect json report.
The webapp is deployed here [2]. An example of a report is available here [3].

We will be happy to improve it if you think about some improvements.
Should we advertise it somewhere in the rpminspect README or in contrib ?
Let us know what do you think.

Fabien

[1]: https://softwarefactory-project.io/cgit/software-factory/rpminspect-report/tree/
[2]: https://fedora.softwarefactory-project.io/rpminspect-report/
[3]: https://fedora.softwarefactory-project.io/rpminspect-report/?url=https://fedora.softwarefactory-project.io/logs/16/16/eb9dd459455eba354948761c461be9ef55543d7e/check/rpm-rpminspect/680a4c8/result.json

**Comment by dcantrell** [comment]
Nice, this looks good.  I am on PTO for basically all of December.  I will look at this in January when I return to work.

**Comment by dcantrell** [comment]
I would like to mention this webapp in the contrib/ directory.  Can you write up a text file that explains it?

Also, rpminspect now has XUnit output support.  I don't know if that would make your web app easier to work with in terms of processing the output for display, but I wanted to let you know it's there.

**Comment by morucci** [comment]
Hi David, let me know if your are fine with that PR.

**Comment by dcantrell** [comment]
Thanks for the PR, merged!
