### ISSUE TITLE
Unapproved license in perl-interpreter-4:5.26.3-417.el8_3.aarch64: Artistic

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#260]
A license check for perl-interpreter-4:5.26.3-417.el8_3.aarch64 binary package fails like this:

~~~~
$ rpminspect-fedora -T license perl-interpreter-5.26.3-417.el8_3.aarch64.rpm 
rpminspect:
-----------
1) command line 
Result: INFO
Waiver Authorization: Not Waivable

Details:
/usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml -T license perl-interpreter-5.26.3-417.el8_3.aarch64.rpm



license:
--------
1) Unapproved license in perl-interpreter-4:5.26.3-417.el8_3.aarch64: Artistic 
Result: BAD
Waiver Authorization: Not Waivable
[...]
~~~~

I think that rpminspect fails to correctly extract a license tag because the license is:

~~~~
$ rpm -q --qf '%{LICENSE}\n' -p perl-interpreter-5.26.3-417.el8_3.aarch64.rpm 
(GPL+ or Artistic) and (GPLv2+ or Artistic) and BSD and Public Domain and UCD
~~~~

I have rpminspect-1.2-2.fc34.x86_64 and rpminspect-data-fedora-1.2-1.fc34.noarch.

**Comment by dcantrell** [comment]
Looks like an error in the function where it's breaking down the License tag string.  It's getting these substrings:
debug: is_valid_expression (161): APPROVED: |GPL+ or Artistic|
debug: is_valid_expression (185): APPROVED: |GPLv2+|
debug: is_valid_expression (185): APPROVED: |BSD|
debug: is_valid_expression (185): APPROVED: |Public Domain|
debug: is_valid_expression (206): APPROVED: |UCD|

So the "(GPLv2+ or Artistic)" is being split when it shouldn't.  Still working on this one.

**Comment by dcantrell** [comment]
More debugging:

debug: main (768): product_release=el8_3
debug: is_valid_license (301): TOKEN: |GPL+ or Artistic|
debug: is_valid_expression (161): APPROVED: |GPL+ or Artistic|
debug: is_valid_license (301): TOKEN: | and |
debug: is_valid_license (301): TOKEN: |GPLv2+ or Artistic|
debug: is_valid_expression (196): lic=|GPLv2+|
debug: is_valid_expression (185): APPROVED: |GPLv2+|
debug: is_valid_expression (196): lic=|(null)|
debug: is_valid_expression (196): lic=|Artistic|
debug: is_valid_license (301): TOKEN: | and BSD and Public Domain and UCD|
debug: is_valid_expression (196): lic=|BSD|
debug: is_valid_expression (185): APPROVED: |BSD|
debug: is_valid_expression (196): lic=|(null)|
debug: is_valid_expression (196): lic=|Public|
debug: is_valid_expression (196): lic=|Public Domain|
debug: is_valid_expression (185): APPROVED: |Public Domain|
debug: is_valid_expression (196): lic=|(null)|
debug: is_valid_expression (196): lic=|UCD|
debug: is_valid_expression (208): APPROVED: |UCD|

It's splitting "(GPLv2+ or Artistic)" and it's definitely my fault.  Fix coming shortly.

**Comment by dcantrell** [comment]
OK, upon further investigation, it's not rpminspect at fault here.  It's the JSON file that provides all of the license information.  The entry for the "GPLv2+ or Artistic" license was called "Perl License (variant)" but that symbolic name was also used for "LGPLv2+ or Artistic".  The entry names need to be unique or they override each other so there's only one.

I'm going to fix this in the license JSON file at https://github.com/rpminspect/rpminspect-data-fedora but also see if there's a way I can iterate the dict entries ignoring the uniqueness of the names.

**Comment by dcantrell** [comment]
Don't see an obvious way to do this with json-c, so I'm modifying the data files in the corresponding rpminspect-data packages to have unique keys.

**Comment by dcantrell** [comment]
The latest rpminspect-data-fedora package in my Copr repo has a fixed license database:

https://copr.fedorainfracloud.org/coprs/dcantrell/rpminspect/

The next release of rpminspect-data-fedora will also include the fix.
