### ISSUE TITLE
RFE: support an 'exclude_path' setting within the 'badfuncs' config file section

### ISSUE THREAD

**Issue by dcantrell** [rpminspect/rpminspect#279]
This should work the same way as the exclude_path setting in the elf inspection, but be restricted to the badfuncs inspection.

**Comment by dcantrell** [comment]
This is handled via the new per-inspection ignore support.  The badfuncs inspection allows an ignore list using glob(7) syntax.  Verified with the python3.10 package in Fedora.

**Comment by hroncok** [comment]
Thanks!
