### ISSUE TITLE
RFE: Changed files (new/deleted/modified) between RPM versions

### ISSUE THREAD

**Issue by cipherboy** [rpminspect/rpminspect#29]
I'd like to use rpminspect to compare two RPMs for:

 - What files were added
 - What files were removed
 - What files might've been changed (optional, might be a lot of useless noise -- I probably wouldn't use this feature)

This should help to prevent accidental packaging of unintended files and let us review the changes between versions.

**Comment by dcantrell** [comment]
I am currently working on a new inspection called 'changedfiles' that reports changes between builds.  It is distinct from newfiles, removedfiles, and movedfiles.  It is confusing, but it actually makes the code somewhat easier to manage and I am modeling the test breakdown on the internal rpmdiff tool.  I should have changedfiles done tomorrow.

**Comment by dcantrell** [comment]
changedfiles, addedfiles, and removedfiles are now present in the list of inspections.  I'm going to close this request out because the specifics can be worked on around those frameworks.
