### ISSUE TITLE
[RFE] Make the output of "rpminspect -D" a valid YAML

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#306]
Currently when I run `rpminspect -D` it prints the current configuration, but it also adds a header and footer (that one is maybe not intentional):

```
$ rpminspect -D -c /usr/share/rpminspect/redhat.yaml
Program Configuration
==========
    ---
    common:
        workdir: /var/tmp/rpminspect

<snip>

==========
rpminspect: *** Invalid before and after build specification.
rpminspect: *** See `rpminspect --help` for more information.
```

Everything's printed on stderr. This is OK for humans, but not for machines where I'd expect a valid YAML that I can parse.

I think the structure could stay the same, but the actual configuration could go to stdout instead of stderr. That way people could get the YAML and easily filter out the rest.

**Comment by msrb** [comment]
Note it also currently exits with 2. But when I use `-D`, I usually don't want to run rpminspect on any builds. I am just interested in the config :)

**Comment by dcantrell** [comment]
This is reasonable.  The original intent of the dump config function was to report what the actual configuration settings are for that invocation of the program.  I will move it to stdout and make it parseable YAML and make sure it does error out.
