### ISSUE TITLE
Performance issue on some inspections ?

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#309]
Hi David,

In the CI we regularly see that our rpminspect job is taking more than 30 minutes to execute. Our CI system is configured with a default job timeout of 30 minutes so the rpminspect job is aborted. We could increase the
the timeout delay for the job but I'd like to get your input first.

Here I list some jobs logs that timeout recently:

- https://fedora.softwarefactory-project.io/zuul/build/5cd137ef85894c359b527ea27d359030/log/job-output.txt#481
- https://fedora.softwarefactory-project.io/zuul/build/c11b5fcc985e46abafde7277fba63ca8/log/job-output.txt#1506
- https://fedora.softwarefactory-project.io/zuul/build/f273ea3964d5462093cfadb0ab930923/log/job-output.txt#730

Thanks in advance
Fabien

**Comment by dcantrell** [comment]
I tried to reproduce some of these locally:

- rpminspect -v oval-graph-1.2.4-2.fc34 oval-graph-1.2.5-1.fc35: completed in about 15 seconds
- rpminspect -v fedora-release-35-0.3: completed in about 14 seconds
- rpminspect -v rpm-ostree-2021.2-2.fc35: completed in about 56 seconds

I'm not sure there's an rpminspect problem.  Have I read the log output incorrectly?

**Comment by morucci** [comment]
Ok I'm not able to reproduce the issue. I bet the CI context leads to the command taking more time than expected. 

I'd like to suggest for the '-v' option to add inspection time processing details to the output. Also maybe '-D' should return the rpminspect version too ?

This issue can be closed. Sorry for the inconvenience.

**Comment by dcantrell** [comment]
I can add the version information to the output in the command line results section.  That reports the command line used to invoke rpminspect.  The timing information is easier if you just wrap rpminspect in '/usr/bin/time -v'.  That's what I do to get rough run time estimates.

**Comment by dcantrell** [comment]
OK, added version information to the rpminspect results just before the command line.  Looks like this:

```
1) version

Result: INFO
Waiver Authorization: Not Waivable

Details:
rpminspect version 1.4
```
