### ISSUE TITLE
segmentation fault validating ghostscript packages

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#310]
Hi David,

I noticed that our rpminspect job failed due to a segfault of rpminspect command when inspecting ghostscript packages.

See this job output log https://fedora.softwarefactory-project.io/zuul/build/cf1e1680d5c544d8877c73bef7d871eb/log/job-output.txt#1049

Built artifacts can be found here: https://fedora.softwarefactory-project.io/logs/10/10/ff753354e022ba010ced0e5be3e9cdd059626c41/check/rpm-scratch-build/5b62887/repo/

Thanks in advance
Let me know how could I help

Fabien

**Comment by dcantrell** [comment]
Unable to reproduce this with the latest stable release of rpminspect.

**Comment by morucci** [comment]
Ah, ok, sorry, I've tried it locally and no segfault. Version 1.4 from copr.

**Comment by dcantrell** [comment]
Thanks for verifying!
