### ISSUE TITLE
RFE: Add ability to exclude subpackages in emptyrpm test

### ISSUE THREAD

**Issue by rvykydal** [rpminspect/rpminspect#355]
In Anaconda we have metapackages (anaconda, anaconda-install-env-deps, anaconda-install-img-deps) that shouldn't make the check fail.
Like in `rpminspect-fedora -v -T emptyrpm anaconda-35.11-1.fc35`

**Comment by dcantrell** [comment]
OK, I have a patch for the emptyrpm inspection where you can list expected empty RPMs in the rpminspect.yaml file.  For anaconda, I did this locally and ran rpminspect again:

```
---
emptyrpm:
    expected_empty:
        - anaconda
        - anaconda-install-env-deps
        - anaconda-install-img-deps
```

rpminspect will still report the empty payloads, but they will be classified as INFO and it will say the empty payload is expected per the configuration file.

**Comment by rvykydal** [comment]
Thank you!
