### ISSUE TITLE
allow /usr/lib/dracut and /usr/lib/udev in files check

### ISSUE THREAD

**Issue by sharkcz** [rpminspect/rpminspect#360]
Both dracut and udev explicitly store files under `/usr/lib/dracut` and `/usr/lib/udev` respectively, but rpminspect rejects `/usr/lib` as valid path in `%files` in the files check. There are no system-wide macros provided for these location, thus `/usr/lib/{dracut,udev}/...` must be specified in the spec files.

**Comment by dcantrell** [comment]
What I need for this is to add an exclude capability to this inspection so you can define those paths in the per-package rpminspect.yaml file in dist-git.  This is aligned with the existing exclude path specification work I am doing.

**Comment by dcantrell** [comment]
Can you provide an NVR of with dracut or systemd that results in rpminspect generating an error as described?  I am trying to reproduce this locally using recent Fedora builds and cannot get the files inspection to show an error.  Thanks.

**Comment by sharkcz** [comment]
It came from a RHEL-9 gating, but I suppose you should get the same result from s390utils from Fedora.

**Comment by dcantrell** [comment]
OK, thanks.  I have a reproducer now.

**Comment by dcantrell** [comment]
OK, I have a fix.  You can use the ignore list in the configuration file under the files section to put path prefixes to ignore.  In the s390utils rpminspect.yaml file in dist-git, you can do this:

```
---
files:
    ignore:
        - /usr/lib/udev/
        - /usr/lib/dracut/
```

That will still let the inspection run, but ignore the files that begin with that path prefix.  It will still report anything else in /usr/lib is a failure.

Patch coming momentarily for this, but I wanted to explain what I changed.  Also, the dracut and systemd packages appear to use macros to specify the paths in %files.  rpminspect does not expand these macros currently, so those packages should pass anyway.

**Comment by sharkcz** [comment]
I believe the "ignores" should be set on distribution level, not in the individual packages, because it's the distribution what defines these path.

**Comment by dcantrell** [comment]
That's fine.  The same code path would be used.  If you want to add that as distribution-wide policy, send a PR to https://github.com/rpminspect/rpminspect-data-fedora with a change to the /usr/share/rpminspect/fedora.yaml file for the 'files' section.

For RHEL it would be redhat.yaml in the internal rpminspect-data-redhat project.
