### ISSUE TITLE
desktop: ignore (or demote as INFO) missing Exec when TryExec is specified

### ISSUE THREAD

**Issue by ptoscano** [rpminspect/rpminspect#395]
The desktop-entry-spec [1] describes a key called `TryExec`. Quoting the spec:

> Path to an executable file on disk used to determine if the program is actually installed. If the path is not an absolute path, the file is looked up in the $PATH environment variable. If the file is not present or if it is not executable, the entry may be ignored (not be used in menus, for example).

This is used, for example, to ship desktop files that enhance a certain executable without a strict dependency on it to avoid extra splitting of packages.

Right now, the `desktop` check reports as VERIFY when the executable specified in `Exec` is not part of any subpackage of the same source. This was reported as #373.

Considering the behaviour hinted by the spec, IMHO another approach could be to ignore the missing `Exec`, or demote its reporting as INFO, in case `TryExec` is specified: XDG menu implementations will check for the existence of the executable in `TryExec`, and if that does not exist then the desktop file will be ignored.

[1] https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Comment by dcantrell** [comment]
I like this idea.  Thanks for the information here.  I will extend the desktop inspection to handle the TryExec value in the manner you described.

**Comment by ptoscano** [comment]
Ah, I was actually working on a patch for this.

**Comment by dcantrell** [comment]
Oh, even better.  I will hold off on this and wait for your PR.
