### ISSUE TITLE
Different output formats use different names for some of the inspections

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#397]
JSON output uses different names for some of the inspections:

```
    'empty-payload': 'emptyrpm',
    'lost-payload': 'lostpayload',
    'header-metadata': 'metadata',
    'man-pages': 'manpage',
    'xml': 'xml-files',
    'elf-object-properties': 'elf',
    'desktop-entry-files': 'desktop',
    'dist-tag': 'disttag',
    'spec-file-name': 'specname',
    'java-bytecode': 'javabytecode',
    'changed-files': 'changedfiles',
    'moved-files': 'movedfiles',
    'removed-files': 'removedfiles',
    'added-files': 'addedfiles',
    'shell-syntax': 'shellsyntax',
    'dso-deps': 'dsodeps',
    'kernel-modules': 'kmod',
    'architectures': 'arch',
    'path-migration': 'pathmigration',
    'bad-functions': 'badfuncs'
```

I am not sure if this is a bug, but it surely looks like an oversight (?)

**Comment by dcantrell** [comment]
It's not a bug, but it does bother me now.  My original thought was that the name of the inspection would be shorter to type but the longer string would be what the report outputs.  But it does seem confusing now.  I'll change it.

**Comment by dcantrell** [comment]
Alright, I made this change.  The report output should now match the inspection names you pass to -T on the command line and that you see in the -l output.
