### ISSUE TITLE
Static web page output format

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#40]
Hi,

Having a html page output format could be useful and handy. My use case is to handle rpminspect in a CI job where results are exported on a http server and having a html page built by rpminspect would be awesome to give user a nice looking results page in that context.

Thanks,
Fabien

**Comment by morucci** [comment]
Hi David,

I went ahead and built a small python script to build the page from the json. I was part of my goal to have rpminspect run on PRs. Here is an example of a PR with multiple check jobs attached and there is one for rpminspect: https://src.fedoraproject.org/rpms/python-gear/pull-request/8#comment-30592.

Clicking on the rpminspect link you can access the html report https://fedora.softwarefactory-project.io/logs/8/8/8ac634d66b7e756e2e4c3711717a7a7d0563385e/check/artifact-rpminspect/1d61914/rpminspect.html.

Let me know if you like it. The code to build the html report is: https://pagure.io/fork/fbo/zuul-distro-jobs/blob/88b50688fb1077592d3fda682898059bbd63a547/f/roles/rpminspect-html-report/files/report-json2html.py

Thanks,
Fabien

**Comment by morucci** [comment]
Feel free to integrate it directly into rpminspect if the html report format is ok for you.

**Comment by dcantrell** [comment]
I like this as an example.  I would like to add it to a contrib/ directory in rpminspect and then bundle that in the package under the docs directory.  Could you create a pull request that adds the script to a contrib/ subdirectory along with a README file explaining how to use it?
