### ISSUE TITLE
Empty Payload, metapackages should not have a payload

### ISSUE THREAD

**Issue by jmflinuxtx** [rpminspect/rpminspect#400]
As rpminspect checks the payload of an rpm, it does not have an exception for a meta-rpm such as kernel, which was created to depend on kernel-core and kernel-modules, but contains no files itself:

empty-payload:
--------------
1) New package kernel-5.11.18-300.fc34.x86_64.rpm is empty (no payloads) 

This is valid and expected.

**Comment by dcantrell** [comment]
RPMs with expected empty payloads can be listed in the package's rpminspect.yaml file.  Here's what you can add to rpminspect.yaml:

```
emptyrpm:
    expected_empty:
        - kernel
```

See /usr/share/rpminspect/generic.yaml for more details on what can go in a package's rpminspect.yaml file.

**Comment by herton** [comment]
Should we change the configuration at https://github.com/rpminspect/rpminspect-data-fedora and also in rpminspect-data-redhat? Both Fedora and RHEL share the kernel behaviour here.
