### ISSUE TITLE
Docs around local rpminspect.yaml files

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#405]
I am looking for some documentation around local `rpminspect.yaml` files and how they can be used to tweak behavior of rpminspect. The target audience would be Fedora developers now, and I guess CentOS Stream developers and contributors later.

Maybe such docs already exist, but I did not find them.

Thanks!

**Comment by dcantrell** [comment]
Right now the definitive documentation for what can go in a local rpminspect.yaml file is in the example config file.  In the source tree for rpminspect, that is data/generic.yaml.  The config files in rpminspect-data-fedora and rpminspect-data-rhel contain those comments as well.

My TODO list has had "actually make documentation" on it for a while, so now is a good time to start.  My plan is to get some docs on readthedocs.io for both the end-user program and the library API.

**Comment by hhorak** [comment]
+1 for better documentation, as I've just been fooled by seeing `xml-files` in the output, but to filter the things out, I need to use just `xml` section in the rpminspect.yaml.

**Comment by hroncok** [comment]
> I've just been fooled by seeing `xml-files` in the output, but to filter the things out, I need to use just `xml` section in the rpminspect.yaml.

That possibly needs not only some documentation, but also might be worth reconsidering as a design choice. It is very confusing.

**Comment by hhorak** [comment]
Right, +1 for keeping it all in sync (log+sections in the yaml config) if possible

**Comment by dcantrell** [comment]
https://rpminspect.readthedocs.io/

Exists and is updated for each push and merge to the master branch.  If there are parts that need clarification or additional information, please open new issues for those requests.
