### ISSUE TITLE
capabilities not found

### ISSUE THREAD

**Issue by bachradsusi** [rpminspect/rpminspect#410]
~~~
$ rpminspect-fedora -r rawhide -T capabilities policycoreutils-sandbox-3.2-2.fc35.x86_64.rpm  
rpminspect:
-----------
1) version 
Result: INFO
Waiver Authorization: Not Waivable

Details:
rpminspect version 1.5



2) command line 
Result: INFO
Waiver Authorization: Not Waivable

Details:
/usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml -r rawhide -T capabilities policycoreutils-sandbox-3.2-2.fc35.x86_64.rpm



capabilities:
-------------
1) File capabilities expected for /usr/sbin/seunshare but not found on x86_64: expected
'cap_dac_override,cap_fowner,cap_setuid,cap_setpcap,cap_sys_admin,cap_sys_nice+ep'  
Result: BAD
Waiver Authorization: Security

Suggested Remedy: Unexpected capabilities were found on the indicated file.  Consult capabilities(7) and either adjust the files in the package or modify thecapabilities list in the rpminspect vendor data package.  The security team may also be of help for this situation.
~~~

~~~
$ rpm -q -p --filecaps policycoreutils-sandbox-3.2-2.fc35.x86_64.rpm
/usr/sbin/seunshare     cap_dac_override,cap_fowner,cap_setuid,cap_setpcap,cap_sys_admin,cap_sys_nice=ep
~~~

It looks like there was a change how file capabilities are presented on RHEL-9/Fedora.

~~~
[root@localhost tmp]# cat test_cap.c 
#include <stdio.h>
#include <sys/capability.h>

int main() {

    cap_t c;
    char *c_s;

    c = cap_get_file("file");
    c_s = cap_to_text(c, NULL);
    printf("%s\n", c_s);
    return 0;
}
[root@localhost tmp]# gcc test_cap.c -lcap
~~~

Fedora Rawhide:

~~~
[root@localhost tmp]# touch file
[root@localhost tmp]# setcap cap_sys_nice+ep file
[root@localhost tmp]# ./a.out 
cap_sys_nice=ep
~~~

RHEL-8

~~~
[root@ci-vm-10-0-137-204 ~]# touch file
[root@ci-vm-10-0-137-204 ~]# setcap cap_sys_nice+ep file
[root@ci-vm-10-0-137-204 ~]# ./a.out 
= cap_sys_nice+ep
~~~

**Comment by dcantrell** [comment]
I'm not sure this is a bug.  My first thought was that either the capabilities inspection needed to handle a new format and/or the capabilities/ files in the rpminspect-data-fedora package needed updating for newer releases.

First, drop the ```-r rawhide``` from the command line.  You don't need that.  rpminspect will infer fc35 from the build as the product release.  The data package does not use 'rawhide' as a symbolic name, it all maps to the dist tag values.

Second, once you drop that option I see the capabilities inspection passing for policycoreutils-3.2-2.fc35.  In librpminspect, I use libcap to read in the capabilities files by using cap_get_fd(), which appears to read the syntax we have there now and gives me a cap_t back.

Can you verify on your end?

**Comment by bachradsusi** [comment]
~~~
$ rpm -ql rpminspect-data-fedora-1.5-2.fc35.noarch | grep capabilities
/usr/share/rpminspect/capabilities
/usr/share/rpminspect/capabilities/rawhide
~~~

My feeling is that it doesn't check capabilities without `-r rawhide`. Note that I found this problem on centos 9 stream build using *rpminspect-data-redhat* which contains */usr/share/rpminspect/capabilities/el9* - see the internal report with the link to the internal rpminspect run

**Comment by dcantrell** [comment]
Ah, right.  I had put the rawhide files in there.  Those probably shouldn't be there.  I will separately clean up rpminspect-data-fedora.  However, your point is still valid.  I now have enough to go on with this reproducer and am working on a fix.
