### ISSUE TITLE
Possible memory leak in rpminspect since copr releases 1.6-0.1.202106081929git.fc34  or 1.6-0.1.202106071956git.fc34 ?

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#429]
Hello David,

I see that on two instances of our Zuul CI, we are having trouble to run rpminspect job. Containers running rpminspect got killed by OOMKiller almost each time.

I don't have a reproducer yet but all rpminspect jobs fail on the same task: https://pagure.io/zuul-distro-jobs/blob/master/f/roles/rpminspect/tasks/main.yaml#_46

Here is the history https://fedora.softwarefactory-project.io/zuul/builds?job_name=rpm-rpminspect where we see since the 8 of June it starts to fails almost every time.

Could it be possible recent changes introduce a mem leak ?

Furthermore, here is a link of Mem usage graph of the node that run rpminspect jobs: https://prometheus.monitoring.softwarefactory-project.io/grafana/d/EtRMbV1Zk/node-exporter-full?viewPanel=78&orgId=1&var-job=node&var-name=k1s02.softwarefactory-project.io&var-node=k1s02.softwarefactory-project.io&var-port=9100&from=1623113469244&to=1623259484640

We see that since the copr build 2239046 we are getting big memory pick.

I cannot say that 100% sure it is related to rpminspect but it looks like there are data that lead to it :)

I'll try to make a reproducer asap if needed.

Thank a lot in advance for the feedback.

Fabien

**Comment by dcantrell** [comment]
Entirely possible there's a leak somewhere.  Let me take a look at this in more detail and see what I can do.  Thanks for the report.

**Comment by morucci** [comment]
Hi David,

It seems last copr build behaves better. I did not notice failure since then: https://fedora.softwarefactory-project.io/zuul/builds?job_name=rpm-rpminspect

And I no longer see memory spikes on our monitoring: https://prometheus.monitoring.softwarefactory-project.io/grafana/d/EtRMbV1Zk/node-exporter-full?viewPanel=78&orgId=1&var-job=node&var-name=k1s02.softwarefactory-project.io&var-node=k1s02.softwarefactory-project.io&var-port=9100&from=1623319903098&to=1623395843196

I'll continue to monitor.
Thanks for the fixes !

**Comment by dcantrell** [comment]
Those failures look like completed runs of rpminspect and it's just reporting findings.  I did a lot of memory leak fixing the other day and it's in this commit:  https://github.com/rpminspect/rpminspect/commit/60849c7dec3e21595419f28050c884af17282c4b

I'll close out this bug and if you find anything new, just open a new one.
