### ISSUE TITLE
rpminspect: realpath: No such file or directory

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#433]
version: rpminspect-1.6-0.1.202106081929git.fc34.x86_64

```
$ rpminspect
rpminspect: realpath: No such file or directory
```

The problem seems to be here:
https://github.com/rpminspect/rpminspect/blob/master/src/rpminspect.c#L537-L539
`realpath()` looks for the `rpminspect` binary in the current working directory.
```
getcwd("/home/msrb", 1024)              = 11
readlink("/home/msrb/rpminspect", 0x7ffde5a7b720, 1023) = -1 ENOENT (No such file or directory)
write(2, "rpminspect: ", 12rpminspect: )            = 12
write(2, "realpath", 8realpath)                 = 8
< snip >
write(2, ": No such file or directory\n", 28: No such file or directory
) = 28
exit_group(1)                           = ?
+++ exited with 1 +++

```

Running rpminspect via absolute path works as expected:
```
$ /usr/bin/rpminspect
rpminspect: Please specify a configuration file using '-c' or supply ./rpminspect.yaml
$ rpminspect-fedora 
rpminspect: *** Invalid before and after build specification.
rpminspect: *** See `rpminspect --help` for more information.
```

**Comment by dcantrell** [comment]
This is impacted by what you have in $PATH.  What is the value of your PATH environment variable and what directory are you launching rpminspect from?  This is entirely valid and I want to recreate it locally so I can fix it and add a test case.

**Comment by msrb** [comment]
```
$ echo $PATH
/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
```

I am launching rpminspect from my home directory.

I believe the problem is here: https://github.com/rpminspect/rpminspect/blob/60849c7dec3e21595419f28050c884af17282c4b/src/rpminspect.c#L532-L534

`realpath(3)` doesn't (afaik) care about PATH -- if the given path (`argv[0]` in this case) doesn't start with `/`, it assumes that it's a file/dir in the current working directory.

```
[msrb@localhost ~]$ pwd
/home/msrb
[msrb@localhost ~]$ echo $PATH
/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
[msrb@localhost ~]$ rpminspect
rpminspect: realpath: No such file or directory
[msrb@localhost ~]$ touch rpminspect
[msrb@localhost ~]$ rpminspect
rpminspect: Please specify a configuration file using '-c' or supply ./rpminspect.yaml
```

**Comment by dcantrell** [comment]
Yep, you're right.  My mistake.  I've modified the code to only run realpath if argv[0] contains a '/' in it, otherwise it takes the argument as given.  Patch coming momentarily.
