### ISSUE TITLE
rpminspect runpath test should allow /usr/libexec/* rpaths and runpaths

### ISSUE THREAD

**Issue by stratakis** [rpminspect/rpminspect#454]
On Fedora some packages might own a directory in /usr/libexec/* but if a binary or a library contains an rpath pointing to those directories, the runpath test will fail.

e.g. testing [glib2](https://kojipkgs.fedoraproject.org//packages/glib2/2.68.3/2.fc35/x86_64/glib2-tests-2.68.3-2.fc35.x86_64.rpm)

rpminspect-fedora --test runpath glib2-tests-2.68.2-1.fc35.x86_64.rpm

1) /usr/libexec/installed-tests/glib/gdbus-peer has an invalid-looking DT_RUNPATH on x86_64: /usr/libexec/installed-tests/glib

This was a recently reported issue through https://bugzilla.redhat.com/show_bug.cgi?id=1973304, for which the upstream rpm script, checking for rpaths was fixed to allow for that use-case: https://github.com/rpm-software-management/rpm/pull/1721/files

**Comment by dcantrell** [comment]
This is just a configuration file change for rpminspect on Fedora.  You can either make the change in glib2's rpminspect.yaml file in the package git repo, or if you want this to be a distribution wide change you can modify fedora.yaml in the rpminspect-data-fedora project:

https://github.com/rpminspect/rpminspect-data-fedora/blob/master/fedora.yaml#L700

Uncomment the allowed_paths block and add /usr/libexec to it.  Send the PR to the rpminspect-data-fedora project.

Thanks!

**Comment by dcantrell** [comment]
Also, for RHEL there is an internal rpminspect-data-redhat package on gitlab.cee.redhat.com.  If this policy change applies there, I would appreciate a pull request on that project too.

And there's also an rpminspect-data-centos project here:  https://gitlab.com/redhat/centos-stream/ci-cd/rpminspect-data-centos
If the policy change applies to CentOS builds, send a pull request to that one too.

The data packages for rpminspect are meant to allow us to have per-distribution packaging policies but also be jointly maintained by everyone working on the distribution.  I have tried to make it as easy as possible.

**Comment by stratakis** [comment]
This is not though a per package change. For example sudo also was affected: https://bugzilla.redhat.com/show_bug.cgi?id=1969310

I'd argue this should be allowed in the rpminspect codebase in a similar way as https://github.com/rpminspect/rpminspect/commit/4ac9d0f00b20f28e6c3db0a062a09e4d2b752390 was fixed, since glib2 and sudo own those directories that their RPATH was pointing to.

**Comment by hroncok** [comment]
I am a bit confused why "rpminspect is failing on the RPATH check for private directories" was considered a program problem and "rpminspect is failing on the RPATH check for private directories in libexec" is considered a configuration problem.

**Comment by dcantrell** [comment]
I'm probably wrong here then.  The change for 4ac9d0f should apply here and I don't know why it's not working.  I will take a look at this on Monday, I am currently on PTO today.

**Comment by dcantrell** [comment]
Yeah, this was a bug in my previous patch to handle DT_RUNPATH/DT_RPATH values that are directories owned by the package.  I was incorrectly insisting on an allowed_paths list, which is optional.  Patch is super simple and it fixes everything up.

**Comment by stratakis** [comment]
Thank you for resolving the issue!
