### ISSUE TITLE
desktop icon test provides wrong message

### ISSUE THREAD

**Issue by mcrha** [rpminspect/rpminspect#475]
There seems to be a regression in the error message, which rose recently. The `rpminspect version: 1.6-0.1.202106292017git.fc34 (with data package: 1:1.5-0.1.202105061811git.fc34)` currently says: `Desktop file /usr/share/applications/org.gnome.Evolution-alarm-notify.desktop on ppc64le references icon /usr/libexec/evolution-data-server/evolution-alarm-notify but no subpackages contain /usr/libexec/evolution-data-server/evolution-alarm-notify` (it references the executable, not the icon name). I do not know how much it is related to your ongoing work for https://github.com/rpminspect/rpminspect/issues/467 .

**Comment by mcrha** [comment]
err, I meant #422

**Comment by mcrha** [comment]
Interestingly,  the same rpminspect version, but package `gnome-software` shows correct icon names: `Desktop file /usr/share/applications/gnome-software-local-file.desktop on i686 references icon system-software-install but no subpackages contain system-software-install`

**Comment by dcantrell** [comment]
Thanks.  This is related to my existing work in progress for fixing up the desktop inspection for standard system icons.

**Comment by dcantrell** [comment]
I believe this is now fixed with the latest development build and the latest rpminspect-data-fedora package in Copr.  When I run rpminspect on both evolution and evolution-data-server, I get this output for the desktop inspection:

```
$ rpminspect-fedora -T desktop evolution-3.40.4-2.fc34
...
desktop:
--------
Result: OK
Waiver Authorization: Not Waivable

$ rpminspect-fedora -T desktop evolution-data-server-3.42.0-1.fc35
...
desktop:
--------
Result: OK
Waiver Authorization: Not Waivable
```

(leading output from rpminspect trimmed for the purposes of this comment)
