### ISSUE TITLE
permissions test - setgid bit for non-root group should be considered safe

### ISSUE THREAD

**Issue by sharkcz** [rpminspect/rpminspect#478]
I am getting a failure in the permissions test when it considers the setgid bit set for a directory owned by non-root group as unsafe.

`/var/log/ts-shell` is owned by `root:ts-shell` with mode 2770 set in the spec file with `%dir %attr(2770,root,ts-shell) /var/log/ts-shell`

I believe this is a safe setup and shouldn't be reported by rpminspect as an issue.

**Comment by dcantrell** [comment]
What build is this happening on?

**Comment by sharkcz** [comment]
it's for s390utils, the s390utils-iucvterm subpackage specifically

**Comment by dcantrell** [comment]
Ah, ok, these are permissions and ownerships that need to be noted in the rpminspect-data-fedora and rpminspect-data-redhat packages.  Send a PR to https://github.com/rpminspect/rpminspect-data-fedora with the changes to the appropriate file or files in the **fileinfo/** subdirectory.  For RHEL, do the same but for the https://gitlab.cee.redhat.com/osci/rpminspect-data-redhat project.

**Comment by dcantrell** [comment]
I have a patch to update the remedy text for these findings that tell you what file in the data packages to edit for these changes.  You still need to make the changes in the rpminspect data packages and send pull requests.

**Comment by dcantrell** [comment]
I went ahead and made the changes to the three rpminspect data packages.  I update the fileinfo files for f35, centos9, and el9.  If you need it in other releases, please send pull requests with the appropriate changes.

I also gave the wrong URL to the rpminspect-data-centos project.  It is here:
https://gitlab.com/redhat/centos-stream/ci-cd/rpminspect-data-centos

**Comment by sharkcz** [comment]
Thanks, David. I was more thinking about a code change that could differentiate between safe and unsafe usage of the setgid bit. But if it's expected to maintain such things in config files, it works for me too.
