### ISSUE TITLE
Override rpminspect configuration file did not work 

### ISSUE THREAD

**Issue by liangwen12year** [rpminspect/rpminspect#485]
NetworkManager developer is aware of `inet_aton` labled as bad function by rpminspect default configuration file because `inet_aton` does not support ipv6. Since NetworkManager only use `inet_aton` for ipv4, we decided to override the default rpminspect configuration file about the badfunc list, see https://gitlab.com/redhat/centos-stream/rpms/NetworkManager/-/merge_requests/6/diffs.

But it did not take effect at all, NetworkManager CI gating still raised bad func failures.
See https://dashboard.osci.redhat.com/#/artifact/brew-build/aid/38523445.

This looks like a bug in librpminspect.  Maybe what's happening is that the initial badfunc list is read in from the rpminspect-data package and the subsequent config files are just appending additional data rather than overriding what was read in.

**Comment by dcantrell** [comment]
I have verified this today and it is a bug in librpminspect.  I have a patch in progress, but will complete it on Monday.  I want to make sure it works in all test cases and I believe my handling of the ignore lists needs a slight change.  Anyways, just wanted to post my status for this today.
