### ISSUE TITLE
rpminspect test on Fedora does not handle the %autorelease macro properly

### ISSUE THREAD

**Issue by sgallagher** [rpminspect/rpminspect#504]
The `disttag` test incorrectly believes that the `%{?dist}` tag is not present when the spec file has `Release: %autorelease` (provided by [rpmautospec](https://docs.pagure.org/Fedora-Infra.rpmautospec/)).

[Failure log](https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/39024/testReport/(root)/tests/_disttag/)

Looking at the code for that test, my suspicion is that rpminspect should actually be handling this properly, but for some reason the `rpmautospec-rpm-macros` package is not present on the system where rpminspect is running.

**Comment by dcantrell** [comment]
Confirmed this locally.  Investigating a proper fix for this.

**Comment by dcantrell** [comment]
OK so where I am with this is an in progress patch that adds librpm macro expansion handling to rpminspect.  This will cover the system-wide macro cases so that rpminspect will know about stuff like %autorelease if you have that file in /usr/lib/rpm.

Currently I have a few failing test cases and I need to add some for %autorelease, but I should be able to do that tomorrow.

**Comment by dcantrell** [comment]
Have a PR to handle this now, tests are running.

**Comment by sgallagher** [comment]
This appears to have reappeared. For example https://artifacts.dev.testing-farm.io/d8b101b1-ac86-42ad-b473-77347087d89e/

```
disttag
BAD
The Release: tag value is missing the dist tag in the proper form. The dist tag should be of the form '%{?dist}' in the Release: tag or in a macro used in the Release: tag. After RPM macro expansion, no dist tag was found in this Release: tag value.
Not Waivable
Suggested remedy:
The Release: tag in the spec file must include a '%{?dist}' string. Please add this to the spec file per the distribution packaging guidelines.

%autorelease
```
