### ISSUE TITLE
Don't mask upstream source changes; make them visible

### ISSUE THREAD

**Issue by t184256** [rpminspect/rpminspect#51]
I don't like the reasoning briefly outlined here:

https://github.com/rpminspect/rpminspect/blob/a38b57f35a7bfd58ef2a00c01ef6ca0c425af14e/lib/inspect_upstream.c#L121

Masking upstream source changes in case of a version number bump is dangerous, because literally anything might change.n

I propose making it a moderately big deal that requires manual inspection, or, at the _very_ least, making it emit a passive, but visible notice. Swallowing that fact silently is not OK for a package comparison tool.

**Comment by dcantrell** [comment]
I agree with your assessment here.  The layout of this inspection was modeled after what rpminspect's ancestor does.  And I think the assumption there was that a version change or epoch change implies the upstream source is changing.  But I agree with you and think even if that's expected, it should still show up as something that needs verification.  The tool is performing a comparsion and that is a difference, even if it's deliberate.

I will change it to behave as you are describing.  Thanks!
