### ISSUE TITLE
dynamic-tags test (PAC_PLT flag is missing from the dynamic tags) fails on all F36 builds

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#520]
I noticed on libmodulemd-2.13.0-3.fc36 and maim-5.6.3-6.fc36 that rpminspect uniformly reports a missing PAC_PLT on aarch64 builds. Examples <https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/42007/testReport/(root)/tests/_annocheck/>, <https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/42003/testReport/(root)/tests/_annocheck/>.

I verified in libmodulemd build.log that all "gcc" calls have -mbranch-protection=standard option. It looks like a bug in rpminspect or a toolchain.

rpminspect version: 1.7-0.1.202109101502git.fc36 (with data package: 1.6)
rpminspect profile: rawhide

**Comment by QuLogic** [comment]
related: https://pagure.io/fedora-ci/general/issue/286

**Comment by dcantrell** [comment]
I believe this is an issue in annocheck.  In the output you linked to, the version of annocheck in use is 10.02.  On my local system I am using 9.79 and this is what I get for PAC_PLT on aarch64 for those two builds:

```
...
Hardened: /usr/bin/modulemd-validator: look: PAC_PLT tag is missing from dynamic tags.
Hardened: /usr/bin/modulemd-validator: ^^^^:  This test is not yet enabled, but if it was enabled, it would fail...
...

...
Hardened: /usr/bin/maim: look: PAC_PLT tag is missing from dynamic tags.
Hardened: /usr/bin/maim: ^^^^:  This test is not yet enabled, but if it was enabled, it would fail...
...
```

It looks like the check has now been enabled in annocheck but not working correctly.  You can open a bug against the annobin package at bugzilla.redhat.com under Fedora.
