### ISSUE TITLE
Overriding emptyrpm results in garbage in the output

### ISSUE THREAD

**Issue by bcl** [rpminspect/rpminspect#530]
I am trying to override emptyrpm for lorax-lmc-virt and -novirt. I have a rpminspect.yaml

```
---
emptyrpm:
  expected_empty:
    - lorax-lmc-virt
    - lorax-lmc-novirt
```

I run `rpminspect-fedora ./results_lorax/35.7/1.fc36/lorax-lmc-novirt-35.7-1.fc36.x86_64.rpm` and the output for the emptyrpm section is:

```
emptyrpm:
---------
1) New package lorax-lmc-novirt-35.7-1.fc36.x86_64.rpm is empty (no payloads); this is expected per the
configuration file 
Result: INFO
Waiver Authorization: Not Waivable



2) <E3>֏^RDV 
Result: OK
Waiver Authorization: Not Waivable
```

Using:

```
rpminspect-1.7-0.1.202109282031git.fc33.x86_64
librpminspect-1.7-0.1.202109282031git.fc33.x86_64
```

On Fedora 33.

**Comment by dcantrell** [comment]
Was able to reproduce this locally using the latest dev build.  What's interesting is that it only does this when you specify a single RPM.  If you give it the entire Koji build it runs fine and does not generic the bogus result.
