### ISSUE TITLE
rpminspect license check fails with "Redistributable" license

### ISSUE THREAD

**Issue by herton** [rpminspect/rpminspect#546]
Seems that even when with "Redistributable, no modification permitted" license is approved at licenses/redhat.json, the license check eg. still fails with:

"1) Unapproved license in kernel-5.14.0-11.el9.aarch64: Redistributable, no modification permitted"

The rpminspect-data-* seems to have the correct data and the license is listed as approved (this issue was found in rhel 9 osci).

**Comment by dcantrell** [comment]
My initial patch was forcing that fedora_abbrev and spdx_abbrev both be empty strings in the JSON file, but in the case of the Redistributable entry the spdx_abbrev field said something like "#No official...".  So I have modified things to just try to match fedora_abbrev, spdx_abbrev, or fedora_name.

**Comment by dcantrell** [comment]
Well, correction.  Match fedora_name iff fedora_abbrev and spdx_abbrev are empty.  If there is an abbreviation, you must use that.  But fall back on fedora_name in other instances.
