### ISSUE TITLE
Examples in readme do not work

### ISSUE THREAD

**Issue by Jakuje** [rpminspect/rpminspect#578]
While getting familiar with `rpminspect`, I thought using examples from README might help. But most of the commands in https://github.com/rpminspect/rpminspect#usage do not work, mostly because the `rpminspect` requires the configuration file these days (unless I miss something -- I am running Fedora 34 with both rpminspect and rpminspect-data-fedora installed).

```
$ rpminspect -v tmux-2.9a-2.fc31 tmux-2.9a-3.fc31
rpminspect: Please specify a configuration file using '-c' or supply ./rpminspect.yaml
```

**Comment by Jakuje** [comment]
ok, I got what the `rpminspect-data-fedora` and friends do, but still the readme should make it more explicit that we need a configuration file and use `rpminspect -c /usr/share/rpminspect/fedora.yaml` or use `rpminspect-fedora`.

**Comment by dcantrell** [comment]
You're right.  Fix coming.
