### ISSUE TITLE
[emptyrpm] Recognize python metapackages automatically

### ISSUE THREAD

**Issue by bookwar** [rpminspect/rpminspect#580]
From python maintainers:

Several Python packages have failures like this:
```
    1) New package python3-requests+security-2.25.1-5.el9.noarch.rpm is empty (no payloads)

    Result: VERIFY
    Waiver Authorization: Anyone

    Suggested Remedy:
    Check to see if you eliminated a subpackage but still have the %package and/or the %files section for it.


    2) New package python3-requests+socks-2.25.1-5.el9.noarch.rpm is empty (no payloads)

    Result: VERIFY
    Waiver Authorization: Anyone

    Suggested Remedy:
    Check to see if you eliminated a subpackage but still have the %package and/or the %files section for it.
```

Notice the `+` sign in the package names. These are Python extras subpackages [A] that bring in additional dependencies for extra functionality of a given Python package. They're supposed to be empty, they only carry metadata.
There is a lot of these packages in Fedora, and a lot of them has made it into RHEL9.

How about creating a new rpminspect rule that packages containing a `+` in the middle of their names (but not at the end) are ok to be empty? That way we could save a lot of maintainers from having to manually hardcode these subpackages into rpminspect.yaml files of each affected project.

[A] https://fedoraproject.org/wiki/Changes/PythonExtras

**Comment by dcantrell** [comment]
This is a reasonable request.  What I would prefer to do is implement this as a configuration file directive rather than embedding it in the source.  So the config file can carry a list of regular expressions to match "expected empty" RPMs.  That's in addition to the current list of package names (RPMTAG_NAME) that you can list as expected empty.

**Comment by torsava** [comment]
> This is a reasonable request. What I would prefer to do is implement this as a configuration file directive rather than embedding it in the source. So the config file can carry a list of regular expressions to match "expected empty" RPMs. That's in addition to the current list of package names (RPMTAG_NAME) that you can list as expected empty.

That sounds good, thanks, David! There is a goal to have packages pass rpminspect by mid-January, do you think this can be deployed in time?

**Comment by dcantrell** [comment]
> > This is a reasonable request. What I would prefer to do is implement this as a configuration file directive rather than embedding it in the source. So the config file can carry a list of regular expressions to match "expected empty" RPMs. That's in addition to the current list of package names (RPMTAG_NAME) that you can list as expected empty.
> 
> That sounds good, thanks, David! There is a goal to have packages pass rpminspect by mid-January, do you think this can be deployed in time?

I know, that goal was my idea.  :)

Yes, it should be deployed earlier than that.  I think I can get this implemented by the end of the week and then the next weekly update of the rpminspect runner for OSCI will pull in the latest build.  I will keep this issue updated with the status.

**Comment by torsava** [comment]
> I know, that goal was my idea. :)

I see 😃

> Yes, it should be deployed earlier than that. I think I can get this implemented by the end of the week and then the next weekly update of the rpminspect runner for OSCI will pull in the latest build. I will keep this issue updated with the status.

Awesome, thanks!

**Comment by hroncok** [comment]
Isn't this a dupe of https://github.com/rpminspect/rpminspect/issues/564 ? The packages are not empty.

**Comment by hroncok** [comment]
(If they were actually empty, that would be a bug that would need to be recognized.)

**Comment by torsava** [comment]
> Isn't this a dupe of #564 ? The packages are not empty.
> 
> (If they were actually empty, that would be a bug that would need to be recognized.)

Well, I disagree semantically: a haunted house is *empty* when the family moves out :) So to me, it's still an empty package. However, you're right, Miro, your detection mechanism is even better.

Can that fix be deployed in time?

**Comment by hroncok** [comment]
:ghost: :derelict_house: :joy: 

Just a note: the python extra subpacakges will either have ghosts only or ghost+manually added files -- both situations are OK.

**Comment by dcantrell** [comment]
Good point, @hroncok.  I can't even remember what things I have fixed or implemented.  :)

I just did this:

```
rpminspect-fedora -T emptyrpm python-requests-2.26.0-1.fc35
```

And got this output:

```
emptyrpm:
---------
1) New package python3-requests+security-2.26.0-1.fc35.noarch.rpm is empty (no payloads); this is expected because the package only contains %ghost entries 

Result: INFO
Waiver Authorization: Not Waivable



2) New package python3-requests+socks-2.26.0-1.fc35.noarch.rpm is empty (no payloads); this is expected because the package only contains %ghost entries 

Result: INFO
Waiver Authorization: Not Waivable
```

So rpminspect detects that these subpackages only have %ghost entries which means rpminspect should expected empty payloads.  Nothing to do here, it's already working.

Duplicate of #564
