### ISSUE TITLE
Make the comparisson work across different RHEL versions

### ISSUE THREAD

**Issue by hhorak** [rpminspect/rpminspect#587]
```
$ rpminspect-redhat libarchive-3.3.3-1.el8 libarchive-3.5.2-1.el9 
rpminspect: *** Unable to determine product release for 1.el8 and 1.el9
...
```

Despite this crashes now (reported separately as #586), it seems the tool does not like different RHEL versions in the comparison mode. This could be very beneficial when checking the ABI compatibility across RHEL releases as we try to maintain the compatibility across RHEL versions for some components (ACG level 1).

**Comment by dcantrell** [comment]
This is exactly supported in the program configuration file.  It's the favor_release setting, which by default is set to 'none' which means rpminspect expects the product release strings to match between the before and after builds.  You can set it to 'oldest' or 'newest' to favor one or the other.  Oldest or newest is determined based on a strverscmp() comparison of the before and after product release strings.

Favoring the newest seems like a good program default, so I think I will change that in the code and update the rpminspect-data packages too to reflect the default setting.

**Comment by dcantrell** [comment]
By favoring newest, your comparison between el8 and el9 would use the el9 rules from rpminspect-data-redhat.

**Comment by hhorak** [comment]
Thanks for a quick reply. Changing it to newest makes sense to me. If set to none, the message above can mention that this is possible to re-configure, so users having it configured to none are aware that this can be done.

**Comment by dcantrell** [comment]
I can modify the message text too.  Thanks for the suggestion.

**Comment by hhorak** [comment]
Wow, that was superfast, thanks a lot!
