### ISSUE TITLE
An ELF check for fortified calls should consult annobin for -D_FORTIFY_SOURCE

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#596]
<https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/70505/testReport/(root)/tests/_elf/> reports a regression in code fortification:

new build: miniz-2.2.0-4.fc36
old build: miniz-2.2.0-2.fc36 (found in f36-updates koji tag)
[...]
3) /usr/lib64/libminiz.so.0.2 may have lost -D_FORTIFY_SOURCE on x86_64

Result: BAD
Waiver Authorization: Security

Details:
Fortified symbols lost:
__memcpy_chk
__memset_chk
Fortifiable symbols present:
fread
memcpy
memset

I thought it was a regression in GCC 12, but I was explained <https://bugzilla.redhat.com/show_bug.cgi?id=2046432> that this is just an overzealous rpminspect. Actually rpminspect output reads:

Suggested Remedy:
Ensure all object files are compiled with '-O2 -D_FORTIFY_SOURCE=2', and that all appropriate headers are included (no implicit function declarations). Symbols may also appear as unfortified if the compiler is unable to determine the size of a buffer, which is not necessarily an error.

Florian Weimer suggested that rpminspect does not have to guess whether -D_FORTIFY_SOURCE=2 was lost or not. It can simply consult annobin annotations.

Hence I propose here an enhancement: This ELF check should check for -D_FORTIFY_SOURCE=2 in the annotations before raising a BAD status. This would help to diminish false negatives like this.

**Comment by fweimer-rh** [comment]
As annocheck is part of rpminspect already, maybe these legacy checks should simply be removed?

**Comment by dcantrell** [comment]
I think that's the appropriate thing to do here.  Since we're using annocheck, there's no need for the legacy checks.  All of that was inherited from stuff that rpmdiff did in a world where annocheck did not exist.

Thanks for the report and the explanation in the BZ too.
