### ISSUE TITLE
metadata inspection fails with VERIFY for trivial release-only changes

### ISSUE THREAD

**Issue by hroncok** [rpminspect/rpminspect#605]
In https://gitlab.com/redhat/centos-stream/rpms/python-pip/-/merge_requests/10 I see the metadata inspection fail with VERIFY with the following changes:

 - :warning: Changed 'Provides: platform-python-pip = 21.2.3-**5**.el9' to 'Provides: platform-python-pip = 21.2.3-**6**.el9' in subpackage python3-pip on noarch
 - :warning: Changed 'Provides: python-pip = 21.2.3-**5**.el9' to 'Provides: python-pip = 21.2.3-**6**.el9' in subpackage python3-pip on noarch
 - :warning: Changed 'Provides: python3.9-pip = 21.2.3-**5**.el9' to 'Provides: python3.9-pip = 21.2.3-**6**.el9' in subpackage python3-pip on noarch
 - :warning: Changed 'Conflicts: python-pip < 21.2.3-**5**.el9' to 'Conflicts: python-pip < 21.2.3-**6**.el9' in subpackage python3-pip on noarch
 - :warning: Changed 'Provides: python-pip-wheel = 21.2.3-**5**.el9' to 'Provides: python-pip-wheel = 21.2.3-**6**.el9' in subpackage python3-pip-wheel on noarch
 - :warning: Changed 'Provides: python-pip-wheel = 21.2.3-**5**.el9' to 'Provides: python-pip-wheel = 21.2.3-**6**.el9' in subpackage python3-pip-wheel on noarch
 - :warning: Changed 'Provides: python3.9-pip-wheel = 21.2.3-**5**.el9' to 'Provides: python3.9-pip-wheel = 21.2.3-**6**.el9' in subpackage python3-pip-wheel on noarch
 - :warning: Changed 'Obsoletes: python-pip-wheel < 21.2.3-**5**.el9' to 'Obsoletes: python-pip-wheel < 21.2.3-**6**.el9' in subpackage python3-pip-wheel on noarch

Would it please be possible not to report changed metadata where the only change is the embedded `%{?epoch:%{epoch}:}%{version}-%{release}`?

**Comment by dcantrell** [comment]
Definitely can fix this.  It should not be reporting those items as VERIFY because they are subpackages from the same SRPM.  This is a bug in how I make that determination.  Easy enough to fix, thanks for the report.

**Comment by hroncok** [comment]
On a related note:

:warning: Gained 'Recommends: (python3-tkinter(x86-64) = 3.9.10-2.el9 if tk(x86-64))' in subpackage python3-libs on x86_64
:arning: Lost 'Recommends: (python3-tkinter(x86-64) = 3.9.10-1.el9 if tk(x86-64))' in subpackage python3-libs on x86_64

This should be:

 1. Changed
 2. not a :warning:

**Comment by dcantrell** [comment]
Just confirmed the tkinter subpackage problem you're seeing is still there.  For my own purposes, can you file that as a new issue?

**Comment by hroncok** [comment]
Opened https://github.com/rpminspect/rpminspect/issues/617
