### ISSUE TITLE
rpminspect runs continuously inspecting openblas

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#607]
I'm not sure what's happening as it doesn't crash and the load changes, so it doesn't appear to be stuck per-se, but when inspecting openblas, it seems to get stuck somewhere. You can replicate this by running:

`rpminspect-fedora openblas-0.3.19-2.fc35`

**Comment by dcantrell** [comment]
Investigating this now.  It can't get past the annocheck inspection.  If you exclude that from the rpminspect run (-E annocheck), it finishes.  Digging in to this more.

**Comment by dcantrell** [comment]
Looks like the *.a libraries are causing a problem for annocheck.  If I create a local rpminspect.yaml and run rpminspect on an openblas build, it completes:

```
---
annocheck:
    ignore:
        - /usr/lib/*.a
        - /usr/lib64/*.a
```

I filed this upstream annocheck bug:  https://bugzilla.redhat.com/show_bug.cgi?id=2052047
