### ISSUE TITLE
Changed rich deps are not considered changed but gained+lost

### ISSUE THREAD

**Issue by hroncok** [rpminspect/rpminspect#617]
Followup from https://github.com/rpminspect/rpminspect/issues/605

:warning: Gained 'Recommends: (python3-tkinter(x86-64) = 3.9.10-2.el9 if tk(x86-64))' in subpackage python3-libs on x86_64
:warning: Lost 'Recommends: (python3-tkinter(x86-64) = 3.9.10-1.el9 if tk(x86-64))' in subpackage python3-libs on x86_64

This should be:

 1. a changed dependency, not a gained+lost one
 2. not a :warning: as the only thing that changed is the version-release

**Comment by hroncok** [comment]
I assume this is not detected as changed because the dependency is rich. But there might be other reasons.

I assume the thing that parses the dependency does not consider it as versioned because the version constraint is not at the end.

**Comment by dcantrell** [comment]
The rich dependency syntax is likely causing my issues here, I just need to ensure the rpmdeps inspection handles it.

**Comment by dcantrell** [comment]
I'm making progress on this one, but it's not done yet.

**Comment by dcantrell** [comment]
As of now this is resolved.  Rich dependency syntax is kind of a mess and librpm does not expose its parsing functions.  There's limited stuff I can do with it in rpminspect, so hopefully what you see now is sufficient.

**Comment by hroncok** [comment]
Thanks.
