### ISSUE TITLE
Add annocheck to rpminspect

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#62]
For details see:
https://pagure.io/fedora-ci/general/issue/78

**Comment by dcantrell** [comment]
I am looking at rpminspect's ancestor and seeing what it does with annocheck.  It currently does two executions of annocheck:

1) annocheck --skip-glibcxx-assertions --skip-stack-realign --ignore-unknown --enable-builtby FILE
2) annocheck --disable-hardened --enable-builtby --ignore-unknow FILE

It executes the first command with the after build file and parses the string output for the built-by information and for the Hardened: string.  If the Hardened: output lacks the substring "PASS", it reports that as a VERIFY noting annocheck warned about lacking hardened build options.

On the second execution, it runs on the before build and parses the output for the built-by information.  If the built-by information changes, it reports it as an INFO result and moves on.

Here is what I propose:
- rpminspect gain a new inspection called 'annocheck'
- Add a configuration setting for the annocheck options
- If the inspection runs against one build, it just performs the hardening check and reporting.
- If the inspection compares two builds, it performs both the hardening check and the built-by comparsion.

Thoughts?  This gains the additional hardening checks from annocheck, the built-by comparison (but do we care about that?), and allows the configuration file to carry the options for annocheck.  With that we can change how rpminspect invokes annocheck by editing the configuration file (which can also be extended on a per-package basis once rpminspect gains overlay configuration file functionality).
