### ISSUE TITLE
version of copr builds is incorrect

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#64]
Note that 0.10 version builds, which (except rawhide) is the latest version:

https://copr.fedorainfracloud.org/coprs/dcantrel/rpminspect/builds/

**Comment by dcantrell** [comment]
0.10 was a mistake that I accidentally pushed to github which then triggered a copr build.  I deleted the bogus tag from github but I guess I forgot about copr.  All old builds have been deleted on copr and new ones started.  Sorry for the confusion.
