### ISSUE TITLE
annocheck failing to identify some Rust exectuables as Rust executables on some architectures

### ISSUE THREAD

**Issue by mulkieran** [rpminspect/rpminspect#641]
Original issue was posted here: https://pagure.io/fedora-ci/general/issue/321

**Comment by dcantrell** [comment]
This is an annocheck bug.  Please open a bug for annocheck on bugzilla.redhat.com for this issue.  Thanks.

**Comment by mulkieran** [comment]
The rpminspect version is 1.9-0.1.202202102106git.fc36, which struck me as a little wierd, since the stratisd build is for f35.

**Comment by mulkieran** [comment]
Done: https://bugzilla.redhat.com/show_bug.cgi?id=2057737.

**Comment by dcantrell** [comment]
Thanks!
