### ISSUE TITLE
free(): invalid next size (fast)

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#65]
Hi David! Whenever I'm trying to run `rpminspect rhosp-director-images-16.0-20191122.1.el8ost` I get an `free(): invalid next size (fast)`
The output is next:
```
$ rpm -q rpminspect
rpminspect-0.9-0.1.201911201855git.fc29.x86_64
$ rpminspect -v rhosp-director-images-16.0-20191122.1.el8ost  
Downloading http:/...
...
-------------
Result: OK

free(): invalid next size (fast)
Aborted (core dumped)
$ echo $?
134
```

**Comment by dcantrell** [comment]
I am seeing a similar result for a local test I'm doing.  I will take a look at this today.

**Comment by dcantrell** [comment]
I just tried this with the most recent build from master and it's running fine.  I think I may have accidentally fixed this one while fixing another memory allocation bug.
