### ISSUE TITLE
No such file or directory errors

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#651]
In the current build, I am seeing errors such as:

```
rpminspect: chdir: No such file or directory
rpminspect: chdir: No such file or directory
rpminspect: chdir: No such file or directory
rpminspect: chdir: No such file or directory
rpminspect: chdir: No such file or directory
rpminspect: chdir: No such file or directory
rpminspect: chdir: No such file or directory

```

As well as:

```
rpminspect: mytmp/kernel-5.14.0.UkLjXD/after/noarch/kernel-abi-stablelists-5.14.0-68.el9.noarch//lib/modules/kabi-current/kabi_whitelist_aarch64: No such file or directory
```

I'm unsure if this has something to do with using the -w flag (in this case, it's run with -w mytmp), but worth noting. The fill command run to replace it:

`rpminspect-redhat -w mytmp -v -o out.txt kernel-5.14.0-66.el9 kernel-5.14.0-68.el9`

Using:
```
librpminspect-1.9-0.1.202202250208git.fc35.x86_64
rpminspect-1.9-0.1.202202250208git.fc35.x86_64
```

**Comment by jimbair** [comment]
Minor update: this is what I pulled from stderr while running my kernel test, which is basically 1.9 minus the last commit before tagging. The invalid argument was new, though the no such file error seems related to the same as before.

```
rpminspect: unable to read /home/jim/test/mytmp/kernel-5.14.0.iaR3Zr/changedfiles/symvers.gz.Ri1cq7: Invalid argument
rpminspect: unable to read /home/jim/test/mytmp/kernel-5.14.0.iaR3Zr/changedfiles/symvers.gz.1yfqsT: Invalid argument
rpminspect: /home/jim/test/mytmp/kernel-5.14.0.iaR3Zr/after/noarch/kernel-abi-stablelists-5.14.0-68.el9.noarch//lib/modules/kabi-current/kabi_whitelist_aarch64: No such file or directory
```

**Comment by dcantrell** [comment]
So the error about the kabi_whitelist_aarch64 is going to be a check in the kmidiff test.  I am probably assuming those always exist if I find one on one architecture.  So that's probably just another if statement.

The chdir errors are requiring a bit more digging, but are not impossible.  Since this is rearing its head with kernel build comparisons, it takes a while to get through it.

**Comment by dcantrell** [comment]
And the symvers.gz read error comes from the changedfiles inspection.  Just making notes for myself as I debug.

**Comment by dcantrell** [comment]
Fixed.
