### ISSUE TITLE
mremap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#67]
And one more:
```
rpminspect java-1.8.0-openj9-1.8.0.232.09.0.17.0-2.el8j9
mremap_chunk(): invalid pointer
Aborted (core dumped)
```
Thank you in advance!

**Comment by ukulekek** [comment]
Same for `microcode_ctl-20190618-1.20191115.2.el8_1`

**Comment by dcantrell** [comment]
Both working in the latest master build, likely fixed with the other memory allocation fixes I did today.
