### ISSUE TITLE
Cannot compare EUS builds

### ISSUE THREAD

**Issue by thrix** [rpminspect/rpminspect#68]
For example:
```
rpminspect  hwdata-0.314-8.2.el8_1 hwdata-0.314-8.3.el8 
```

**Comment by ukulekek** [comment]
Similar problem with:
```
rpminspect vhostmd-1.1-1.el8.1 vhostmd-1.1-2.el8
```

**Comment by thrix** [comment]
Another example:
```
rpminspect puppet-nova-15.4.1-0.20191125131858.ca70367.el8ost puppet-nova-15.4.1-0.20191101201933.890dc6f.el8
```

**Comment by dcantrell** [comment]
Working on this one now.

**Comment by dcantrell** [comment]
Ah ha...so here's the problem:

*** Builds have different product releases (el8_1 != el8)

rpminspect tries to figure out the product release by looking at the dist tag.  If these are different, it assumes you are comparing builds from two different products and gives you the message above.

In cases like this, you need to tell rpminspect the product release string.  Pass:

-r el8

To the rpminspect command and it will run.

**Comment by dcantrell** [comment]
OK, so different products under RHEL-8 will have different dist tags.  The default behavior of rpminspect is to match dist tags and if can't do that, you have to tell it the product release with the "-r" option.  My thought now is adding a second step in case the gathered dist tags don't match.  It would be product release strings in the config file mapped to a regexp to use, for example:

[products]
el8 = ^el8.*$

So any dist tag that begins with "el8" and contains zero or more characters after 'el8' will be treated as 'el8' for the purposes of rpminspect.  The order of determining the product release would then be:

1) The -r option, if specified.
2) Gathering the dist tag from the Release string as it does now.
3) If method 2 fails, iterate over the entries in the [products] for a match.  Stop when we have a match.

This will require maintenance of rpminspect.conf in the rpminspect-data package, but we're already doing that for everything else.

Thoughts?
