### ISSUE TITLE
RFE: Display storage used to fetch and unpack builds with -v

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#682]
As a follow-up to https://github.com/rpminspect/rpminspect/pull/676

It would be helpful for rpminspect to display this information when using -v inside of the "diagnostics" data. I could see this being useful for mass runs. Specifically, the data that would be helpful would be how much space the fetched builds take up, and then the space taken once unpacked. 

As a bonus, we could do fetched packages size / unpacked packages size / total of the two, though I think fetch size and total size is probably all we need. The bonus would be mostly influenced by how much effort it would take. Everyone loves more diagnostic data!

**Comment by dcantrell** [comment]
How do you want this to look in the output?
