### ISSUE TITLE
Builds have different product releases (el7 != el7)

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#70]
Hello, patch for https://github.com/rpminspect/rpminspect/issues/68 works fine, but now comparing packages with equal releases are broken.
Example:
```
$ rpminspect atomic-enterprise-service-catalog-4.4.0-201911252116.git.1.10a9adc.el7 atomic-enterprise-service-catalog-4.4.0-201911260323.git.1.04efd58.el7
*** Builds have different product releases (el7 != el7)
```

**Comment by ukulekek** [comment]
Another example:
`rpminspect  dhcp-4.3.6-34.el8 dhcp-4.3.6-39.el8`

**Comment by dcantrell** [comment]
Ooops, my mistake.  Fixed.
