### ISSUE TITLE
rpminspect may be choosing debuginfo files more or less arbitrarily when doing annocheck test

### ISSUE THREAD

**Issue by mulkieran** [rpminspect/rpminspect#703]
See https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/90229/testReport/(root)/tests/_annocheck/.

Also, stratisd specfile[1] will tell you what files should be using the stratisd-dracut debuginfo rpm and what should be using the stratisd debuginfo rpm.

As far as I can tell, the build process is creating the debuginfo rpms correctly.

See prior discussion in bz[2].

[1] https://src.fedoraproject.org/rpms/stratisd/blob/rawhide/f/stratisd.spec
[2] https://bugzilla.redhat.com/show_bug.cgi?id=2071463

**Comment by dcantrell** [comment]
It's not arbitrary, but it does assume that the debuginfo construction is left to rpmbuild.  It was only a matter of time before I had an example that demonstrated something else.  I'll get on this after a couple other pending fixes.  Thanks.

**Comment by dcantrell** [comment]
PR that addresses the debuginfo arg problem.  That appears to be correct now, though annocheck is at least failing for me but I am going to leave that to either annocheck expected behavior or a bug.
