### ISSUE TITLE
Huge elf results

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#71]
Elf produces a lot of duplicated strings in results. JSON results can be 15MB large or even more.
Example:
```
rpminspect mesa-19.1.4-2.el8 mesa-19.1.4-3.el8_1
```

**Comment by dcantrell** [comment]
Looks like the elfcmp results string is the reason here.  I can look into this one in more detail.

**Comment by dcantrell** [comment]
Further examination reveals that 'eu-elfcmp --verbose' is generating a ton of the same message over and over again.  The --help output says --verbose causes it to display all results, not just the first one.  But what I guess it's doing is showing the result for the first one for as many times as it found a problem.

I question the value of running eu-elfcmp still.  rpminspect's ancestor ran it, but with the annocheck inspection coming and the existing ELF checks already in librpminspect, eu-elfcmp seems to provide little additional value.

What I am going to do for now is remove --verbose and clean up the results reporting.  On the test with the mesa packages you mentioned, it went from 15M for the results to 44K.  We can decide later if we want to remove eu-elfcmp entirely from librpminspect.

**Comment by dcantrell** [comment]
Fix coming after I finish a couple test runs here.
