### ISSUE TITLE
abidiff failure even with samba.abignore

### ISSUE THREAD

**Issue by filipavel** [rpminspect/rpminspect#739]
I am trying to fix a failure reported here https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/98577/testReport/(root)/tests/_abidiff/ :

Details:
Command: abidiff /var/tmp/rpminspect/samba-4.16.1.KNxchl/before/i686/samba-libs-4.16.1-3.fc37.i686//usr/lib/libdcerpc-samr.so.0.0.1 /var/tmp/rpminspect/samba-4.16.1.KNxchl/after/i686/samba-libs-4.16.1-4.fc37.i686//usr/lib/libdcerpc-samr.so.0.0.1

abidiff: failed to read input file /var/tmp/rpminspect/samba-4.16.1.KNxchl/before/i686/samba-libs-4.16.1-3.fc37.i686//usr/lib/libdcerpc-samr.so.0.0.1
abidiff: could not find the debug info
abidiff: Maybe the root path to the debug information '' is wrong?
abidiff: Maybe you should consider using the --debug-info-dir2 option to tell me about the root directory of the debuginfo? (e.g, --debug-info-dir2 /usr/lib/debug)
abidiff: could not find the ELF symbols in the file '/var/tmp/rpminspect/samba-4.16.1.KNxchl/before/i686/samba-libs-4.16.1-3.fc37.i686//usr/lib/libdcerpc-samr.so.0.0.1'

I have created according to https://fedoraproject.org/wiki/How_to_filter_libabigail_reports file samba.ignore with:

1 #################################################                                                                                                                                                
2 # This is a grouping library without any code
3 #################################################
4 [suppress_file]
5 file_name_regexp=.*libdcerpc-samr\\\\.so.\*

But the issue remains....

**Comment by dcantrell** [comment]
So there are two things for this issue:

1. rpminspect looks for the abignore file in the SRPM.  I see that for samba it's just in dist-git and not in the SRPM itself.  The abignore file needs to be added to the spec file as SourceN: FILENAME so its included in the SRPM.

2. The default name of the abignore file is **.abignore**.  If you want rpminspect to find it under another name, you need to set this in the package rpminspect.yaml file:

```
abidiff:
    suppression_file: samba.abignore
```

I made these changes locally and ran the abidiff inspection on the samba package with rpminspect and it passed.

**Comment by cryptomilk** [comment]
Can you please improve the documentation at https://fedoraproject.org/wiki/How_to_filter_libabigail_reports

**Comment by filipavel** [comment]
With the proposed changes, abidiff works fine:

https://bodhi.fedoraproject.org/updates/FEDORA-2022-3233d2bf69

Thank you!

**Comment by dcantrell** [comment]
> With the proposed changes, abidiff works fine:
> 
> https://bodhi.fedoraproject.org/updates/FEDORA-2022-3233d2bf69
> 
> Thank you!

Great, glad that worked!

**Comment by dcantrell** [comment]
> Can you please improve the documentation at https://fedoraproject.org/wiki/How_to_filter_libabigail_reports

Sure, happy to add to that page.  I was not familiar with that page until this issue was opened, but it makes sense to also mention rpminspect there.
