### ISSUE TITLE
Unable to determine product release for (null) and (null)

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#76]
Hi!
When I run: 
```
rpminspect net-snmp-5.7.2-43.el7_7.3 net-snmp-5.7.2-43.el7_7.2
```
I got 
```
*** Unable to determine product release for (null) and (null)
```
I suppose the underscore is the reason of the error

**Comment by dcantrell** [comment]
With the latest rpminspect-data-redhat and rpminspect builds, that should work.  Let me see if I can figure out what's happening.

**Comment by dcantrell** [comment]
Two things here.  The key matching check in get_product_release() was not looking for the key correctly in the before and after strings.  The other problem were the regular expressions in the rpminspect.conf file.  Those needed to be a bit more explicit.  Fix coming in a few minutes.

**Comment by ukulekek** [comment]
Could you test it for this case as well?
```
rpminspect systemd-219-67.el7_7.3 systemd-219-67.el7_7.2
```

**Comment by dcantrell** [comment]
> systemd-219-67.el7_7.2

Works.  Make sure you get the latest rpminspect and rpminspect-data-redhat package from Copr.
