### ISSUE TITLE
Rpminspect unable to detect the right download link

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#77]
Hi!
Some builds are failed to tests because rpminspect trying to download sources from the wrong link. The files are exists but in other directories. 
Example: 
```
$ rpminspect lvm2-2.03.07-1.el8 lvm2-2.03.05-5.el8
*** Fopen() failed for /var/tmp/rpminspect/lvm2-2.03.05.5Yrki1/after/i686/device-mapper-event-libs-1.02.163-5.el8.i686.rpm: No such file or directory
*** error reading RPM: /var/tmp/rpminspect/lvm2-2.03.05.5Yrki1/after/i686/device-mapper-event-libs-1.02.163-5.el8.i686.rpm
*** error downloading build lvm2-2.03.05-5.el8
*** Failed to gather specified builds.
```
Some other examples with the same behaviour:
```
rpminspect atomic-openshift-3.11.157-1.git.0.dfe38da.el7 atomic-openshift-3.11.156-1.git.0.162dbb3.el7

rpminspect rh-dotnet31-dotnet-3.1.100-1.el7

rpminspect qt5-qtbase-5.12.5-4.el8 qt5-qtbase-5.12.5-3.el8
```

**Comment by dcantrell** [comment]
I see what's happening here.  The NVR of the subpackage is different for some packages.  In this case, device-mapper-events-libs.  The version of that package is 1.02.167 while the version of the lvm2-libs package is 2.03.07.  This is easy enough to fix.

**Comment by dcantrell** [comment]
Yep, fixed.  Pushing in just a sec.
