### ISSUE TITLE
archive_read_open_filename: Lzma library error: Corrupted input data: Success / format not recognized: Success

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#775]
While running rpminspect in comparison mode against linux-firmware-20210716-121.el9.1 /  linux-firmware-20220509-126.el9 in c9s-pending, we ran across the following errors:

```
logs/linux-firmware-20210716-121.el9.1-linux-firmware-20220509-126.el9-comparison.log.stderr:rpminspect: archive_read_open_filename: Lzma library error: Corrupted input data: Success
logs/linux-firmware-20210716-121.el9.1-linux-firmware-20220509-126.el9-comparison.log.stderr:rpminspect: archive_read_open_filename: Lzma library error: format not recognized: Success
```

The Corrupted input data error pops up 52 times, and the format not recognized pops up 2 times.

The command ran to create: 

`rpminspect-centos -s VERIFY -w mytmp -o logs/linux-firmware-20210716-121.el9.1-linux-firmware-20220509-126.el9-comparison.log linux-firmware-20210716-121.el9.1 linux-firmware-20220509-126.el9`

**Comment by dcantrell** [comment]
Well that is unpleasant.  Of course it has to be the hellscape that is the linux-firmware package that causes this bug to show up.
