### ISSUE TITLE
should "-T [inspection]" override the setting in the local configuration file?

### ISSUE THREAD

**Issue by dcantrell** [rpminspect/rpminspect#779]
If I have this in a local rpminspect.yaml file:

```
---
inspections:
    upstream: off
```

And then run rpminspect with `-T upstream`, it ignores the config file setting and runs it anyway.  I think this is correct because it lets you override the setting in data package configurations.  But what about local config files?

**Comment by jimbair** [comment]
I feel that the hierarchy should be the defaults, which are overridden by a -T option if specified and have conflicts, which are then overridden by a local rpminspect.yaml settings in the current working directly if it exists, with any conflicts.

Defaults > -T > local yaml (with inheritance)

**Comment by dcantrell** [comment]
I think it should be a slightly different order:

Defauklts -> config file read ins (main one, profile, then local rpminspect.yaml) -> command line

I think the command line option should always override the config file settings because that's a logical use case.  If I want to temporarily try something that I have disabled in the config file, I should be able to do that with the command line option.  But I am open to other interpretations.

**Comment by dcantrell** [comment]
No, wait, this doesn't make sense.  The command line option already overrides the config file settings.  In fact, that's what we want.  If you specify -T or -E and a list of inspections, rpminspect throws out the config file settings and just uses what you specify.  That's how it has to work.

Disregard this RFE.
