### ISSUE TITLE
RFE: Rpminspect  should know how to handle .spec files without SOURCE tag

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#78]
Some .spec files don't contain SOURCE tag. When we try to test it, rpminspect raise an error.
Example:
```
rpminspect rh-dotnet31-3.1-2.el7 rh-dotnet31-3.1-1.el7
*** unable to find RPMTAG_SOURCE for tmpnPUXxi/artifacts/rh-dotnet31-3.1.wXbYkp/after/src/rh-dotnet31-3.1-2.el7.src/rh-dotnet31.spec
```
I don't know, if it can be implemented, so it is the topic for discussion.

**Comment by dcantrell** [comment]
Oh this is an easy fix.  Coming right up.

**Comment by dcantrell** [comment]
Fixed.  Pushing change.
