### ISSUE TITLE
How to inspect modules locally?

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#798]
I found that rpminspect has "modularity" test. I supplied a modular package to rpminspect and it reported "Result: INFO". According to rpminspect sources it's because rpminspect does not recognize it is a modular package (buildtype). It only switches to modular build type after retrieving data from Koji. Can this be somehow locally overridden?

So I used "rpminspect -c /usr/share/rpminspect/redhat.yaml -d  php-7.4-8040020220622090235.d7c09045" on a RHEL 9.1 machine and got this error:

~~~~
rpminspect: XML-RPC Fault: Value of type INT supplied where string type was expected. (-501)
~~~~

I tried it from a Fedora 35 system for perl-DBI-1.643-3520220228164016.e12b6f3a and that passed. Is there a bug in handling Brew responses? "brew buildinfo php-7.4-8040020220622090235.d7c09045" works for me on that RHEL system.

Next, on Fedora it worked and reported "Result: OK" for  modularity. Fine. But redownloading everything from Koji takes time. I tried using --keep option to preserve the downloaded data:
~~~~
$ rpminspect -c /usr/share/rpminspect/fedora.yaml -a x86_64 -k -v -T modularity perl-DBI-1.643-3520220228164016.e12b6f3a
Downloading module perl-DBI-1.643-3520220228164016.e12b6f3a
[...]
modularity:
-----------
Result: OK
Waiver Authorization: Anyone
[...]
Keeping working directory: /var/tmp/rpminspect/perl-DBI-1.643.2Z8MYK
~~~~

and then pointed rpminspect to the temporary directory:

~~~~
$ rpminspect -c /usr/share/rpminspect/fedora.yaml -a x86_64 -k -v -T modularity /var/tmp/rpminspect/perl-DBI-1.643.2Z8MYK
rpminspect: Fopen failed for /var/tmp/rpminspect/perl-DBI-1.643.2Z8MYK/after/x86_64/perl-DBI-debuginfo-1.643-7.module_f35+13908+53d84a48.x86_64/usr/lib/debug/.build-id/76/6baf9b1dbc15964c8a42b77cdca3493f4ef334: No such file or directory
rpminspect: mkdir: File exists
Running modularity inspection...     pass
diagnostics:
------------
1) Version information for libraries and programs used by rpminspect.  This result is for informational
and diagnostic purposes only. 

Result: INFO
Waiver Authorization: Not Waivable
~~~~

How do I point rpminspect to a downloaded module? The error states that the file does not exist. A reason is that the file is a symlink which is broken:

~~~~
$ stat /var/tmp/rpminspect/perl-DBI-1.643.2Z8MYK/after/x86_64/perl-DBI-debuginfo-1.643-7.module_f35+13908+53d84a48.x86_64/usr/lib/debug/.build-id/76/6baf9b1dbc15964c8a42b77cdca3493f4ef334
  File: /var/tmp/rpminspect/perl-DBI-1.643.2Z8MYK/after/x86_64/perl-DBI-debuginfo-1.643-7.module_f35+13908+53d84a48.x86_64/usr/lib/debug/.build-id/76/6baf9b1dbc15964c8a42b77cdca3493f4ef334 -> ../../../.build-id/76/6baf9b1dbc15964c8a42b77cdca3493f4ef334
  Size: 60              Blocks: 8          IO Block: 4096   symbolic link
[...]
$ file -s  /var/tmp/rpminspect/perl-DBI-1.643.2Z8MYK/after/x86_64/perl-DBI-debuginfo-1.643-7.module_f35+13908+53d84a48.x86_64/usr/lib/debug/.build-id/76/6baf9b1dbc15964c8a42b77cdca3493f4ef334
/var/tmp/rpminspect/perl-DBI-1.643.2Z8MYK/after/x86_64/perl-DBI-debuginfo-1.643-7.module_f35+13908+53d84a48.x86_64/usr/lib/debug/.build-id/76/6baf9b1dbc15964c8a42b77cdca3493f4ef334: broken symbolic link to ../../../.build-id/76/6baf9b1dbc15964c8a42b77cdca3493f4ef334
~~~~

I think that's a bug. Or do I use rpminspect in a wrong way?

**Comment by dcantrell** [comment]
The modularity inspection is only triggered if the Koji build type is KOJI_BUILD_MODULE.  If it is, rpminspect will check to ensure each RPM in the module carries an RPMTAG_MODULARITY value.  But that's all it does.

Modularity support is limited in rpminspect and that's because I don't know where to find any information about talking to MBS or what constitutes a module or how to read the metadata.  All input to rpminspect has to come from a Koji download -or- local RPMs or Koji builds.  There is currently no way to explicitly tell rpminspect that a locally provided RPM or build subdirectory is a module, though I can see adding that as an RFE.  Certainly if I can get information on how to enable better or more complete modularity support in rpminspect.

I can see adding a command line option to note the Koji build type explicitly since you can supply local RPMs to rpminspect.  Should there be more for modularity support in rpminspect?  Happy to discuss this further.

**Comment by ppisar** [comment]
How to get to MBS: "koji buildinfo" returns a JSON document in Extra field. The JSON document contains module_build_service_id key whose value is an MBS build id. E.g. for perl-DBI-1.643-3520220228164016.e12b6f3a it's 13908. Then all details about that MBS build are available at <https://mbs.fedoraproject.org/module-build-service/2/module-builds/13908?verbose=1> URL.

However, I do not recommend using MBS because this is not what a user sees. User gets modules from Koji. Therefore your approach to use Koji is better.

I'd like to see additional tests for modules and modular packages in rpminspect. I have two very concrete tests at my mind. I will file a separate requests. (I wanted to send pull requests directly, but I hit this issue.)

Maybe the modularity tests could be split into two tests: module-level tests which require the module YAML file, and RPM-level tests which do not need the YAML file, can be run for an individual RPM package file, and are activated by modularitylabel RPM tag in the package (or an explicit rpminspect command line option).

**Comment by ppisar** [comment]
The two new tests: #801, #803.

**Comment by dcantrell** [comment]
The first thing I'm doing here is adding a command line option called -b or --build-type that lets you set the Koji build type explicitly.  For example, for locally cached module build directories, you can pass "-b module" to rpminspect and it will treat the inputs as module builds.  That should get it at least running the modularity inspection for now.

The next phase will be tied to the other issues and that is performing additional module-related checks based on the module metadata.
