### ISSUE TITLE
set_worksubdir: Assertion `task != NULL' failed.

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#80]
Hi!
Whenever I run:
```
rpminspect gcc-4.8.5-41.el7
```
I got
```
rpminspect: ../src/builds.c:95: set_worksubdir: Assertion `task != NULL' failed.
Aborted (core dumped)
```
The bug is present in `rpminspect-0.9-0.1.201912052120git.fc29.x86_64` and it works fine in `rpminspect-0.9-0.1.201912021802git.fc29.x86_64`

**Comment by ukulekek** [comment]
Same for
```
rpminspect java-1.8.0-ibm-1.8.0.6.0-2.el8 java-1.8.0-ibm-1.8.0.5.40-3.el8_0
```

**Comment by dcantrell** [comment]
Found it.  I would have fixed it earlier, but there was  FESCo meeting.  Patch coming after a local test.
