### ISSUE TITLE
Accept SPDX licenses in Fedora packages

### ISSUE THREAD

**Issue by ppisar** [rpminspect/rpminspect#818]
Fedora approved <https://pagure.io/fesco/issue/2799> a migration to SPDX license format in RPM License tags <https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1>.

It would be great if rpminspect accepted this SPDX format. The Fedora change mentions that rpminspect should use a list of approved licenses from fedora-license-data package <https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1#What_tools_validate_the_License_field?>.

perl-Text-Bidi-2.17-1.fc37 is the one of the first packages with SPDX identifiers and rpminspect naturally fails on it <https://osci-jenkins-1.ci.fedoraproject.org/job/fedora-ci/job/rpminspect-pipeline/job/master/110808/testReport/(root)/tests/_license/>:

~~~~
Result: BAD
1) Unapproved license in perl-Text-Bidi-2.17-1.fc37.i686: Artistic-1.0-Perl
~~~~

**Comment by dcantrell** [comment]
This is now present in the latest Copr builds of rpminspect and rpminspect-data-fedora.  The rpminspect-data-fedora package now requires fedora-license-data and specifies that licensedb for rpminspect to use.  Likewise you need the latest Copr build of rpminspect which supports explicit paths for the licensedb setting in the config file.

https://github.com/rpminspect/rpminspect-data-fedora/commit/5808a775670f2e9ac89a49d87eb5f73889bce91b

**Comment by ppisar** [comment]
Thanks for the quick resolution.
