### ISSUE TITLE
rpminspect: *** Unable to determine product release or none specified (-r).

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#819]
While running against some el8 builds, I ran across these two packages not being able to find their product release:

```
[jbair@awvr ~]$ rpminspect-redhat -s VERIFY -w mytmp -o logs/libmodulemd-2.13.0-1.el8.log libmodulemd-2.13.0-1.el8 
rpminspect: *** Unable to determine product release or none specified (-r).
[jbair@awvr ~]$ rpminspect-redhat -s VERIFY -w mytmp -o logs/subscription-manager-migration-data-2.0.51-1.log subscription-manager-migration-data-2.0.51-1 
rpminspect: *** Unable to determine product release or none specified (-r).
[jbair@awvr ~]$ 
```

I'm not sure if something changed on our side as this is a new one from the tag-runner side.

**Comment by jimbair** [comment]
Would this mean we have something like `rpminspect-centos9` vs `rpminspect-centos`? I suspect devs would sooner put in a dist tag vs a yaml config. Also, libmodulemd-2.13.0-1.el8 appears to have el8 in the name; was it also missing the dist tag?

**Comment by dcantrell** [comment]
No, there wouldn't be a new wrapper script.  What this would do is mean the rpminspect.yaml file you have in the RHEL 8.6 branch, for instance, would say "product_release: el8".  Since the runner will always pick up any rpminspect.yaml present, that's how rpminspect could know what product release to use when it can't infer it from the dist tag.  The user still runs the same thing, which would be ```rpminspect-VENDOR [opts]```

**Comment by jimbair** [comment]
This works; I'm not sure how many devs will use it in lieu of a dist tag, but tag-runner could use it as a part of the profile, which would solve missing dist tags in runs. Though even a --product-release flag in the CLI would also work, but in this case I think I could simply generate a yaml file in the CWD and fire off the tag-runner runs.

It's an edge case so I'm not overly worried about it.
