### ISSUE TITLE
Invalid License Tag

### ISSUE THREAD

**Issue by karelzak** [rpminspect/rpminspect#83]
util-linux spec file:
```
   License: GPLv2 and GPLv2+ and LGPLv2+ and BSD with advertising and Public Domain
```
rpminspect reaction:
```
Invalid License Tag in util-linux-2.32.1-19.el8.i686: GPLv2 and GPLv2+ and LGPLv2+ and BSD with advertising and Public Domain
```
Note that we use this License tag for years.

**Comment by dcantrell** [comment]
Each of those license short names is in fedora.json in the rpminspect-data-fedora package, which is where rpminspect gets license information.  Let me see what's going on.

**Comment by dcantrell** [comment]
Oh, it's "BSD with advertising" getting tokenized incorrectly.  Fixing this.
