### ISSUE TITLE
util-linux suids binaries reported

### ISSUE THREAD

**Issue by karelzak** [rpminspect/rpminspect#834]
Red Hat CI output
```
1) /usr/bin/mount in util-linux on aarch64 carries insecure mode 4755, Security Team review may be required
```
but it seems /usr/bin/mount is already in fileinfo list as suid. It reports the issue only on aarch64.

Additional info:
```
rpminspect version: 1.11-0.1.202207121758git3be9d73.el9 (with data package: 1.7-0.1.202207141735git7736552.el9)
rpminspect profile: rhel-8
new build: util-linux-2.32.1-37.el8
old build: util-linux-2.32.1-35.el8 (found in rhel-8.6.0-et-compose brew tag)
```

**Comment by dcantrell** [comment]
I am unable to reproduce this problem with the latest Copr build of rpminspect:

https://copr.fedorainfracloud.org/coprs/dcantrell/rpminspect/build/4636032/

If you are still seeing it, please open a new issue or reopen this one if that's possible.
