### ISSUE TITLE
rpminspect-redhat returns 2 when analysing a package

### ISSUE THREAD

**Issue by i386x** [rpminspect/rpminspect#843]
Hello, I started the `SuperLU` package analysis but after the packages were downloaded `rpminspect` exits with exit code 2 (also notice the difference between `rpminspect-redhat -V` and `rpm -q`):
```
$ rpminspect-redhat -vvv -ddd -T ALL SuperLU-5.2.0-7.el8
Downloading RPM build SuperLU-5.2.0-7.el8
...
debug: main (827): product_release=(null)

$ echo $?
2

$ rpminspect-redhat -V
rpminspect version 1.9

$ rpm -q rpminspect
rpminspect-1.10-1.fc35.x86_64
```

**Comment by i386x** [comment]
Adding `-r el8` fixes the problem, but maybe `-r` can be determined from the NVR?

**Comment by msrb** [comment]
rpminspect in Fedora is old. This issue is indeed reproducible with the older version that is the official Fedora repositories now, but the latest official COPR build works: https://copr.fedorainfracloud.org/coprs/dcantrell/rpminspect/

**Comment by dcantrell** [comment]
rpminspect-1.10 is also released and built as an update for Fedora 35, Fedora 36, Fedora 37, EPEL 7, EPEL 8, and EPEL 9.
