### ISSUE TITLE
Segmentation fault with machine-config-daemon

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#85]
Hello!
When I run
```
rpminspect -v machine-config-daemon-4.4.0-202001071423.git.1.f9e3b2b.el8 machine-config-daemon-4.4.0-202001070823.git.1.8124740.el8
```
I get
```
Downloading... (truncated output)
Downloading... (truncated output)
...
Segmentation fault (core dumped)
```
I have tried to run the rpminspect analysis for these packages separately - it worked fine and no error has occurred.
Thank you in advance!

**Comment by dcantrell** [comment]
Good find.  This was happening because the DT_NEEDED check was incorrectly running for ELF ET_EXEC files when it needs to only run for ELF ET_DYN types.  Fix coming.
