### ISSUE TITLE
RFE: Make the clamav dependency optional/weak

### ISSUE THREAD

**Issue by hroncok** [rpminspect/rpminspect#856]
When I install the rpminspect-data-fedora and rpminspect packages in Fedora, the huge clamav-data package (218 M) is required. I don't want to run virus checks locally. Please, make this dependency optional (e.g. Recommended). Thanks.

**Comment by dcantrell** [comment]
Reasonable

**Comment by hroncok** [comment]
librpminspect still requires clamav-lib which requires clamav-data :(
