### ISSUE TITLE
error: XML-RPC response too large.  Our limit is 524288 characters.  We got 1473813 characters.

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#864]
It seems like rpminspect is hitting some xmlrpc-c limits when dealing with bigger builds (glibc for example):

```
$ rpminspect-redhat glibc-2.34-28.el9_0.2
rpminspect: XML-RPC Fault: Unable to make sense of XML-RPC response from server.  XML-RPC response too large.  Our limit is 524288 characters.  We got 1473813 characters.  Use XMLRPC_TRACE_XML to see for yourself (-509)
```

This xmlrpc-c function might help us here:
http://xmlrpc-c.sourceforge.net/doc/libxmlrpc.html#limit_set

**Comment by dcantrell** [comment]
Yep, pretty easy to reproduce.  Working on a fix.
