### ISSUE TITLE
Support error messages in non-standard formats

### ISSUE THREAD

**Issue by jimbair** [rpminspect/rpminspect#877]
When trying to fetch a fonts build while only specifying the x86_64 arch, the inspection rightfully failed as there was no x86_64 build to be found (we needed to add noarch to get it working).

When doing this with `-F json`, the failure is silent minus the 255 exit code. Once stripping the format flag, the error popped up as expected.

This could simply go to stderr outside of the json (or other format) payload if desired, or sent into the payload as an error; whatever you think makes the most sense.

**Comment by dcantrell** [comment]
Can you give me an example command line that triggers this problem?

**Comment by jimbair** [comment]
The example I had from yesterday is 
` rpminspect-redhat -v -a x86_64 -F json -p rhel-6 -w mytmp -o logs/abyssinica-fonts-1.0-5.1.el6.log abyssinica-fonts-1.0-5.1.el6 `
