### ISSUE TITLE
Default temporary directory not honored

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#88]
Hi David,

I observed a change in rpminspect behavior recently breaking my rpminspect CI job. See the following output:

```
➜  ~ rpminspect -h
Usage: rpminspect [OPTIONS] [before build] [after build]
Options:
...
  -w PATH, --workdir=PATH  Temporary directory to use
                             (default: /var/tmp/rpminspect)
...

➜  ~ rpminspect -v -w /var/tmp/rpminspect -f nodepool-3.9.0-1.fc32 
Downloading https://kojipkgs.fedoraproject.org/packages/nodepool/3.9.0/1.fc32/noarch/nodepool-launcher-3.9.0-1.fc32.noarch.rpm...
...

Keeping working directory: /var/tmp/rpminspect/nodepool-3.9.0-1.fc32

➜  ~ rpminspect -v -f nodepool-3.9.0-1.fc32                        
Downloading https://kojipkgs.fedoraproject.org/packages/nodepool/3.9.0/1.fc32/noarch/nodepool-launcher-3.9.0-1.fc32.noarch.rpm...
...

Keeping working directory: /home/fabien/nodepool-3.9.0-1.fc32
➜  ~ rpminspect --version
rpminspect version @0.10@
```

W/o '-w' current user home directory is used instead of the default /var/tmp/rpminspect

**Comment by dcantrell** [comment]
This is deliberate when using the -f option.  The documentation could be improved.  When running "rpminspect -v -f" and specifying a build, most users told me they wanted the build downloaded to the current directory.  So when using -f, that's what happens now.  If you specify -w, you can override it even for -f.

This change went in to the code on Nov 20.

**Comment by morucci** [comment]
Ok, yes that make sense. I've fixed the playbook by specifying the -w. https://pagure.io/zuul-distro-jobs/pull-request/26#request_diff
The issue could be closed then.

**Comment by dcantrell** [comment]
Thanks.  Out of curiosity, what is the reason for directing downloads to /var/tmp/rpminspect?

**Comment by morucci** [comment]
I do a rpminspect between the current build of the pull-request and the previous build from related koji target. The build of the pull-request is done as scratch build on koji and I have some Ansible tasks that download from koji and prepare the cache in /var/tmp/rpminspect (like expected before by rpminspect). I could change the path used by the cache preparation's Ansible tasks for sure and use the home directory. By the way, is rpminspect able to fetch a build from a koji scratch build (this could simplify a lot the Ansible role I'm using) ?

**Comment by dcantrell** [comment]
Yes, rpminspect can fetch scratch builds.  Just give it the scratch build task ID number.
