### ISSUE TITLE
XML-RPC Fault: tag requires admin permission (1004)

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#881]
Koji/Brew can successfully build a package, but then fail to tag it -- maybe because the build was submitted too early and the tags are still locked. The result is that the build exists in Koji/Brew and it can be tagged later.
However, Koji/Brew will always show the original task as "failed", because the last step (tagging) failed.

rpminspect fails to process such failed tasks:

```
$ rpminspect-redhat  47538529
rpminspect: XML-RPC Fault: RPC failed at server.  tag requires admin permission (1004)
```
Note if the NVR is provided instead of Brew task id, everything works:
```
$ rpminspect-redhat -v gnome-online-accounts-3.28.2-4.el8
Downloading RPM build gnome-online-accounts-3.28.2-4.el8
=> gnome-online-accounts-3.28.2-4.el8.src.rpm   [####^C      
```

**Comment by dcantrell** [comment]
Definitely able to recreate it locally.  This is odd.  Might be a new thing with Koji.  Will try to dig in to this more and see what is happening.

**Comment by dcantrell** [comment]
OK, it's happening when rpminspect calls the Koji hub with getTaskResult via XML-RPC on task 47538750.  That fails and gives you the "tag requires admin permission (1004)".  If you go to the web interface for internal koji and look up that task ID, you will see "ActionNotAllowed: tag requires admin permission" in the Result field.

Looking at this further, I see the other tasks for this build are all for different architectures.  The failing one is for noarch.  That feels like an error.  Going to ask the Koji people for more information.

**Comment by dcantrell** [comment]
Filed upstream as https://pagure.io/koji/issue/3526

We'll wait to see if this is a Koji bug or if there's something to adjust in the XML-RPC communication.

**Comment by dcantrell** [comment]
OK, Koji team responded with details and what I should be doing is checking the task or build state and failing earlier if it's not done.  Here's what I get now when I try to test that task ID:

```
$ rpminspect-redhat 47538529
rpminspect: Koji task state is failed for task 47538529, cannot continue.
```

I also added something similar for Koji builds, so unless a build is successful, rpminspect will not try to fetch it.

**Comment by msrb** [comment]
Does this mean that developers will need to bump the release field and submit a new build to Koji?
