### ISSUE TITLE
Javabytecode generate 6 million results

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#89]
Hello!
When I run
```
rpminspect java-1.8.0-openjdk-1.8.0.242.b05-0.1.ea.el7
```
I get six million results like that https://url.corp.redhat.com/622ae10.  Should be the test so strict? Or should it generate a result for every class in a file? What do you think about reducing the results to one for every file?

**Comment by dcantrell** [comment]
That is a lot of results.  My first question is whether or not 50 is the correct Java bytecode version for el7.  Should it be 52?  If 50 is correct, then I think the test needs to be a <= and not ==.  Do you know of a way to verify what the Java major bytecode version for el7 should be?

**Comment by ukulekek** [comment]
I'm afraid I don't know

**Comment by dcantrell** [comment]
Looking in to this more, the JVM major version number for OpenJDK 8 is 0x52.  But EL7 contains multiple JDK packages.  I think this test needs some adjustments because these errors should not be there.  Working on it a bit more.

**Comment by dcantrell** [comment]
I adjusted the test but now I get 3893 results where the byte code version in the packaged file in the jar is 45 but el7 has a minimum requirement of 50.  I think the test adjustment is correct, now I'm just digging in to why it's picking up the wrong JVM version.

**Comment by dcantrell** [comment]
I have some of the offending class files opened in a hex editor and I can see at byte offset these files say 0x2D which is 45 in decimal, which is the JDK 1.1 major number.  So rpminspect is finding the right value.  The question now is whether or not this is a legitmate error or an exception.  I am going to email the person who built that package to see what the story is.  If this is an exception, then this is a reason to implement an ignore path mechanism in rpminspect (which I knew we would need, but now might be the time).

**Comment by dcantrell** [comment]
Based on Andrew's feedback, it looks like rpminspect was doing the correct thing but had the wrong major version for one product release.

The key thing is that the javabytecode inspection should not be run for JDK packages.  Only packages that need a JDK or JRE.  I am working on adding support to the config file to allow runtime selection of inspections (similar to the -T and -E options) as well as per-package config files.  We will need that to skip the JDK packages properly.

**Comment by dcantrell** [comment]
I have updated the inspection code in librpminspect in the previous commits.  I've also updated javabytecode section in the rpminspect.conf file in rpminspect-data-fedora to carry the correct JVM major versions.

However, per Andrew's comments, the javabytecode inspection should not be run on the openjdk package.  I think the easiest way to handle that is add a profile to rpminspect-data-fedora called openjdk that just turns off that exception.  The profile code will also expand to support a .rpminspectrc file in the current directory.  We can drop those in dist-git repos and let packages define specifics.  So maybe at that point the openjdk package could carry a .rpminspectrc file that does:

```
[inspections]
javabytecode = off
```

For now we can add a profile to rpminspect-data-fedora.  If you want to send me a pull request to do that, please do.  If not, let me know and I can add it.
