### ISSUE TITLE
Invalid filename in the stat-whitelist

### ISSUE THREAD

**Issue by ukulekek** [rpminspect/rpminspect#90]
Hello!
When I run one of these commands:
```
rpminspect bind-9.11.13-2.el8 bind-9.11.12-4.el8
rpminspect s390utils-2.6.0-26.el8 s390utils-2.6.0-24.el8
rpminspect dotnet3.0-3.0.102-2.el8_1 dotnet3.0-3.0.100-1.el8
```
I get 
```
*** Invalid filename in the stat-whitelist: -rwsr-x---
*** From this invalid line:
***     root	disk	/usr/lib64/amanda/application/amgtar
munmap_chunk(): invalid pointer
Aborted (core dumped)
```

**Comment by dcantrell** [comment]
Can you tell me what versions of rpminspect and rpminspect-data-redhat you have installed?  And where are you running it?  Workstation or a VM?  How is the system configured?

**Comment by ukulekek** [comment]
I use rpminspect-0.10-0.1.202001071902git.fc29.x86_64 and rpminspect-data-redhat-0.9-0.1.201912181635git.fc29.noarch. I run it within a docker container [1] running in VM provisioned by openstack. The used OS is fedora 31. I have tried to run the container on my workstation (also fedora 31) - the result is the same.

[1]: https://url.corp.redhat.com/c07597e

**Comment by ukulekek** [comment]
Just get the same behaviour with rpminspect-0.10-0.1.202001172048git.fc29.x86_64 and rpminspect-data-redhat-0.9-0.1.202001162036git.fc29.noarch. The system configuration is the same.

**Comment by dcantrell** [comment]
Got it.  I was finally able to reproduce it locally.  Working on it now.

**Comment by dcantrell** [comment]
Fixed.
