### ISSUE TITLE
abidiff inspection failure when comparing lua builds

### ISSUE THREAD

**Issue by dcantrell** [rpminspect/rpminspect#918]
[...]
abidiff: failed to read input file
/var/tmp/rpminspect/lua-5.4.2.ekzinB/before/aarch64/lua-libs-5.4.2-4.el9.aarch64//usr/lib64/liblua-5.3.so
abidiff: could not find the alternate debug info file at: ../../.dwz/lua-5.4.2-4.el9.aarch64
[...]

Before build: lua-5.4.2-4.el9
After build: lua-5.4.2-4.el9_0.2

**Comment by Jakuje** [comment]
Seems like I am affected by this too with the libgcrypt build from today in CI:
```
rpminspect version: 1.11-0.1.202210201537git704521f.el9 (with data package: 1.7-0.1.202210191719git0f85195.el9)
rpminspect profile: none
new build: libgcrypt-1.10.0-8.el9_0
old build: libgcrypt-1.10.0-5.el9_0 (found in rhel-9.0.0-z brew tag)
```
Reproducer is
```
$ rpminspect-redhat -T abidiff libgcrypt-1.10.0-5.el9_0 libgcrypt-1.10.0-8.el9_0
```
Given that the changes are minimal, I am going to waive the check and reference this issue.

**Comment by dmnks** [comment]
Can confirm the same, this is apparently not Lua-specific as I'm also seeing this now with RPM itself:

```
abidiff: failed to read input file /var/tmp/rpminspect/rpm-4.16.1.3.qBzyk3/before/aarch64/rpm-plugin-ima-4.16.1.3-12.el9_0.aarch64//usr/lib64/rpm-plugins/ima.so
abidiff: could not find the alternate debug info file at: ../../../.dwz/rpm-4.16.1.3-12.el9_0.aarch64

```
