### ISSUE TITLE
RFE: show local rpminspect.yaml in diagnostics inspection

### ISSUE THREAD

**Issue by msrb** [rpminspect/rpminspect#925]
It might be beneficial to have the content of the local (component-specific) rpminspect.yaml shown in the diagnostics inspection output. This feature would make it easier to check the custom configuration that was used to produce the rpminspect result.

cc @dcantrell @jimbair @martinpitt

**Comment by msrb** [comment]
I've been thinking about this more as well. I think we could start simple.

This RFE is based on the request from QE in OSCI-3997. It specifically asks for the user configuration to be visible as QE may want to double check what inspections were skipped or which files were excluded by developers.
Therefore I think printing the content of the user's local rpminspect.yaml in the diagnostics inspection should be enough (at least for now (?)).

WDYT?

**Comment by dcantrell** [comment]
Yeah, that feels like the easiest approach.  I will add support for printing the local rpminspect.yaml (or json or dson!) in the diagnostics section.
