### ISSUE TITLE
Incorrect desktop file error relating to icons

### ISSUE THREAD

**Issue by natoscott** [rpminspect/rpminspect#95]
In gating/ci tests for the pcp package, I'm seeing this failure:

```Desktop file /usr/share/applications/pmchart.desktop on i686 references icon pmchart but no subpackages contain pmchart
```

The pcp sub-package named pcp-gui contains both the /usr/bin/pmchart binary and the (many) icon files of various forms (i.e. all are in the one rpm - pcp-gui - which is an artifact of the build under test).  

The desktop application file is correct according to the desktop docs, and the icons are rendered correctly in the desktop when the tool is actually used, so I believe this is a false failure...?

**Comment by dcantrell** [comment]
In that subpackage I see /usr/share/pcp-gui/pixmaps/pmchart.png.  Is that the icon file?  If so, that would be the source of the problem.  Let me clarify.

The desktop inspection is based on the same-named test in rpmdiff.  I'm not an expert on the specifics of each thing we deliver, so I start with what I see rpmdiff doing and (a) fix obvious wrong things and (b) wait for feedback like this to further refine it.  So thank you!

If you can confirm the file above is the icon file, I am going to look in to how the desktop files are processed and make sure rpminspect is using the same icon path and/or method for finding icons.  The rpmdiff test looked exclusively in /usr/share/icons.

**Comment by dcantrell** [comment]
OK, I think this is what I need to do.  Implement the same icon lookup algorithm:
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

I thought that I could rely on desktop-file-validate for that, but I think that's just a style checker.  This should be easy enough to do.  I'll continue on this and post here with updates.

**Comment by natoscott** [comment]
@dcantrell thanks!  Happy to help test things here - lemme know if you need anything.

**Comment by dcantrell** [comment]
I've modified the desktop test to perform the icon finding algorithm as noted here:
https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#icon_lookup

rpminspect is more simple in that it just looks for a file that matches the name and has any extension.  I feel if I don't do that then I will be chasing the list of valid extensions forever.

Here's what I get on my most recent run:

`[dcantrel@awvr rpminspect]$ rpminspect -T desktop pcp-5.0.2-4.el8
desktop-entry-files:
--------------------
Result: OK`

Going to push this soon.  Let me know if you run in to any more problems.
