### ISSUE TITLE
rpminspect SIGSEGV on microdnf in annocheck inspection

### ISSUE THREAD

**Issue by dcantrell** [rpminspect/rpminspect#965]
```
$ rpminspect-redhat microdnf-3.9.1-2.el9
rpminspect: libannocheck_init error: version number too small
/usr/bin/rpminspect-redhat: line 2: 166032 Segmentation fault      (core dumped) /usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml $*
```

**Comment by msrb** [comment]
```
$ rpm -qa |grep rpminspect
rpminspect-data-centos-1.2-0.1.202210241900git6f9d334.fc37.noarch
rpminspect-data-fedora-1.10-0.1.202210271518git4429e19.fc37.noarch
rpminspect-data-redhat-1.7-0.1.202211071626git69ef2e6.fc37.noarch
librpminspect-1.11-0.1.202211231559git683d045.fc37.x86_64
rpminspect-1.11-0.1.202211231559git683d045.fc37.x86_64

$ rpm -q annobin-annocheck
annobin-annocheck-10.93-1.fc37.x86_64
```

@dcantrell Would it be possible to prioritize this bug please? We cannot easily rebuild the container without updating dependencies and thus breaking rpminspect in CI. Note the problem is not specific to microdnf, it affects other components as well:
```
$ rpminspect-redhat sscg-3.0.0-7.el9
rpminspect: libannocheck_init error: version number too small
/usr/bin/rpminspect-redhat: line 2: 383506 Segmentation fault      (core dumped) /usr/bin/rpminspect -c /usr/share/rpminspect/redhat.yaml $*
```

**Comment by martinpitt** [comment]
@dcantrell : Unfortunately the [1116 build](https://download.copr.fedorainfracloud.org/results/dcantrell/rpminspect/fedora-36-x86_64/05043479-rpminspect/) lost its binaries, presumably because it hasn't been current for more than two weeks. I tried to use that in https://github.com/fedora-ci/rpminspect-runner/pull/83. The current build was the [1123 one](https://copr.fedorainfracloud.org/coprs/dcantrell/rpminspect/build/5062315/) until yesterday.

**Comment by martinpitt** [comment]
FTR, I tried the latest 1.11-0.1.202212091747git65a52f9 build, and it still crashes the same way.

**Comment by dcantrell** [comment]
OK, I have verified what I thought the problem was.  It's a libannocheck bug that I have reported upstream.  For now I will be defaulting rpminspect back to the /usr/bin/annocheck method for that inspection.

The issue is the libannocheck_init() function which you have to call before using the library.  The first parameter is LIBANNOCHECK_VERSION which is defined in libannocheck.h.  In the code the init function checks if that first parameter is < LIBANNOCHECK_VERSION and if so errors out saying the version is too small.  What this is effectively reporting is that you are trying to run an rpminspect executable built with an older version of libannocheck.  So if Copr builds against libannocheck 10.92 and then an update to 10.93 is made, rpminspect has to be rebuilt as well.  This is unnecessary and I've asked upstream to refactor the init code so we can have an API version or something.
