### ISSUE TITLE
Curious error "Missing license database"

### ISSUE THREAD

**Issue by morucci** [rpminspect/rpminspect#97]
Hi David,

On this run https://fedora.softwarefactory-project.io/logs/21/21/3e8bec4cf2b5a09065f5eac89ccdfbd91081382d/check/rpm-rpminspect/dc5c0ae/rpminspect.html
the license checking is failing due to "Missing license database". But I see the required packages installed on the system: rpminspect-data-fedora (here is the log of package installation: https://fedora.softwarefactory-project.io/logs/21/21/3e8bec4cf2b5a09065f5eac89ccdfbd91081382d/check/rpm-rpminspect/dc5c0ae/ara-report/result/0c0ce227-982f-43fb-aff5-9f3765e67fcb/)

Do you have an idea what could happen here ?
Thanks in advance for your feedback

Fabien

**Comment by dcantrell** [comment]
I can't tell what builds were compared here.  What command was run?

**Comment by morucci** [comment]
Right, some information are missing. Here is the packages list that will be compared: https://fedora.softwarefactory-project.io/zuul/build/dc5c0aed81ec4e44b83582dc76ff74c2/log/job-output.txt#349

And here is the command: https://fedora.softwarefactory-project.io/logs/21/21/3e8bec4cf2b5a09065f5eac89ccdfbd91081382d/check/rpm-rpminspect/dc5c0ae/ara-report/result/a863aeb7-e6f1-4c41-b099-357474915f67/

**Comment by dcantrell** [comment]
I am unable to find the python39-3.9.0~a3-2.fc32 build.  I have performed a local rpminspect run with:

python39-3.9.0~a2-1.fc32
python39-3.9.0~a3-1.fc32

I don't get an error about missing the license database.  Make sure you have rpminspect-data-fedora installed where rpminspect is running.  If you're using rpminspect from my Copr repo, make sure to also use rpminspect-data-fedora from that repo.
