### ISSUE TITLE
I think the symlinks test is wrong.

### ISSUE THREAD

**Issue by halfline** [rpminspect/rpminspect#978]
**Describe the bug**
I have a symlinks test VERIFY report of the form

```
regular file /usr/share/help/pl/gnome-logs/media/gnome-logs-3-34.png became a symbolic link (to /usr/share/help/pl/gnome-logs/media/gnome-logs-3-34.png) in gnome-logs on aarch64
```

It's fine that I need to verify the symlinks manually, but I think the part in the parenthesis (to ...) is incorrect.  It looks like it's repeating the from, instead of displaying the to.

**Comment by dcantrell** [comment]
Yep, you're right.  I'll get this fixed up.  Thanks!

I had high hopes about 2 years ago of people reporting stuff like this so I didn't really triple check all of the reported strings and, well, here we are.
