### ISSUE TITLE
RFE: Add visible info about tested NVR above the rpminspect table

### ISSUE THREAD

**Issue by kkaarreell** [rpminspect/rpminspect#982]
**Is your feature request related to a problem? Please describe.**

When I open multiple rpminspect results in different tabs, it is not visible to which NVR particular tab/results applies to.

**Describe the solution you'd like**
Please, add visible information about the NVR of a tested package and build URL (e.g. brew link) to the html report, 
ideally somewhere above the table so it can be seen all the time.

**Describe alternatives you've considered**
Expand diagnostics section and find the info in the cmdline example but this is quite user unfriendly.

**Comment by dcantrell** [comment]
@martinpitt what do you think about this change?

**Comment by martinpitt** [comment]
@dcantrell : That'd be nice indeed! The currently produced [results.json](https://artifacts.dev.testing-farm.io/35391ab7-e604-4fc7-bd57-eae9e07b1e96/work-rpminspectr_sw3azw/rpminspect/execute/data/rpminspect/data/result.json) does not actually have the tested NVRs in machine readable form (parsing diagnostics and trying to fish them out from the command line is too brittle IMHO).

Could this grow something like `.diagnostics[0].packages` or `._info.packages` with a list of NVRs? Then it's straightforward to show that in the viewer.

**Comment by kkaarreell** [comment]
I didn't realized it sooner but it would be necessary also to see an information about the NVR baseline used.

**Comment by dcantrell** [comment]
> @dcantrell : That'd be nice indeed! The currently produced [results.json](https://artifacts.dev.testing-farm.io/35391ab7-e604-4fc7-bd57-eae9e07b1e96/work-rpminspectr_sw3azw/rpminspect/execute/data/rpminspect/data/result.json) does not actually have the tested NVRs in machine readable form (parsing diagnostics and trying to fish them out from the command line is too brittle IMHO).
> 
> Could this grow something like `.diagnostics[0].packages` or `._info.packages` with a list of NVRs? Then it's straightforward to show that in the viewer.

Yeah, I can do that.
