### ISSUE TITLE
rpmdeps reports missing epoch for dep with explicit epoch

### ISSUE THREAD

**Issue by notroj** [rpminspect/rpminspect#984]
**Describe the bug**
rpmdeps is reporting a missing epoch for a dependency which has an explicit epoch and is displayed with an explicit epoch in the error message:

`Missing epoch prefix on the version-release in 'Requires: httpd-core = 0:2.4.54-9.fc38' for mod_proxy_html on i686`

**To Reproduce**
```
/usr/bin/rpminspect -c /usr/share/rpminspect/fedora.yaml --workdir /var/ARTIFACTS/work-rpminspectprhh6lw7/rpminspect/discover/default-0/tests/workdir/ --format=json --output=/var/ARTIFACTS/work-rpminspectprhh6lw7/rpminspect/execute/data/rpminspect/data/result.json --verbose --release=fc38 --profile=rawhide httpd-2.4.54-6.fc38 95557571
```

**Expected behavior**
Either the real error is something more subtle than a missing epoch and is reported badly - or the report is a false positive?

**Environment:**
 - Fedora rawhide i686

**Comment by dcantrell** [comment]
The problem here is rpminspect is not handling cases where you have an Epoch > 0 on a subpackage but not the main package.  I see httpd is doing that.  This should not be too difficult to fix up.

**Comment by notroj** [comment]
Awesome, thanks David.
