### ISSUE TITLE
abidiff doesn't finish on GCC buids and breaks OSCI

### ISSUE THREAD

**Issue by vkadlcik** [rpminspect/rpminspect#987]
**Describe the bug**
rpminspect dies on GCC el9 builds in OSCI, I have to run it manually outside of OSCI. That way I have to run it "per partes" to avoid abidiff. The abidiff sub-test seems to never finish (my last attempt is 12 hours and still running).

**To Reproduce**
OLD_NVR=_some-newish-el9-build_
NEW_NVR=_another-newish-el9-build_
rpminspect-redhat -f $OLD_NVR $NEW_NVR
rpminspect-redhat -T abidiff -v $OLD_NVR $NEW_NVR

**Expected behavior**
abidiff finishes in reasonable time, rpminspect provides results to OSCI

**Environment:**
 - x86_64, any el8 or el9 compose or release; use e.g. 9.1 (oh, and it SIGSEGVs on my fedora 36 notebook but let's leave it out of scope)

**Comment by dcantrell** [comment]
There have been some recent issues reported with the abidiff inspection and abidiff taking a long time.  This was showing up shortly before the company shutdown.  There was a new release of libabigail and that addressed some problems, but there may be more at play here.

I'm going to have to do some more debugging here to get more details on slowdowns.  Before the shutdown there was also talk of what files the abidiff inspection should skip, so there may be some work to do there.

**Comment by dodjiseketeli** [comment]
Hello,

This issue should hopefully be fixed by libabigail 2.3.  Here is a log of an abidiff inspection with that version of libabigail:
https://people.redhat.com/dseketel/paste/cant-replicate-issue-with-abidiff-2.3.txt.
