### ISSUE TITLE
CI Zuul pipeline fails, while locally it runs OK

### ISSUE THREAD

**Issue by Andrei-Stepanov** [rpminspect/rpminspect#989]
**Describe the bug**
CI pipeline on ZUUL fails with:

```
Running shellsyntax inspection...    pass
rpminspect: ../lib/runcmd.c:56: run_cmd_vpe: Assertion `argv != NULL' failed.
/usr/bin/rpminspect-centos: line 2:  9456 Aborted                 (core dumped) /usr/bin/rpminspect -c /usr/share/rpminspect/centos.yaml $*
```

**To Reproduce**
I cannot reproduce on F37 and F35:
Command I use:

```
rpminspect-centos -Dv -k -t VERIFY --profile=centos-stream-9-devel -w /data/rpminspect -a x86_64,noarch,src -o /root/result.json -F json /data/rpminspect/libssh-0.10.4-6.el9
```

**Environment:**

https://centos.softwarefactory-project.io/logs/18/18/ca6ea525bad0a23649dad33e683749bbd6b45c86/check/rpm-rpminspect/7e7e470/job-output.txt

ctrl-f: for  `core dumped`

**Comment by Andrei-Stepanov** [comment]
```
rpm -qa | grep rpminsp
librpminspect-1.11-0.1.202212211657gite6c741f.fc35.x86_64
rpminspect-1.11-0.1.202212211657gite6c741f.fc35.x86_64
rpminspect-data-centos-1.2-0.1.202210241900git6f9d334.fc35.noarch
```

```
rpm -qa | grep rpmi
librpminspect-1.11-0.1.202212211657gite6c741f.fc37.x86_64
rpminspect-1.11-0.1.202212211657gite6c741f.fc37.x86_64
rpminspect-data-centos-1.2-0.1.202210241900git6f9d334.fc37.noarch
```

**Comment by msrb** [comment]
Was this some recent rpminspect run in CI?
Because the same (or similar) issue was fixed just recently:

**Comment by Andrei-Stepanov** [comment]
https://gitlab.com/redhat/centos-stream/rpms/libssh/-/merge_requests/18
started Dec 21, 2022 3:31pm GMT+0100

**Comment by msrb** [comment]
Ah, yeah, I think it's the same problem. "recheck" from yesterday is green there.

**Comment by dcantrell** [comment]
Alright, thanks for the followup.  I'll close this issue.
