### ISSUE TITLE
Global ignore list in rpminspect.yaml can suppress security sensitive findings

### ISSUE THREAD

**Issue by thoger** [rpminspect/rpminspect#995]
**Describe the bug**
Certain problems detected by rpminspect are marked as WAIVABLE_BY_SECURITY and are not meant to be suppressed via the $CWD/rpminspect.yaml configuration, but require entry in the central security policy file.  In terms of the rpminspect implementation, this seems to translate into rpminspect not ignoring these results for files listed in the inspection-specific ignore list.  However, seems this can be avoided by adding relevant files to the global ignore list instead.

**To Reproduce**
Modify the fileinfo allow list that will be used by rpminspect, such as /usr/share/rpminspect/fileinfo/fc37 from rpminspect-data-fedora, to remove or comment out entry for /usr/bin/chage.

Run rpminspect on the shadow-utils rpm with the permissions inspection enabled:

```
$ rpminspect-fedora -T permissions -r fc37 shadow-utils-4.12.3-4.fc37.x86_64.rpm
...
permissions:
------------
1) /usr/bin/chage in shadow-utils on x86_64 carries insecure mode 4755, Security Team review may be required 

Result: BAD
Waiver Authorization: Security


2) /usr/bin/gpasswd in shadow-utils on x86_64 carries expected mode 4755 

Result: INFO
Waiver Authorization: Not Waivable


3) /usr/bin/newgrp in shadow-utils on x86_64 carries expected mode 4755 

Result: INFO
Waiver Authorization: Not Waivable
...
```

Attempt to suppress this finding with this rpminspect.yaml:

```
$ cat rpminspect.yaml 
permissions:
    ignore:
    - /usr/bin/chage
```

Re-run rpminspect and see the same results are before.  This is expected.

Now change the rpminspect.yaml to:

```
$ cat rpminspect.yaml 
ignore:
    - /usr/bin/chage
```

The output after re-running rpminspect is:

```
permissions:
------------
1) /usr/bin/gpasswd in shadow-utils on x86_64 carries expected mode 4755 

Result: INFO
Waiver Authorization: Not Waivable


2) /usr/bin/newgrp in shadow-utils on x86_64 carries expected mode 4755 

Result: INFO
Waiver Authorization: Not Waivable
```

chage is no longer mentioned in the report.

**Expected behavior**
$CWD/rpminspect.yaml should not be allowed to suppress WAIVABLE_BY_SECURITY finding.

**Comment by dcantrell** [comment]
I've got a series of patches coming that ensure the per-inspection and global ignore lists are skipped for any check that can generate a WAIVABLE_BY_SECURITY result.  The only way to deal with those will be to add rules to the vendor data package via a pull request to the appropriate project (e.g., rpminspect-data-fedora or rpminspect-data-centos).
