### ISSUE TITLE
Unicode test failures can not be controlled via the system security policy file

### ISSUE THREAD

**Issue by thoger** [rpminspect/rpminspect#996]
**Describe the bug**
The unicode inspection can produce findings marked as WAIVABLE_BY_SECURITY.  Suppression of such findings is meant to be done via one of the system files (e.g. inspection-specific allow lists such as fileinfo or capabilities), or via the central security policy file.  There is no allow list for unicode, or support for it in the security policy file.

Note that it currently is possible to suppress unicode failure via $CWD/rpminspect.yaml file, which is - as far as I understand - not expected for WAIVABLE_BY_SECURITY findings.

It should also be noted that this inspection needs to be applied to sources / source rpms rather than binary rpms, which also means any sort of allow or ignore list need to properly support file paths inside expanded source tree without any rpminspect implementation-specific prefix (such as unpack-XXXXXXX).  It should also be reviewed how other configuration settings for the unicode inspection (exclude, excluded_mime_types, forbidden_codepoints) should be handled when coming from rpminspect.yaml, as those settings should also be able to suppress findings.

**Comment by omajid** [comment]
Related: https://github.com/rpminspect/rpminspect/issues/1020
