### ISSUE TITLE
Incorrect parsing of rpminspect.yaml

### ISSUE THREAD

**Issue by thoger** [rpminspect/rpminspect#998]
**Describe the bug**
There seems to be some issue with parsing of the rpminspect.yaml file, that causes global ignore list to get used as per-inspection ignore list of the last inspection in the previously listed "inspections" section.

**To Reproduce**
I'm using this rpminspect.yaml, that aims to follow the format of the system fedora.yaml file:

```
$ cat rpminspect.yaml 
inspections:
    virus: off

ignore:
    - /usr/bin/chage
```

Checking the output of `rpminspect -D`:

```
$ rpminspect-fedora -D
...
ignore:
    - /usr/lib*/python?.?/site-packages/__pycache__
    - /usr/lib*/python?.?/site-packages/*/*.pyc
    - /usr/lib*/python?.?/site-packages/*/*.pyo
...
global ignores:
    - /usr/lib*/python?.?/site-packages/__pycache__
    - /usr/lib*/python?.?/site-packages/*/*.pyc
    - /usr/lib*/python?.?/site-packages/*/*.pyo
per-inspection ignores:
    files:
        - /usr/lib/dracut
        - /usr/lib/udev
    debuginfo:
        - /lib/modules/*
        - /usr/lib/debug/.dwz/*
        - /usr/lib/grub/*
    virus:
        - /usr/bin/chage
```

See the chage file listed in the per-inspection ignore for virus.  I.e. something that should be expect when using this rpminspect.yaml file:

```
$ cat rpminspect.yaml 
inspections:
    virus: off

virus:
    ignore:
    - /usr/bin/chage
```

Note that with this second rpminspect.yaml, chage does not appear in any ignore list reported by `rpminspect -D`:

```
ignore:
    - /usr/lib*/python?.?/site-packages/__pycache__
    - /usr/lib*/python?.?/site-packages/*/*.pyc
    - /usr/lib*/python?.?/site-packages/*/*.pyo
...
global ignores:
    - /usr/lib*/python?.?/site-packages/__pycache__
    - /usr/lib*/python?.?/site-packages/*/*.pyc
    - /usr/lib*/python?.?/site-packages/*/*.pyo
per-inspection ignores:
    files:
        - /usr/lib/dracut
        - /usr/lib/udev
    debuginfo:
        - /lib/modules/*
        - /usr/lib/debug/.dwz/*
        - /usr/lib/grub/*
```

**Environment:**
rpminspect-1.11-0.1.202301091644git302586d.fc37.x86_64

**Comment by dcantrell** [comment]
This is addressed by PR #988 which I am waiting to merge until Fedora and EPEL gain the libdson package in the stable updates collections.

**Comment by dcantrell** [comment]
It fixes YAML parsing and adds support for JSON and DSON config file formats for the rpminspect.yaml file.

**Comment by dcantrell** [comment]
Confirmed this is fixed with that large PR merged.
